### ISSUE TITLE
Error in clean install

### ISSUE THREAD

**Issue by jalberto** [rmagatti/auto-session#1]
when I run `nvim` with no params:

```
Error detected while processing VimEnter Autocommands for "*":
E5105: Error while calling lua chunk: ~/.vim/plugged/auto-session/lua/auto-session.lua:8: attempt to index field 'fn' (a nil value)
```

**Comment by rmagatti** [comment]
Thanks for reporting @jalberto. 

Are you on Vim or Neovim? What version? What OS?.

This reminds me, I'll see if I can add a nice issue reporting template for the repo. 😊

**Comment by jalberto** [comment]
Thank you for your plugin :)

I am in neovim 0.4 in Linux

**Comment by rmagatti** [comment]
Hey @jalberto sorry about the delay -- can you try on the latest neovim nightly? I think this might be neovim version related.

**Comment by rmagatti** [comment]
Closing this. We can reopen if need be. As a result of this I've added a **Compatibility** section in the README. 👍
