### ISSUE TITLE
Prevents usage with startuptime plugin

### ISSUE THREAD

**Issue by akinsho** [rmagatti/auto-session#10]
Hi 👋🏿 , thanks for this great plugin. It's exactly what I was looking for to replace `vim-prosession`

One thing I seem to have lost the ability to do though is profile my vim config using https://github.com/dstein64/vim-startuptime. I believe it is getting blocked immediately trying to load session and maybe is hitting a press enter to continue prompt. Not sure, in either case when running startuptime I'd like to disable this plugin since I don't want loading sessions included in the profile.

The plugin includes arguments that can be passed to the startup time command which will be relayed to vim so I'm wondering if there could be some sort of vim global I can pass on startup that will tell this plugin not to run e.g.
```
nvim -u <rcfile> "+let g:autosession_disabled=1"
```

**Comment by akinsho** [comment]
Whilst I still think this might be useful I've actually switched to `tweekmonster/startuptime.vim` which doesn't seem to have the same issue so this might be something to do with `dstein`'s plugin

**Comment by rmagatti** [comment]
Hey @akinsho, for now a "hack" you could use is set `let g:loaded_auto_session = 1`, one of the first things the VimL portion of this plugin does is check if it has already loaded before executing the rest of the commands, this will tell it that it has been loaded, thus effectively not doing anything in the end.

Maybe try that out and lmk how it goes?

**Comment by akinsho** [comment]
@rmagatti I gave that a try but it doesn't actually stop the plugin from starting up the session. If you run that in the terminal as `nvim "+let g:loaded_auto_session = 1"` it still starts autosession

**Comment by rmagatti** [comment]
> @rmagatti I gave that a try but it doesn't actually stop the plugin from starting up the session. If you run that in the terminal as `nvim "+let g:loaded_auto_session = 1"` it still starts autosession

Well that's not fun, I'll have some time to look into it between today and tomorrow. Thanks again for reporting the issue!

**Comment by rmagatti** [comment]
@akinsho I just merged in support for disabling the auto save/restore features.
The readme is updated with usage, but all you gotta do is `nvim "+let g:auto_session_enabled = 0"`.

Hope that works for you!

**Comment by akinsho** [comment]
@rmagatti just a heads up that worked 👍🏾 thanks for working on this
