### ISSUE TITLE
[BUG] Session loading twice

### ISSUE THREAD

**Issue by mattleong** [rmagatti/auto-session#100]
**Describe the bug**
Unsure if this is expected/intended. But it looks like with the below settings, the session is restored _twice_ upon start up.

```lua
  auto_session = {
    pre_save_cmds = { 'NvimTreeClose', 'cclose', 'lua vim.notify.dismiss()' },
    auto_session_enabled = true,
    auto_restore_enabled = true,
    auto_save_enabled = true,
  },
```

When I manually restore the session with `:RestoreSession`, I only see one printing of the lines below.

**To Reproduce**
1. Use settings above
2. Auto restore a session from nvim start up

**Expected behavior**
Session is loaded only once 

**Screenshots**
<img width="799" alt="Screen Shot 2021-11-30 at 3 47 56 PM" src="https://user-images.githubusercontent.com/3721204/144146521-2ec92a90-0dea-49de-840a-8698b8cdb713.png">

**Comment by rmagatti** [comment]
Hm odd. Since those settings are already the default, mind removing the boolean settings from your setup call and seeing what you get?

**Comment by mattleong** [comment]
I still see the same behavior :/

**Comment by rmagatti** [comment]
I have never seen this happen. How about if you disable the pre save autocmds? Any different behavior then?

**Comment by mattleong** [comment]
@rmagatti Confirming I'm seeing the same behavior.

Here is my plugin list. I'm honestly not to sure as to what would be affect it since I haven't dug into the plugin code yet. My wildly speculative guess could be that it has something to do with impatient.nvim? I dunno.

<img width="269" alt="Screen Shot 2021-12-02 at 6 25 46 PM" src="https://user-images.githubusercontent.com/3721204/144534438-b1e87c9a-1381-4a5b-97a5-6a289cc1c971.png">

**Comment by rmagatti** [comment]
@mattleong, is your config public? I'd have to take a look at how things are configured, though to be honest I doubt this is an issue with auto-session itself.

**Comment by rmagatti** [comment]
Ah, from this I see you're lazy loading auto-session.
I would recommend not doing that. Auto Session itself doesn't really take much of your startup time, what takes time is the loading of the session itsef.
https://github.com/CosmicNvim/CosmicNvim/blob/main/lua/cosmic/core/pluginsInit.lua#L211

Maybe try loading it normally and see if the session still loads twice?

**Comment by mattleong** [comment]
@rmagatti ahh of course! That seems to have done the trick.

**Comment by rmagatti** [comment]
🎉

**Comment by mattleong** [comment]
Feel free to close now! Very much appreciate your assistance!
