### ISSUE TITLE
[BUG] do not save window for tree-like plugins

### ISSUE THREAD

**Issue by im-n1** [rmagatti/auto-session#105]
**Describe the bug**
I'm using nvim-tree.lua plugin and when exit vim with the tree window (on the right side) open and then open the vim again the plugin opens the same window for the tree but it's blank. I don't think it's necessary to save tree-like plugin windows.

**To Reproduce**
1. install nvim-tree.lua plugin
2. open vim, open tree window, open another file
3. exit vim
4. open vim

**Expected behavior**
no window for tree-like plugin windows

**Comment by rmagatti** [comment]
Hi, this is not really an issue with auto-session. You'll find that even if you save and restore sessions manually yourself, these plugins tend to not be savable to a session.

There are closed issues about using the plugin's hooks to close those windows before saving the session you might want to check out.
https://github.com/rmagatti/auto-session/issues/50

**Comment by im-n1** [comment]
Non of solutions in the referenced issue works for now. Nevertherless I used other plugins on old vim that handled this automatically.

**Comment by rmagatti** [comment]
Sorry to hear that @im-n1.
I'd be happy to reopen this and help you debug through why the hooks don't work for you!

I'm just not particularly interested in building support directly into the plugin to interface with tree-like plugins as then I'd need to theoretically support a potentially unlimited number of tree-like plugins. So the approach I went with here is to have customizable hooks anyone can use to tweak behaviour that interfaces with other plugins themselves. I realize this approach leans towards the more generalized and perhaps less convenient side of things, but it also makes sure I'm not spending too much time trying to keep up with every tree-like plugin out there and instead am focused on session related features.

I hope that makes sense.

Thanks again for the issue submission, let me know if you'd like help with debugging your hooks!

Cheers!

**Comment by zwhitchcox** [comment]
Just a note, I also made a [PR](https://github.com/nvim-tree/nvim-tree.lua/pull/1734) to fix this upstream in `nvim-tree`, which should work for all sessions, as it restores the `nvim-tree` after a `SessionLoadPost` event. I think this is ultimately the solution that needs to happen, but that plugin should work in the meantime!
