### ISSUE TITLE
[BUG] DeleteSession not working for paths with spaces

### ISSUE THREAD

**Issue by SimonMandlik** [rmagatti/auto-session#106]
**Describe the bug**
If there is a space in pwd, the `*.vim` file is not deleted when running `:DeleteSession`

**To Reproduce**
1. `mkdir ~/"With space"`
2. `cd ~/"With space"`
3. `nvim`
4. `:SaveSession`
5. `:DeleteSession`

**Expected behavior**
The session file should be deleted but isn't.

**Baseline (please complete the following information):**
 - OS. e.g `uname -a`: `Darwin Simons-MacBook-Pro.local 21.2.0 Darwin Kernel Version 21.2.0: Sun Nov 28 20:28:54 PST 2021; root:xnu-8019.61.5~1/RELEASE_X86_64 x86_64`
 - Neovim version `nvim --version`:  `NVIM v0.6.1`

Not using any other config besides
```
require('auto-session').setup {}
```

**Comment by rmagatti** [comment]
Interesting, might need some more sanitizing. Should be a simple fix, I'll try and check it out this weekend if someone doesn't get to it first.
