### ISSUE TITLE
Session only save two buffer

### ISSUE THREAD

**Issue by vpeopleonatank** [rmagatti/auto-session#11]
When I open multiple buffers, quit nvim, and open nvim again. But only two buffers are automatically opened
I use `:SessionSave` then `:SessionLoad`, this still occurs.

# Expected result:
All buffers are opened when reopen nvim

**Comment by rmagatti** [comment]
Hey @vpeopleonatank first off thanks for the issue submission!

I'll need some more info to dig into this, what are the contents of those buffers that aren't loaded? 

What does your `set sessionoptions?` look like?

Can you provide maybe a gif or a video showcasing the issue?

**Comment by Shatur95** [comment]
I had the same problem, make sure you don't remove `buffers` from `sessionoptions` (this is the default).

**Comment by vpeopleonatank** [comment]
After add `buffers` to `sessionoptions`, issue is solved. Thank you.
