### ISSUE TITLE
[BUG] Where are the logs going?

### ISSUE THREAD

**Issue by danielo515** [rmagatti/auto-session#122]
Hello, thanks for this plugin. I am facing some problems with it and I was wondering where can I go to check the logs

**Describe the bug**
Not a bug, but, I set the debug level do debug to troubleshoot some problems, and I don't know where to check the log now.

**Expected behavior**
To have a documentation about it

**Comment by rmagatti** [comment]
Logs only get printed, they don't get saved anywhere currently. If you set `log_level = 'debug'`, you should see more information.

What kind of problems are you facing?

**Comment by danielo515** [comment]
I already set the debug level to debug and I noticed exactly what you said.
the problem I was trying to debug, I came to the conclusion that it is namespace clashing. I have folders with the same name on different locations, and when I open them they overwrite each other

**Comment by rmagatti** [comment]
I see. It's odd though, because the way the session names work is by parsing the full path into the session name, so there shouldn't be a clash of session names. There's a chance some of the parsing plays with some special characters though and I can see that causing a clash, do you know if that was your case?

**Comment by danielo515** [comment]
can be the dot prefix of some folders be the problem? I'll have to check again

**Comment by rmagatti** [comment]
It shouldn't be an issue. Works fine for me on directories like `.aws` for example 🤔

**Comment by danielo515** [comment]
Here is the logs of the only path giving me issues:
![image](https://user-images.githubusercontent.com/2270425/163839714-94362629-b6a0-4c3d-84f7-42a0fef18d30.png)
![image](https://user-images.githubusercontent.com/2270425/163839715-9a9b9e0b-43c2-4b5a-a560-6174c63428a5.png)

**Comment by rmagatti** [comment]
Hm, I don't immediately see a problem with that session name.

Let's maybe take a step back here, what is the exact issue you're seeing when trying to load one of your sessions? I maybe a bit unclear on that still

**Comment by rmagatti** [comment]
Stale

**Comment by danielo515** [comment]
Yes, sorry I was not able to reproduce the problem again.
I'll provide better insights next time

**Comment by rmagatti** [comment]
@danielo515 all good, thanks!
