### ISSUE TITLE
[BUG] git branch save session fails if branchname contains a forward-slash

### ISSUE THREAD

**Issue by timtyrrell** [rmagatti/auto-session#124]
**Describe the bug**
With the new `auto_session_use_git_branch = true,` setting, branch names with a forward-slash do not save

**To Reproduce**
1. create local branch with slash like `test/test`
2. set `auto_session_use_git_branch = true,`
3. open nvim, open file, close nvim
4. using `nvim -V9myVim.log` command I see error:
```
v...l/.config/nvim/plugged/auto-session/lua/auto-session.lua:300: Vim(mksession):E190: Cannot open "/Users/timothy.tyrrell/.local/share/nvim/sessions/%Users%timothy.tyrrell%code%timtyrrell%dotfiles_test/test.vim" for writing
stack traceback:
^I[C]: in function 'cmd'
^I...l/.config/nvim/plugged/auto-session/lua/auto-session.lua:300: in function 'SaveSession'
^I...l/.config/nvim/plugged/auto-session/lua/auto-session.lua:263: in function <...l/.config/nvim/plugged/auto-session/lua/auto-session.lua:254>
```

**Expected behavior**
It strips out the forward-slash or converts to another value.

**Screenshots**

**Baseline (please complete the following information):**
 - Result of `set sessionoptions?`: sessionoptions=blank,curdir,folds,tabpages,winsize
 - OS. e.g `uname -a`: Darwin ******* 21.4.0 Darwin Kernel Version 21.4.0: Fri Mar 18 00:45:05 PDT 2022; root:xnu-8020.101.4~15/RELEASE_X86_64 x86_64
 - Neovim version `nvim --version` NVIM v0.7.0-dev+1443-gdbd5242d8
 - URL to your current config (if public) https://github.com/timtyrrell/dotfiles/blob/main/init.vim#L1650-L1657

**Comment by WhoIsSethDaniel** [comment]
Hi. This is my fault. I don't use forward slashes in my branches and simply didn't test that scenario. Oddly I have used forward slashes in branch names in the distant past.  I'll see if I can look at this soon.
