### ISSUE TITLE
[Q] On which events SaveSession happens automatically?

### ISSUE THREAD

**Issue by edshamis** [rmagatti/auto-session#125]
Couldn't find in readme, sorry if missed

**Comment by rmagatti** [comment]
@edshamis I suppose it's not mentioned in the readme indeed.
It's only on VimLeave currently.

https://github.com/rmagatti/auto-session/blob/main/plugin/auto-session.vim#L36

**Comment by edshamis** [comment]
Do you think is it possible to add configuration to define events for session saving? 
For example I'd definitely want to update session on every layout or buffers list change.

**Comment by edshamis** [comment]
Well, I can do it with autocmd. Thanks!

**Comment by rmagatti** [comment]
Hey, yeah you can do it with autocmds yourself. I don't really want to add the ability to mix and match when sessions get saved necessarily, that might make debugging things a lot harder when something goes wrong. I did want to experiment with making the plugin save sessions automatically on some more autocmds than just on Leave by default but haven't gotten to that yet
