### ISSUE TITLE
Question on session save command

### ISSUE THREAD

**Issue by zlksnk** [rmagatti/auto-session#13]
If I:
1. Open dir in NVim using `nvim`
2. Close NVim so a session file is created.
3. Open NVim, but this time using `nvim .`
4. Make few changes in window layout and overwrite session using `:SaveSession`.
4. Make few changes in window layout again and close NVim.
5. Open NVim using `nvim`

This restores the layout when `SaveSession` is called instead of when NVim is closed. Is this expected behaviour?

**Comment by rmagatti** [comment]
Hey @zlksnk, yeah it is for now. The plugin doesn't take into consideration that you manually called `SaveSession`, and the flag it had previously set when opening Neovim that it's open in "pager mode" is still set to true, so AutoSaveSession isn't triggered.

I'd be happy to accept a PR for overriding this behaviour though if it's done in a configurable way i.e based on a setup config option.

That said I think the current behaviour makes more sense, at least from the perspective of my own workflow.

It should be as simple as overriding the in pager mode flag to false when triggering a `SaveSession` command.

**Comment by zlksnk** [comment]
To be honest I don’t understand what “pager mode” means here. Maybe I’m unfamiliar with pager mode at all. Do you have a document or a link that you can point me to so I can read more about it?

**Comment by rmagatti** [comment]
If you check the vim portion of the plugin, it sets an autocmd on [StdinReadPre](https://www.github.com/rmagatti/auto-session/tree/main/plugin%2Fauto-session.vim).

Based on that the pager flag is set, it basically means vim is reading from stdin.

You can read more in `:h StdinReadPre`.

**Comment by rmagatti** [comment]
I'm gonna leave this open to track maybe adding a flag to override this behaviour.

**Comment by zlksnk** [comment]
I'm fairly new to Vim (and so to this plugin ecosystem and the languages involved) but I'll try to tackle this. Any plugins or tools do you suggest to make it easier to develop Lua/VimScript based plugins?

**Comment by rmagatti** [comment]
I just use native lsp and installed a language server for both Lua and Vimscript. 

Also, that would be awesome, thanks! Let me know if you have any questions.

**Comment by zlksnk** [comment]
Been totally busy with work, that's why I'm taking days to reply, hope you understand. (Also, timezones.)

I realized my original intention was totally different. The reason I was doing `vim .` is because I was trying to create a fresh session (delete existing session before creating a new one with the same name). Because all sessions are stored in a separate directory there was just no easy way for me to delete the previous session. Is there a way to skip loading existing session if there is any? Currently I need to hunt it down in sessions directory.

I too agree in keeping pager mode functionality as it is.

**Comment by rmagatti** [comment]
Oh totally, same here 😄 

So today you can disable the auto loading of sessions by doing `nvim "+let g:auto_session_enabled = 0"`.
This makes auto-session bypass the auto restoration and the auto saving of sessions altogether.

Maybe this fits your needs?

**Comment by zlksnk** [comment]
> you can disable the auto loading of sessions by doing nvim `"+let g:auto_session_enabled = 0"`

And then using `:let g:auto_session_enabled = 1` inside nvim to overwrite existing session on close. Yeah that certainly works. 

Okay let's keep this issue open, I'll explore some ideas and I'll come back to you.

**Comment by zlksnk** [comment]
One idea that I liked is to introducing a command `NewSession`. One can call nvim using `nvim "+NewSession"` to remove existing session so that nvim can be loaded with a clean slate. A session will be created when nvim is closed as per usual.

**Comment by rmagatti** [comment]
Yeah I see what you mean, the plugin already has a `:DeleteSession` command I just hadn't exposed yet (it's exposed now).
One could setup a flag to pass on startup to make auto session delete the session instead of trying to restore it if it finds one.

I mostly see this being useful for cases where sessions are broken and you don't want to load them in the first place, because if it's just about deleting the current session, you can already do that by just calling `:DeleteSession` with no args.

**Comment by rmagatti** [comment]
With the new feature in the linked PR you could open nvim like so.
`nvim "+let g:auto_restore_enabled = 0"`, which would mean it doesn't try to restore the session, you can then subsequently call `SaveSession` and that will override the session for the cwd. This should cover the case you mentioned without having to delete the session at all. 

If that's not the case we can reopen this. :)

**Comment by zlksnk** [comment]
That solves my problem perfectly, thanks!
