### ISSUE TITLE
[BUG] auto_session_use_git_branch breaks if a directory which is not a git repository is opened

### ISSUE THREAD

**Issue by akinsho** [rmagatti/auto-session#131]
**Describe the bug**
When using `auto_session_use_git_branch` I've found that switching to a project that is not under version control e.g. my notes stored elsewhere and opening neovim in this directory throws the following error

<img width="855" alt="Screen Shot 2022-05-06 at 08 15 04" src="https://user-images.githubusercontent.com/22454918/167077171-146501a0-e256-47b8-b8e5-f977d445f268.png">

**To Reproduce**
1. Go to a non-version controlled directory
2. Open neovim

**Expected behavior**
A session should be created and keyed to the directory the same as without the use git branch setting

**Baseline (please complete the following information):**
 - Result of `set sessionoptions?`: `sessionopts=globals,curdir,winpos,help,buffers`
 - OS. e.g `uname -a`: MacOS
 - Neovim version `nvim --version`: 0.7.0
 - URL to your current config (if public)

**Additional context**

**Comment by rmagatti** [comment]
Hey @akinsho while trying to reproduce here I noticed the expected behaviour you mentioned still happens correctly. It just seemingly breaks because of the `vim.api.nvim_err_writeln(string.format("git failed with: %s", table.concat(out, "\n")))` call.
> A session should be created and keyed to the directory the same as without the use git branch setting

I can just debug log instead to make it more seamless.

**Comment by akinsho** [comment]
@rmagatti that sounds good, actually I did notice it loading just the presentation of the error seemed very much like something had failed
