### ISSUE TITLE
[BUG] Ignoring certain buffer types

### ISSUE THREAD

**Issue by ziombo** [rmagatti/auto-session#133]
**Describe the bug**
When using auto-session with certain plugins that create buffers, these buffers are included in the session save and are broken when loaded. For example if the functionality from [treesitter-context](https://github.com/nvim-treesitter/nvim-treesitter-context) is currently in use and you save session, the next time you load it, there will be an additional empty buffer opened. 
The first two lines are from  ts-context:
![image](https://user-images.githubusercontent.com/15613606/172439248-b6d458d5-5ab6-48f9-b6da-5642ce743106.png)
After saving and restoring the save:
![image](https://user-images.githubusercontent.com/15613606/172439383-4b5ab227-a650-4a4c-8e2d-256ff85fde7b.png)
a buffer with no name is restored together with 1 line of height.

A similar thing was happening when I was using [incline.nvim](https://github.com/b0o/incline.nvim), can't come up with other examples atm. but I'm assuming anything that creates some sort of window/buffer that's used to display something on screen, yet is not visible in the bufferlist.

**Comment by ziombo** [comment]
Great, I pretty much managed to get what I wanted with this code (sorry for providing it via screenshot, I don't have clipboard properly configured for wsl):
![image](https://user-images.githubusercontent.com/15613606/172463368-c5e33a91-1b8b-46b1-9076-10884bdd055b.png)

One caveat is that since it's closing the treesitter_context window on save, I have to somehow get it back if I'm triggering the save manually, that's why I'm sending _j_ and _k_. 

I know there's a function to hide a windowinstead of closing it, which seems to be working as well, however I couldn't find a way to bring the window back. Do you know if it's possible? If not, then I think the issue can be closed since I'm achieving what I wanted with one small side-efect which is flashing the top row

**Comment by ziombo** [comment]
Sorry for no response for quite some time. My current use case for this is calling my alias that opens my neovim config, which doesn't trigger the automatic save/load so I do these manually. 

Anyway, your solution works for me so I think it's fine to close this issue. Thanks!

**Comment by FormalSnake** [comment]
> incline.nvim

sorry to activate this old thread, but what was your final code in the config?
