### ISSUE TITLE
[BUG] DeleteSession not working 

### ISSUE THREAD

**Issue by thecontinium** [rmagatti/auto-session#138]
**Describe the bug**

This session file `/Users/thecontinium/.local/share/nvim/sessions/%Users%thecontinium%dev%project%dim%clojure.vim`
exists.

:DeleteSession  /Users/thecontinium/dev/project/dim/clojure
Gives this error with log level debug:

``` vim
debug session_file_path /Users/thecontinium/.local/share/nvim/sessions//\%Users\%thecontinium\%dev\%project\%dim\%chosen.vim
Vim:E474: Invalid argument
stack traceback:
^I[C]: in function 'delete'
^I...os/github.com/rmagatti/auto-session/lua/auto-session.lua:471: in function 'DeleteSession'
^I...os/github.com/rmagatti/auto-session/lua/auto-session.lua:457: in function <...os/github.com/rmagatti/auto-session/lua/auto-session.lua:449>
```

On line 471 the expand function looks to be returning an empty string.

**To Reproduce**
As above

**Expected behavior**
Deletes session without an error

**Screenshots**
N/A

**Baseline (please complete the following information):**
 - Result of `set sessionoptions?`:curdir,help,tabpages,winsize
 - OS. e.g `uname -a`:Darwin dimension.local.mac-nfs 20.6.0 Darwin Kernel Version 20.6.0: Mon Aug 30 06:12:21 PDT 2021; root:xnu-7195.141.6~3/RELEASE_X86_64 x86_64
 - Neovim version `nvim --version`NVIM v0.7.0
 - URL to your current config (if public)

**Additional context**
N/A

**Comment by rmagatti** [comment]
Hey 👋 I'm not quire sure how you got a vim directory to not end up being called `%Users%thecontinium%dev%project%dim%clojure.vim.vim`, maybe the session was created with a previous version that didn't used to handle `.vim` directories correctly?

Either way, I just tested this and it does work when the session name follows the latest pattern. Maybe try deleting that session file then recreating it from the latest auto-session version and see if that works out? Lmk if it doesn't. 
<img width="831" alt="Screen Shot 2022-06-25 at 3 21 52 AM" src="https://user-images.githubusercontent.com/2881382/175765093-c269d558-de19-4e5b-a581-90c5ad2d8f2a.png">

**Comment by thecontinium** [comment]
Hi Thanks for the reply. 

re: your comment "... not end up being called ..."; sorry  - I think I must have copied the wrong debug above.

I am running the latest version.
Here are the steps I have just done which I think replicates you.
Hopefully this detail helps clarify my problem.

```sh
❯ pwd
/tmp/thedir

nvim
:SaveSession 

debug ==== SaveSession
debug Running pre-save command: lua require("interface").win.close_plugin_owned()
info Session saved at /Users/thecontinium/.local/share/nvim/sessions/\%private\%tmp\%thedir.vim

:DeleteSession <Tab>
:DeleteSession /private/tmp/thedir

debug Auto Save disabled for current session. {
  current_session = "\\%private\\%tmp\\%thedir",
  session_name = "\\%private\\%tmp\\%thedir"
}
debug session_file_path /Users/thecontinium/.local/share/nvim/sessions//\%private\%tmp\%thedir.vim
Vim:E474: Invalid argument
stack traceback:
^I[C]: in function 'delete'
^I...os/github.com/rmagatti/auto-session/lua/auto-session.lua:471: in function 'DeleteSession'
^I...os/github.com/rmagatti/auto-session/lua/auto-session.lua:457: in function <...os/github.com/rmagatti/auto-session/lua/auto-session.lua:449>
```

```sh
❯ pwd
/Users/thecontinium/.local/share/nvim/sessions
❯ ls
%private%tmp%thedir.vim
```

**Comment by thecontinium** [comment]
I'm not sure why you are using the expand function here but if I remove it so that the line reads:

``` lua
   vim.fn.delete(file_path)
```

then it works for me.

**Comment by thecontinium** [comment]
I think the answer is to create a util_expand function that does something along the lines of:

1. saves the value of wildignore
2. set wildignore=""
3. e = expand stuff
4.  set wildignore back to the saved value
5. return e

For all places you call expand call util_expand.

If I find time I'll raise a PR.
