### ISSUE TITLE
[BUG] Directories with spaces in their name are not saved

### ISSUE THREAD

**Issue by thecontinium** [rmagatti/auto-session#139]
**Describe the bug**
Sessions are not saved when a directory has a space in it's name 

**To Reproduce**
:cd directorywitha\ initsname
:SaveSession

**Expected behavior**
Session saved and loaded like any other directory

**Screenshots**
na

**Baseline (please complete the following information):**
 - Result of `set sessionoptions?`:curdir,help,tabpages,winsize
 - OS. e.g `uname -a`:Darwin dimension.local.mac-nfs 20.6.0 Darwin Kernel Version 20.6.0: Mon Aug 30 06:12:21 PDT 2021; root:xnu-7195.141.6~3/RELEASE_X86_64 x86_64
 - Neovim version `nvim --version`NVIM v0.7.0
 - URL to your current config (if public)

**Additional context**
N/A

**Comment by rmagatti** [comment]
Hey @thecontinium sorry about the delay. I can't seem to reproduce. I'm on Neovim master. This still happen to you?

**Comment by thecontinium** [comment]
working with current version
