### ISSUE TITLE
Option to disable startup message?

### ISSUE THREAD

**Issue by mvllow** [rmagatti/auto-session#14]
Hey there, thanks for the lovely plugin 😌

Is there a way to disable having to press enter on startup?

<img width="694" alt="Screen Shot 2021-05-03 at 11 17 29" src="https://user-images.githubusercontent.com/1474821/116902769-27f14480-ac01-11eb-9563-f9ce3fa9c366.png">

edit: this doesn't seem to happen every single time, and may be an issue with my config

**Comment by rmagatti** [comment]
> Hey there, thanks for the lovely plugin 😌
> 
> Is there a way to disable having to press enter on startup?
> 
> <img alt="Screen Shot 2021-05-03 at 11 17 29" width="694" src="https://user-images.githubusercontent.com/1474821/116902769-27f14480-ac01-11eb-9563-f9ce3fa9c366.png">
> 
> edit: this doesn't seem to happen every single time, and may be an issue with my config

Yeah that happens because of [this.](https://vim.fandom.com/wiki/Avoiding_the_%22Hit_ENTER_to_continue%22_prompts) 

You can set the config `logLevel = 'error'` to only print errors from the plugin, or alternatively you can `set cmdheight=3`.
