### ISSUE TITLE
[BUG] vim.fs not available in stable neovim release

### ISSUE THREAD

**Issue by bit101** [rmagatti/auto-session#145]
**Describe the bug**
Running `:AutoSession search` or `:AutoSession delete` results in an error of `attempt to index 'fs' (nil value)`.
This is due to the fact that `vim.fs` is not available in the 0.7.2 stable release of neovim. It is only in the development / nightly release.

**To Reproduce**
Run one of the two commands above.

**Expected behavior**
Just that the above actions would work.

**Screenshots**
n/a

**Baseline (please complete the following information):**
 - Result of `set sessionoptions?`:
 `blank,buffers,curdir,folds,help,tabpages`
 - OS. e.g `uname -a`:
 `5.18.7-1-Manjaro`
 - Neovim version `nvim --version`
 `0.7.2`
 - URL to your current config (if public)
 n/a

**Additional context**
The code that utilizes `vim.fs` was added just 5 days ago.

**Comment by akinsho** [comment]
@rmagatti this is my bad, I've been on nightly for so long I'd completely forgotten this feature wasn't in nvim stable. I'll raise a PR to see if there's another way to get this info

**Comment by rmagatti** [comment]
Ah, that's my bad too, been running builds from source on master for a while now and completely forgot to check stable 😅
