### ISSUE TITLE
Option to ignore certain directories

### ISSUE THREAD

**Issue by Adictya** [rmagatti/auto-session#15]
**Description:**
1. A global variable to store list of blacklisted directories which would not auto save/restore sessions. eg. 
``` vim
let g:auto_session_ignore = ["~/","~/Expermiments"]
```
2. Optionally matched using regex (*) operator to handle all sub directories eg.
``` vim
let g:auto_session_ignore = ["~/Expermiments/*"]
``` 
   doesnt save session for all sub directories of Experiments

**Motivation**

First of all amazing plugin, after sifting through loads of legacy plugins I was able to find just what I was looking for.

However my usage pattern involves opening up my terminal by default in home directory and relying on [startify](https://github.com/mhinz/vim-startify/) to navigate. It would be greate if I could still reatain that somewhat as I use it to primarily navigate to my config files. I also have an experiments folder where I prefer to not have the auto session behaviour. Could be a nice to have feature for those who need it?

**Comment by Adictya** [comment]
#16

**Comment by rmagatti** [comment]
Hey, thanks for the submission @Adictya.
Yeah I agree that would be a welcome addition!

**Comment by rmagatti** [comment]
Implemented in https://github.com/rmagatti/auto-session/pull/17
