### ISSUE TITLE
[BUG] This plugin only really works if you use tpope vim-obsession

### ISSUE THREAD

**Issue by dagadbm** [rmagatti/auto-session#152]
If I have a buffer and do ctrl-w  s (to create a splice)
and quit nvim using: cq

auto-session doesnt remember the buffer changes.

If I do the same with tpop/vim-obsession plugin installed it just works.

**Comment by rmagatti** [comment]
Hi, let's break things down.
1. This plugin works by itself. What you're seeing is either a bug or a misconception on _how_ this plugin works.
2. vim-obsession is a different plugin altogether, these two have no correlation aside from the fact they aim to handle sessions.

vim-obsession does save a session when buffer changes happen, auto-session currently only saves on exit of nvim, this might be the misconception I mentioned before.

I do plan on making it work with buffer and window changes soon, just haven't had the time to try it out lately. Let me know if this does not clarify things!

**Comment by dagadbm** [comment]
i see!

cant wait for those changes to land . one less vim script plugin for me to
manage

**Comment by rmagatti** [comment]
@dagadbm meanwhile you probably shouldn't use both auto-session _and_ vim-obsession. These two plugins do not work together.

Also, is there a specific use case you have for saving sessions on buffer/window change?

**Comment by rmagatti** [comment]
Closing. Stale. Feel free to reopen.
