### ISSUE TITLE
[BUG] Changes current directory to VCS root directory and if session file is not found shows error

### ISSUE THREAD

**Issue by arionrefat** [rmagatti/auto-session#157]
When I try to open a file that not in VCS root directory, it open a empty buffter with the following error
![image](https://user-images.githubusercontent.com/37513070/183305200-868d084d-b6d4-4b8b-8e58-3da7f7c43f2b.png)

**To Reproduce**
Suppose a git root folder name `my_project`
you want to open a file that is in `my_project/org-mode/todo.org`
then the following error occurs

**Expected behavior**
It should just open the file without file without creating an empty buffter without an error

**Baseline:**
 - Result of `set sessionoptions?`: 
![image](https://user-images.githubusercontent.com/37513070/183305359-ea8d48f5-51cb-413e-b9ac-a55e7be076aa.png)
 - OS : `Arch Linux`
 - Neovim version: 
```NVIM v0.7.2
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by builduser

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"
```
 - URL to your current config: https://github.com/arionrefat/dotfiles/blob/master/neovim/.config/nvim/lua/user/sessionmanager.lua

**Additional context**
Sorry if give less information, please let me know what you need to know

**Comment by ray-x** [comment]
https://user-images.githubusercontent.com/1681295/183313693-c3b42b74-69bb-4bd3-ae12-5b2c56f26794.mp4

I saw the same thing here.

**Comment by rmagatti** [comment]
Hey thanks for the issue submission! When you open the file, do you have anything in your config that changes the cwd? This message only happens here:
https://sourcegraph.com/github.com/rmagatti/auto-session/-/blob/lua/auto-session-autocmds.lua?L45

**Comment by rmagatti** [comment]
@arionrefat, from your config I can see you have nvim-tree with the `update_cwd` config set to `true`. This would explain that message getting triggered.

Maybe the ideal thing to have for auto session `cwd` handling be disabled by default as some people seem to be running into things like this.

For my workflow I don't have anything that changes the cwd so this never showed as a problem but I'll make that change. 👍

**Comment by rmagatti** [comment]
Similar case I think
https://github.com/rmagatti/auto-session/issues/158

**Comment by rmagatti** [comment]
@ray-x and @arionrefat mind testing out this branch before I merge it?

**Comment by ChristianChiarulli** [comment]
@rmagatti I tested the branch and it seems to fix the issue for me.

**Comment by rmagatti** [comment]
@ChristianChiarulli Cool thanks!. Just wanted at least one other person to test it. Merging it now 👍
