### ISSUE TITLE
A session file is likely missing for this cwd.

### ISSUE THREAD

**Issue by xbladesub** [rmagatti/auto-session#158]
I started to receive this message:
"info Could not load session. A session file is likely missing for this cwd. <PATH>". What does it mean and how can I fix it?
I started after PackerUpdade

**Comment by rmagatti** [comment]
Hey @xbladesub, this happens upon handling the `DirChanged` autocmd. It shouldn't be happening a lot unless you've got something changing your `cwd` frequently.
https://sourcegraph.com/github.com/rmagatti/auto-session/-/blob/lua/auto-session-autocmds.lua?L45

Do you see any degradation in any existing functionality or just the message?

**Comment by ChristianChiarulli** [comment]
I'm also noticing this issue, maybe it's nvimtree or project.nvim but I never noticed this behavior before.
