### ISSUE TITLE
[BUG]debug warning on startup: "debug: cwd_chnage_handling is disabled, skipping setting DirChangedPre ..."

### ISSUE THREAD

**Issue by aj3423** [rmagatti/auto-session#163]
**Describe the bug**
There are two lines of debug warning on every startup: 

> debug: cwd_change_handling is disabled, skipping setting DirChangedPre and DirChanged autocmd handling 
> debug: ==== Pager mode

**To Reproduce**
1. Launch Nvim

**Expected behavior**
No debug output.

**Screenshots**
![image](https://user-images.githubusercontent.com/4710875/184623828-9b884977-68fa-4db2-b598-8241ccffc1d3.png)

**Baseline (please complete the following information):**
 - Result of `set sessionoptions?`: 
   sessionoptions=blank,buffers,curdir,folds,help,tabpages,winsize,resize,winpos
 - OS. e.g `uname -a`:
   Linux kali 5.18.0-kali5-amd64 #1 SMP PREEMPT_DYNAMIC Debian 5.18.5-1kali6 (2022-07-07) x86_64 GNU/Linux
 - Neovim version `nvim --version`
   NVIM v0.8.0-dev-699-gcbfae548e

**Comment by rmagatti** [comment]
Do you have `logLevel` set to `debug` in your `setup{}` function call?
