### ISSUE TITLE
[BUG] Folds are not saved for session

### ISSUE THREAD

**Issue by huynle** [rmagatti/auto-session#166]
**Describe the bug**
With `set sessionoptions=curdir,help,tabpages,winsize,folds,winpos`, i tried to issue folds in my markdown and close out. when reopening vim, the file and windows are all there, but the folds are unfolded.

**To Reproduce**
1. add 'folds' to your `set sessionoptions`
2. go to a file, and issue a fold command, `zM` or something of that sort
3. close neovim, and reopen
4. folds are not restored

**Expected behavior**
Folds need to be restored to previous state before closing neovim 

**Baseline (please complete the following information):**
 - Result of `set sessionoptions?`:  curdir,help,tabpages,winsize,folds,winpos
 - OS. e.g `uname -a`: Linux, fedora
 - Neovim version `nvim --version`: nvim v0.8.0

**Comment by rmagatti** [comment]
Hey, I'm actually unable to reproduce. Folds seem to restore fine for me. 

![2022-09-17 23 13 45](https://user-images.githubusercontent.com/2881382/190886853-ce5cea68-28d5-4bdd-8650-0abe212f61ba.gif)

**Comment by rmagatti** [comment]
Closing, feel free to reach out if for some reason this is still not working for you.
