### ISSUE TITLE
[QUESTION] How to remove "Press ENTER or type command to continue" line

### ISSUE THREAD

**Issue by tomzaku** [rmagatti/auto-session#167]
I'm using the new version of auto-session, but I'm having this message when I open nvim. May I know how can I ignore this message and open directly the files

My config:

```
lib.setup({
  log_level=""
})
```

<img width="857" alt="image" src="https://user-images.githubusercontent.com/19413272/185681625-269aa4ef-e0e1-4737-82e8-5e5d30436b4b.png">

```
"file/path...."
Press ENTER or type command to continue
```

**Comment by rmagatti** [comment]
Hey, try setting the log level to "error" that means no info logs will be printed which in combination with your cmdheight might be what's causing you to see this message and have to press enter

**Comment by tomzaku** [comment]
It's working from myside. Thank you so much
