### ISSUE TITLE
[FEATURE] Way to save `titlestring` as session name

### ISSUE THREAD

**Issue by aj3423** [rmagatti/auto-session#169]
**Is your feature request related to a problem? Please describe.**
  There is no title when a session is opened, so when multiple projects(sessions) opened, they all look like "[No Name] -- NVIM" on the task bar, hard to distinguish by name.

  Currently my workaround is `set titlestring=ProjectName`, but it's not saved to session by default, I also have to  set `vim.opt.sessionoptions:append('options')` in *init.lua*. It works but the problem is, it saves all options including all plugins' configuration, so every time I change any plugin option, I have to delete and re-create all the project sessions to make it apply.

**Describe the solution you'd like**
  A per-directory-scoped switch that can be turned on to set `titlestring` to the directory name, or specified name.

**Describe alternatives you've considered**
  Maybe there is a way to only save `titlestring` in session without saving other options?

**Additional context**

**Comment by rmagatti** [comment]
Hey @aj3423 since titlestring isn't really something that gets saved in a session this is how I've been addressing what you mention. I set a lualine section to the current session name identified by auto-session. You can do something similar with auto-session hooks and the `title` and `titlestring` options if that's what you prefer using.

```lua
require('lualine').setup{
  options = {
    theme = 'tokyonight',
  },
  sections = {lualine_c = {require('auto-session-library').current_session_name}}
}
```

**Comment by aj3423** [comment]
@rmagatti Thanks, the `current_session_name()` works, now I use it in a `SessionLoadPost` event. 
```lua
-- set titlestring as dir name
vim.api.nvim_create_autocmd('SessionLoadPost', {
	pattern = '*',
	command = 'lua vim.opt.titlestring = require("auto-session-library").current_session_name()'
})
```
