### ISSUE TITLE
[BUG] Segmentation fault when using `cmdheight=0` on latest nightly

### ISSUE THREAD

**Issue by igorlfs** [rmagatti/auto-session#170]
**Describe the bug**
Launching neovim from a directory that has a saved session crashes it.

**To Reproduce**
1. Set `cmdheight=0` in your config (setting it using `:set` does not trigger a crash)
2. Save a session and quit
3. Try to restore the session by launching nvim again

**Expected behavior**
Neovim shouldn't crash

**Baseline (please complete the following information):**
 - Result of `set sessionoptions?`: `blank,buffers,curdir,folds,help,tabpages,winsize,terminal`
 - OS. e.g `uname -a`: Linux 5.19.8
 - Neovim version `nvim --version`
 ```
 NVIM v0.8.0-dev-1103-ga0642ec75e
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
```

**Additional context**

**Comment by rmagatti** [comment]
Hey @igorlfs, this looks like something that should be handled upstream in neovim/neovim. This plugin doesn't really do anything special when it comes to `cmdheight` handling.

**Comment by igorlfs** [comment]
> this looks like something that should be handled upstream in neovim/neovim
I see 😅

I'll be closing then

**Comment by rmagatti** [comment]
If you do end up opening an upstream issue, feel free to reference it here though so when people come searching they can easily find where to go 😄
