### ISSUE TITLE
[BUG] Tabs not restored

### ISSUE THREAD

**Issue by simonmandlik** [rmagatti/auto-session#171]
**Describe the bug**
Tabs are not properly restored after upgrading to Nvim 0.7

**To Reproduce**
1. `touch a b && nvim`
2. `:e a | tabnew b | SaveSession`
3. `:qa`
4. `nvim`

**Expected behavior**
Two tabs `a` and `b` with `b` in focus. Instead, only `b` is shown

**Baseline (please complete the following information):**
 - Result of `set sessionoptions?`: `sessionoptions=winpos,terminal`
 - OS. e.g `uname -a`: `MacOS Monterey`
 - Neovim version `nvim --version` `NVIM v0.7.2`

**Comment by rmagatti** [comment]
@simonmandlik hey, your `sessionoptions` doesn't include `tabpages`. Try adding that and see if you get the behaviour you were expecting.

**Comment by simonmandlik** [comment]
That was it, thanks :) A dumb error when rewriting config from vimscript to lua
