### ISSUE TITLE
[BUG] 51ac94b generates *x.vim files unconditionally

### ISSUE THREAD

**Issue by wilriker** [rmagatti/auto-session#172]
**Describe the bug**
Since commit [51ac94b](https://github.com/rmagatti/auto-session/commit/51ac94b2b579e1b291b666f56e04e3c2e009af77) auto-session will generate a `*x.vim` file unconditionally (for a functionality I do not use) loading my session list up with garbage entries.

**To Reproduce**
1. Load any session
2. Write session

**Expected behavior**
Only the current session is saved unless I add some data to the new `saveextra` hook.

**Comment by rmagatti** [comment]
Yeah the expected behaviour you mention should have been the behaviour from the start. Should be an easy fix 👍

**Comment by wilriker** [comment]
Thanks! I can confirm it works now as (I) expected (it). :-)
