### ISSUE TITLE
[FEATURE] Rename user commands in the form :Session*

### ISSUE THREAD

**Issue by steliyan** [rmagatti/auto-session#175]
**Is your feature request related to a problem? Please describe.**
It's a bit difficult to issue a plugin auto command, e.g. `SaveSession`, `RestoreSession`.

**Describe the solution you'd like**

**Describe alternatives you've considered**
I wanted to try to do it myself, by that I mean to be able to manually rename the plugin's user commands. Haven't found a way, if there is, it would be great. :)
`:delcommand` is a possibility, but then I need to copy/paste the plugin definitions. Not ideal, but a possibility.

**Additional context**
Generally speaking, it's good to have the command in the form of `<PluginName><Action>` as this helps discoverability as well. Personally, I don't have the habit of reading the docs.

EDIT: Kinda the same proposal for [`Vundle`](https://github.com/VundleVim/Vundle.vim/issues/76#issuecomment-1871344).

**Comment by rmagatti** [comment]
Hey, I wouldn't mind renaming these, as long as for a while the other commands just show up as deprecated so as to not immediately just break for people.

**Comment by WhoIsSethDaniel** [comment]
@steliyan have you considered using `:cabbrev`?
e.g.
```vim
:cabbrev SaveSession SessionSave
:cabbrev RestoreSession SessionRestore
...
```
It may be able to tide you over until this happens.

**Comment by steliyan** [comment]
@rmagatti, yep, sounds reasonable. :)

@WhoIsSethDaniel, awesome, didn't know this existed. Doesn't work with https://github.com/hrsh7th/cmp-cmdline out of the box, tho.

Using this:
```lua
vim.cmd([[
  cabbrev <expr> SessionSave getcmdtype() == ":" && getcmdline() == "SessionSave" ? "SaveSession" : "SessionSave"
]])
```
