### ISSUE TITLE
[BUG] No name buffers cause issues with buffer name already existing.

### ISSUE THREAD

**Issue by danielyrovas** [rmagatti/auto-session#176]
**Describe the bug**
No name buffers cause auto-session to disable itself and fail to load saved sessions.

**To Reproduce**
1. Install [wfxr/minimap.vim](https://github.com/wfxr/minimap.vim)
2. SaveSession, when minimap is open
3. load session
4. Many errors (I think due to the no-name buffer appearing twice)

**Expected behavior**
Should load without errors

**Screenshots**
![image](https://user-images.githubusercontent.com/72130039/192800476-84c6eb07-bf64-4b1a-8d27-4f92eebd3ac5.png)

**Baseline (please complete the following information):**
 - Result of `set sessionoptions?`: blank, buffers, curdir, folds, help, tabpages, winsize, terminal
 - OS. e.g `uname -a`: Linux desktop 5.19.10-arch1-1 #1 SMP PREEMPT_DYNAMIC Tue, 20 Sep 2022 15:17:59 +0000 x86_64 GNU/Linux
 - Neovim version `nvim --version': NVIM v0.8.0-dev-1059-g2d6735d8c

I also occasionally run into this error when I have saved a session containing a no-name buffer.
Could no-name buffers simply be excluded from being saved?
Thanks

**Comment by rmagatti** [comment]
Hey 👋 , auto session doesn't really control which buffers get saved versus which ones don't, that's up to Neovim's built-in `mksession`. That said, through a hook you can make sure to delete unnamed buffers before the saving of sessions happen.

Check out the main README.md for information on how to setup a `pre_save` hook, in there you'd run a command to delete any unnamed buffers.

**Comment by anthrotype** [comment]
Did anybody find a solution for how to make [wfxr/minimap.vim](https://github.com/wfxr/minimap.vim) and auto-session work together?

**Comment by rmagatti** [comment]
@anthrotype have you tried using the `pre_save` hook I mentioned above?

**Comment by anthrotype** [comment]
I'm not familiar with vimscript or lua so I wouldn't know how to write that..

**Comment by rmagatti** [comment]
There's information in the readme on how to set hooks up but here's how the code for the setup might look specifically to delete

```lua
require("auto-session").setup {
  log_level = "error",
  pre_save_cmds = {
    function()
      local buffers = vim.api.nvim_list_bufs()
      for _, buffer in ipairs(buffers) do
        if vim.api.nvim_buf_get_name(buffer) == "" then
          vim.api.nvim_command("bwipeout! " .. buffer)
        end
      end
    end
  },
}

```

**Comment by rmagatti** [comment]
Stale and it looks like the solution above might work. Closing
