### ISSUE TITLE
[FEATURE] Example of how to set custom path for sessions to be saved in nvim config directory?

### ISSUE THREAD

**Issue by thepenguinthatwants** [rmagatti/auto-session#177]
Hiya,
Thanks for the interesting plugin.
I am trying to configurate this plugin to save all sessions to my ~/.config/nvim/sessions/ folder, but haven't gotten it to succeed yet.
Any clue why it fails? 

```

require('session-lens').setup {
    path_display={'shorten'},
}

require("auto-session").setup {
  log_level = "error",
  auto_session_enable_last_session = false,
  auto_session_root_dir = vim.fn.stdpath('data').."~/.config/nvim/sessions/",
}
```

I can easily switch to other sessions using session lens, but I want this plugin to only save sessions when I want to separately create a session and sessions files to be on a easily accessible location. Right now it has created tons of sessions and I don't even know where to delete obsolete ones.

**Comment by rmagatti** [comment]
Hi, you're concatenating the standard `vim.fn.stdpath('data')` with `"~/.config/nvim/sessions/"`.
`auto_session_root_dir` should just be set to whatever path you'd actually like instead of concatenating with Neovim's standard data path, so:

```lua
require("auto-session").setup {
  log_level = "error",
  auto_session_enable_last_session = false,
  auto_session_root_dir = "~/.config/nvim/sessions/",
}
```

**Comment by thepenguinthatwants** [comment]
For some reasons I am now getting this error.
```
...site/pack/packer/start/auto-session/lua/auto-session.lua:437: attempt to concatenate local 'session_file_name' (a nil value)
stack traceback:
^I...site/pack/packer/start/auto-session/lua/auto-session.lua:437: in function <...site/pack/packer/start/auto-session/lua/auto-session.lua:430>

```

**Comment by rmagatti** [comment]
Ah @thepenguinthatwants this seems to be an issue with relative paths. If you use the absolute path in that config it should work fine.

**Comment by hermitmaster** [comment]
Try this:
```
require('session-lens').setup {
    path_display={'shorten'},
}

require("auto-session").setup {
  log_level = "error",
  auto_session_enable_last_session = false,
  auto_session_root_dir = vim.fn.stdpath('config').."/sessions/",
}
```
