### ISSUE TITLE
Command for deleting sessions

### ISSUE THREAD

**Issue by jaekyeom** [rmagatti/auto-session#18]
Hi,
thanks for this amazing plugin!

Sometimes, there are broken stuffs that make into the session file and I wish there was a command for deleting the session for the current directory.
I know that I can delete them manually, but it feels non-trivial.
Maybe it should allow deleting only if the current vim instance hasn't loaded the session.

**Comment by rmagatti** [comment]
Hey, the `DeleteSession` function already existed, just hadn't been exposed yet. I put a PR up to expose it, I'll add some docs to the readme on how to use it too.

Thanks for the submission!
