### ISSUE TITLE
[BUG] Nvim version compatibility incorrect in Readme

### ISSUE THREAD

**Issue by SimonLammer** [rmagatti/auto-session#181]
**Describe the bug**
The Readme states compatibility with nvim > 0.5, but when trying to install it in nvim v0.6.0 I get the following error:

```
Error detected while processing /home/slammer/.local/share/nvim/plugged/auto-session/plugin/auto-session.vim:
line    8:
E5108: Error executing lua ...cal/share/nvim/plugged/auto-session/lua/auto-session.lua:425: attempt to call field 'nvim_create_user_command
' (a nil value)
stack traceback:
        ...cal/share/nvim/plugged/auto-session/lua/auto-session.lua:425: in main chunk
        [C]: in function 'require'
        [string "luaeval()"]:1: in main chunk
```

According to the reddit comment below, this function was introduced in 0.7.0, so the compatibility stated in the Readme seems incorrect.
https://www.reddit.com/r/neovim/comments/vmpodm/comment/ie2d61y/?utm_source=share&utm_medium=web2x&context=3

**To Reproduce**
1.  Try to install the plugin

**Expected behavior**
No error when loading the plugin.

**Baseline (please complete the following information):**
 - Result of `set sessionoptions?`: N/A
 - OS. e.g `uname -a`: Linux mint 20.3 (Kernel 5.4.0-117-generic)
 - Neovim version `nvim --version`: v0.6.1

**Comment by rmagatti** [comment]
Hey, I've got a PR open to bump the min version mentioned in the docs. That PR also has some more changes to vimdocs, which are having some issues with the doc generator. This means I'll wait a bit to try and get those solved before merging the PR.

Thanks for flagging this!

**Comment by SimonLammer** [comment]
Thank's for the quick fix, I didn't create a PR myself, because I wasn't sure enough if my research regarding the correct version requirement is correct.
Looks like you missed a spot though :)
https://github.com/rmagatti/auto-session/pull/183
