### ISSUE TITLE
[BUG] Session fails to load correctly

### ISSUE THREAD

**Issue by nickconway** [rmagatti/auto-session#194]
**Describe the bug**
Upon loading a session, specifically my `zmk-config` directory, I get an error message that states that the session might be corrupted and that autosaving has been disabled. It seems to only load the first file of the session, and then I can't save anything without a `!`.

**To Reproduce**
1. `cd zmk-config`
2. `nvim`

**Expected behavior**
Session loads without errors as normal.

**Screenshots**
![image](https://user-images.githubusercontent.com/26747205/208988363-35d13b47-a1ac-4132-94fa-6f3f85a05d78.png)
![image](https://user-images.githubusercontent.com/26747205/208988483-307b8cb9-d37e-4c36-875a-fe17f24034ff.png)

**Baseline (please complete the following information):**
 - Result of `set sessionoptions?`: `blank,buffers,curdir,folds,help,tabpages,winsize,terminal`
 - OS. e.g `uname -a`: `Linux DESKTOP 5.15.79.1-microsoft-standard-WSL2 #1 SMP Wed Nov 23 01:01:46 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`
 - Neovim version `nvim --version`: `NVIM v0.9.0-dev-522+g174335923`
 - URL to your current config (if public): https://github.com/nickconway/dotfiles

**Additional context**

**Comment by rmagatti** [comment]
Have you tried running `DeleteSession` to get rid of that session and then recreating it to see if it was just something to do with your current session file being corrupted somehow?

If that doesn't do it: it looks like it's erroring when running `filetype.lua`, which is Neovim's new lua-based filetype detection feature iirc, you could check what is erroring out there in that directory, for example opening the first file in the session manually with auto-session disabled and seeing if you get an error from that file still.

All auto-session is doing here is telling you there's an error when `source your/session/file.vim` runs. Which is something you can run yourself to reproduce as well.

**Comment by nickconway** [comment]
Installing treesitter cli fixed it, thanks for the help!
