### ISSUE TITLE
[BUG] When attempting to load via Autosession search, it cannot find directory

### ISSUE THREAD

**Issue by Gremious** [rmagatti/auto-session#195]
**Describe the bug**
When running `Autosession search` I get to pick between my 2 currently existing session. Picking ether of them, however, errors out with the following:
 
![image](https://user-images.githubusercontent.com/21365711/209446499-b4d80451-75aa-4e0b-8906-80915632e732.png)

Notably, this does **not** happen when using session-lens, so I feel like it may have potentially sneaked under the radar.

**To Reproduce**
1. Uninstall session-lens and disable the telescope plugin.
2. (Perhaps uninstall dressing as well, however, it repros for me with it too)
3. Restart vim
4. Go to a valid directory, open a few buffers, save a session
2. Run `Autosession search` and pick the new one
5. See error.

**Expected behavior**
The app restores the session smoothly.

**Baseline (please complete the following information):**
 - Result of `set sessionoptions?`: `sessionoptions=blank,buffers,curdir,folds,help,tabpages,winsize,terminal,localoptions,winpos`
 - OS. e.g `uname -a`: `MSYS_NT-10.0-22621 PC-Name 3.3.6-341.x86_64 2022-09-05 20:28 UTC x86_64 Msys` (win 11)
 - Neovim version `nvim --version`
```
NVIM v0.9.0-dev-417+g1390e97c2
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compiled by runneradmin@fv-az153-379
```

**Additional context**
Also, Autosession delete does not delete the session for me ether. Feel like that might be related.

**Comment by rmagatti** [comment]
Hey, this is an interesting one. At first glance it looks to me like it's an error with your config regarding `vim.ui.select` but I'm not super sure how exactly this would happen

**Comment by Gremious** [comment]
If I can provide and logs or further info, please do say 👍

**Comment by Mupu** [comment]
Having the same with just this setup:
```
        require("auto-session").setup({
            log_level = "error",
            auto_session_enable_last_session = true,
        })

```

**Comment by rmagatti** [comment]
Does `vim.ui.select` itself work for any of you?
To check, put this code into a lua file and then run `:luafile %`
```lua
local M = {}

function M.select()
  vim.ui.select({ "Australia", "Belarus", "Canada", "Denmark", "Egypt", "Fiji" }, {
    prompt = "Select a country",
    format_item = function(item)
      return "I like to visit " .. item
    end,
  }, function(country, idx)
    if country then
      print("You selected " .. country .. " at index " .. idx)
    else
      print("You cancelled")
    end
  end)
end

M.select()

return M
```

**Comment by Gremious** [comment]
![image](https://user-images.githubusercontent.com/21365711/217531476-95a54f9d-eac3-4df8-ab8d-7249129a1e88.png)
![image](https://user-images.githubusercontent.com/21365711/217531621-ab7f6a63-6431-4e2c-90f5-70516b64f2eb.png)

Absolutely no problems at all

The ui is there for auto-session too:

![image](https://user-images.githubusercontent.com/21365711/217531997-fdcb46e2-ffb9-451e-a531-41f109b7e127.png)

Maybe a call to `vim.fs.normalize()` is needed somewhere?

**Comment by rmagatti** [comment]
Thanks for trying that out, just wanted to rule something out. I have also just realized that the windows path handling might not be working well. I also have no real way of testing this as I'm not a windows user myself, but I'd be happy to help someone with this if they've got the time to dig in. The hypothesis is that the issue is only around the parsing of the path from the real path to the escaped path and back.

**Comment by Gremious** [comment]
I wouldn't mind trying - could you point me in the right direction? Any suggestions as to what should be checked where?

**Comment by rmagatti** [comment]
There are a couple of windows specific functions in this file you could start playing with to see what you get
https://github.com/rmagatti/auto-session/blob/04ccdac802200ecc363b251cf922b2b022bb515c/lua/auto-session-library.lua#L116

**Comment by cameronr** [comment]
@rmagatti I think this can be closed now
