### ISSUE TITLE
[BUG] Lose color on file when switch session?

### ISSUE THREAD

**Issue by tmpm697** [rmagatti/auto-session#198]
**Describe the bug**
when i switch session, color on file not appear correctly (less colors)

**To Reproduce**
the color corrects again if i open new file to edit or switch to other buffers and then switch back -- meaning if you just switch to other session and stay and keep use the buffer that restored session bring you in, that buffer is not colored correctly and it'll keep it that way unless you change buffer that somehow will trigger to re-correct the color.

**Expected behavior**
color display same as when edit file

**Screenshots**
after switched session:
![image](https://i.imgur.com/rnar0Qu.png)

use normally (expected behavior):
![image](https://i.imgur.com/J0pfTqH.png)
**Baseline (please complete the following information):**
 - Result of `set sessionoptions?`: sessionoptions=blank,buffers,curdir,folds,help,tabpages,winsize,terminal
 - OS. e.g `uname -a`: archlinux
 - Neovim version `nvim --version` nightly
 - URL to your current config (if public)

**Additional context**

**Comment by tmpm697** [comment]
after switched session, if i issue `:TSPlaygroundToggle`, it'll show empty buffer --> so treesitter not loaded after switch session, why?

**Comment by rmagatti** [comment]
This is entirely outside of auto-session's control. Something with _your_ plugins. If I were to guess, some form of lazy loading is causing treesitter to not be loaded.

**Comment by tmpm697** [comment]
it happens with other colorscheme too.

i use your treesitter config: https://github.com/rmagatti/dotfiles/blob/master/nvim/lua/rmagatti/treesitter.lua#L109 
same result.

 i saw you use packer instead of lazy.vim, can that be problem? (as in picture, i've set the priority to 999)

**Comment by rmagatti** [comment]
@tmpm697 your issue also sounds similar to an issue I had a while back. Here's a commit I made where I describe why it was happening to me. 
 https://github.com/rmagatti/dotfiles/commit/d2f47ccafc892d9e9a9b57dbaca46fe9619178a0

**Comment by tmpm697** [comment]
I sometime get unwanted and random error echo smth contain `BufReadPre` but idk that cause the issue.

I try to have a minimal steps here:
```
1. cd ~/.config/nvim/pack/default/start; git clone auto-session, plenary.nvim, telescope.nvim, telescope-project.nvim
2. vi ~/.config/nvim/init.lua
vim.cmd([[colorscheme habamax]])
require("auto-session").setup {
  log_level = "error",
  cwd_change_handling = {
    restore_upcoming_session = true, 
    pre_cwd_changed_hook = nil,
  },
}
require("telescope").load_extension("project")
4. :qa!, nvim, then use :Telescope project to create two project/session name A, B by cd to folder A and then B and create the project
5. cd ~, nvim, then use :Telescope project to switch to A, :e ./fileA # assume it contains some highlight with comment started with #
6. switch to B and do same as 5. , :e ./fileB <...>
7. :qa!, cd ~, nvim , :Telescope project select A, now you can see that there's no highlight color in comment 
```

All above basically mean, that we instead of using any kind of plugin manager, use default plugin location of nvim for plugin ~/.config/nvim/pack/default/start, git clone all plugins under here, nvim will automatically recognize them.
Then we create project A and B, under each of them has a file with comment portion highlighted as picture below.
Switch back and forth A and B and see the result.

after switch session:
![image](https://i.imgur.com/5Mpla9M.png)

normally if we nvim /path/to/file
![image](https://i.imgur.com/RDTxt8h.png)

**Comment by tmpm697** [comment]
Now i try with this minimal init.lua config:
```
nvim ~/.config/nvim/init.lua
vim.cmd([[colorscheme habamax]])
require("auto-session").setup({
	log_level = "error",
	cwd_change_handling = {
		restore_upcoming_session = true,
		pre_cwd_changed_hook = nil,
	},
})
mkdir -p ~/.config/nvim/pack/default/start
cd ~/.config/nvim/pack/default/start
git clone https://github.com/rmagatti/auto-session

cd "$(mktemp -d)" # this is folder A
nvim
:e /what/ever/lua/file.lua #edit a lua file for rich color
:qa

cd "$(mktemp -d)" # this is folder B
nvim
:e edit /what/ever/javascript/file.js #edit a javascript file for rich color
:qa

cd "$(mktemp -d)" # whatever folder
nvim
:source /home/sarc/.local/share/nvim/sessions/\%tmp\%tmp.NEXO2gs4i1\%luafile.vim  # restore session from folder A

Now  I always got this error:
Error detected while processing /home/sarc/.local/share/nvim/sessions/\%tmp\%tmp.NEXO2gs4i1\%luafile.vim:
line   53:
E108: No such variable: "SessionLoad"

And then session A still loaded and colors was correct (:colorscheme returns habamax)
```

Why with above minimal config I always get error when source session vim file? this is nvim nightly @rmagatti

**Comment by tmpm697** [comment]
I tried `withgennaro-tedesco/nvim-possession` and somehow switch session worked and colors not lose.
Sorry i can't give an PR for this, i just need something work so i can continue to work on my current workload.

**Comment by tmpm697** [comment]
I'm guessing but this issue can be auto-session tried to remove/clear current buffer before switching?

**Comment by tmpm697** [comment]
yeah this caused the issue: https://github.com/rmagatti/auto-session/blob/main/lua/auto-session-autocmds.lua#L44
if i don't set `restore_upcoming_session`, color shows correct, so the action to clear up current buffers before switch actually causes it.

**Comment by tmpm697** [comment]
can you help to clarify why you need to check for `session_dir` before restore? `mksessions` saves it to `.vim` file then we can just get the file and restore?
https://github.com/rmagatti/auto-session/blob/main/lua/auto-session.lua#L491

I don't seem to find out the code that you call to clean up buffers before switching, can you point it out?

**Comment by tmpm697** [comment]
Weird that if i use auto-session and let it save some sessions, then disable it and open nvim to manually `:source /path/to/session`, the colors display correctly.

**Comment by tmpm697** [comment]
If i enable debug mode, i got this:
```
debug:  ==== Pager mode
debug:  sessions_dir, session_file
debug:  ==== Using session DIR
debug:  ==== Session Name:
debug:  ==== is_readable
info:  Session restored from /home/user/.local/share/nvim/sessions/\%home\%user\%.local\%share\%nvim\%lazy\%auto-session\%lua.vim
debug:  Running post-restore command: Neotree action=show
```
so why these values are empty?
```
debug:  ==== Pager mode
debug:  sessions_dir, session_file
debug:  ==== Using session DIR
debug:  ==== Session Name:
debug:  ==== is_readable
```

**Comment by tmpm697** [comment]
```
tmpm697 21:51:33
what would causing %bd! not clean up all buffers with my config, what options in my config can cause this issue?
note that i'm using cokeline buffer bar

seandewar 21:52:55
tmpm697: probably a plugin

tmpm697 21:53:01
yes that's cokeline.

tmpm697 21:53:20
if i disable it, %bd! gives result same as with --clean
i'm fked with this as this is reason why auto-session not restore my color correctly.
tks for the info
```

this issue seems from https://github.com/noib3/nvim-cokeline that does not clean all buffers but keep minimal one, it probably overwrite `%bd!` behavior and causes this plugin to lose color.

if i do `%bd!` manually with `cokeline` enable, the un-deleted buffer loses color also, so it lost color before switch session with `auto-session`.

**Comment by rmagatti** [comment]
To be clear, this still has nothing to do with auto-session. It's the combination of your plugins and the order of operations of those plugins loading that seem to be causing issues for you. Auto Session does _not_ control whether _color_ or really anything else gets restored, that's controlled by vim's own session management, auto-session merely wraps that. `:h Session`

**Comment by nnako** [comment]
sorry for still posting into this already closed issue... but ...

it seems that the `filetype` somehow gets lost when switching sessions. so, when adding e.g. a `set filetype=python` within the session's vim configuration file somewhere below the respective `edit <filepath>` entry, the color is properly restored for this file type after switching to that session:

```
tabnext
edit ~/_Python/LIB__freeplane/src/freeplane.py
set filetype=python  " <-- this one is the added line
argglobal
setlocal fdm=manual
setlocal fde=0
setlocal fmr={{{,}}}
...
```

I don't know though, whether this "problem" should be fixed on the `auto-session` side or rather within some core component of `neovim`. but on the `auto-session` side, it would definitely solve the issue, for now, if the buffer's file type would be stored alongside the other information into the session's vim file.
