### ISSUE TITLE
[FEATURE] Sync between post_restore_cmds and restored buffers?

### ISSUE THREAD

**Issue by tmpm697** [rmagatti/auto-session#199]
I have this settings:
```
post_restore_cmds = { "Neotree action=show" },
```
so this will open `neo-tree` after session restored but this will cause some short/quick disruption to user as the window will stress out on screen.

I want smth that can sync to display `post_restore_cmds` nicely with restored buffers, meaning restore and display all together after `post_restore_cmds` complete instead of doing best effort to display whatever ready to display?

**Comment by rmagatti** [comment]
I'm not sure I understood the issue altogether. What does "window will stress out on screen" mean?

It's worth noting all auto-session does is call the post-restore commands after the successful run of a `:source path/to/session.vim` command.

**Comment by tmpm697** [comment]
`neo-tree` window will a bit delay to display on screen than buffers, so it's causing a flick when user switch session or just start vim with `auto-session` enabled.

**Comment by rmagatti** [comment]
Got it. Unfortunately, there's nothing I can do about that. Auto Session does not and will not, at least in the near future add code to support behaviour with other plugins directly. Doing that is a pandora's box I am not eager to open.

**Comment by rmagatti** [comment]
I am closing this as a non-issue.
