### ISSUE TITLE
Piping to nvim tries to restore a session

### ISSUE THREAD

**Issue by urandom** [rmagatti/auto-session#2]
When one pipes content to nvim like `command-output | nvim`, the auto-session plugin will attempt to restore the session, which messes with the piped content buffer. Instead, it should treat this scenario as if nvim was opened with a file, and not restore a session.

**Comment by rmagatti** [comment]
@urandom thanks for the issue submission!

I agree on how the behaviour should be. Will try to get to this soon!

**Comment by rmagatti** [comment]
So this one is a bit harder than anticipated, identifying that vim is opening in pager mode _before_ the session actually starts seems to be a bit of a head scratcher. I'll try a few more things though.

**Comment by urandom** [comment]
@rmagatti would it be possible perhaps to check whether the opened buffer is unnamed and has content? Though that would not play very nice if the pipe does not produce any content at all.

**Comment by rmagatti** [comment]
Maybe, but I think the source of the challenge here is that the plugin works by setting an autocmd on VimEnter, I can technically know if I'm opening in pager mode with `StdinReadPre` but that only happens after.

Maybe I can use something that's not VimEnter to load the session, something that gets evaluated before `StdinReadPre` gonna try something like that.

**Comment by rmagatti** [comment]
@urandom just pushed an update that should work. Apparently the `StdinReadPre` way works fine now that I did it in vimscript instead of lua. Pretty sure I was just doing something wrong before. Lmk if this doesn't fix it for you.

**Comment by urandom** [comment]
@rmagatti Seems to be working fine with the latest update
