### ISSUE TITLE
[Q] how to add further item to be saved/retrieved in/from session file

### ISSUE THREAD

**Issue by nnako** [rmagatti/auto-session#201]
**describe the question**
within a session configuration file, there are some dedicated elements stored:

- the `cwd`
- some locals (`fdm`, `fde`, `fmr`, ...)
- ...

would it be possible to somehow configure further settings to be stored and retrieved when managing the sessions? like:

- buffer-specific state of horizontal word wrap: `set wrap` or `set nowrap`
- current file type of the respective buffer: `set filetype=...`
- ...

**describe the benefit**
especially being able to store a specific file type would be of great help when dealing with "non-standard" files within a particular project setting: an example would be a `freeplane` file which has the extension ".mm" but should be handled as an "ordinary" `xml` syntax file. if the file's type is not stored within the session's configuration file, the user is forced to manually re-set the filetype after restoring the session.

**Comment by rmagatti** [comment]
For the filetype you can actually do something along the lines of `autocmd BufNewFile,BufRead *.mm setfiletype xml`.

These things can be achieved by using the `save_extra` hook, reading those values, and saving them to the `*x.vim` file.

I am however hesitant to add features that essentially enhance `sessionoptions` directly to auto-session for now at least.

**Comment by nnako** [comment]
Hi @rmagatti ,
thanks for your quick reply and for the hint regarding the usage of `setfiletype` . This will solve at least one aspect of the question.

But, anyway, is it normal behavior that every file looses the `filetype` setting when retrieved using `auto-session`? Or is it just a wrong setting and easily fixed?
