### ISSUE TITLE
Nvim-tree + symbols-outline save state

### ISSUE THREAD

**Issue by xbladesub** [rmagatti/auto-session#206]
Is it possible to save state of Nvim-tree and symbols outline as it shown on screenshot? Currently if I save the session and load it on neovim open - buffers which should contain nvim-tree and symbols outline are empty.
<img width="1512" alt="Screenshot 2023-02-25 at 1 25 48 AM" src="https://user-images.githubusercontent.com/45129790/221247772-bad1b704-1b4e-4bd9-a9bd-295a5231824a.png">

**Comment by rmagatti** [comment]
Auto Session does not integrate with any other plugin directly. That is why `hooks` are provided, so users can define their own specific integrations.

**Comment by toantk238** [comment]
@rmagatti Can you help me to exclude the specific of buffer ( like nvim-tree nav pane ) in save state ?

**Comment by tan-wei** [comment]
It is possible with using some hooks. For example, I use this to restore nvim-tree:
```lua
pre_save_cmds = {
    function()
      local status_ok, api = pcall(require, "nvim-tree.api")
      if not status_ok then
        return
      end
      api.tree.close()
    end,
  },

  post_save_cmds = {
    function()
      local status_ok, api = pcall(require, "nvim-tree.api")
      if not status_ok then
        return
      end
      api.tree.toggle { focus = false, find_file = true }
    end,
  },

  post_restore_cmds = {
    function()
      local status_ok, api = pcall(require, "nvim-tree.api")
      if not status_ok then
        return
      end
      api.tree.toggle { focus = false, find_file = true }
    end,
  },
```

**Comment by rmagatti** [comment]
Closing this as functionality is up to the user and is supported by hooks. Cheers!

**Comment by convers39** [comment]
there is another way to solve this, the hooks above will open nvim-tree even when it was not opened, this hook below will restore nvim-tree only when there is a nvim-tree buffer and the view is not visible.

```lua
local autocmd = vim.api.nvim_create_autocmd
-- restore nvim-tree with auto-session
autocmd({ "BufEnter" }, {
  pattern = "NvimTree*",
  callback = function()
    local api = require "nvim-tree.api"
    local view = require "nvim-tree.view"

    if not view.is_visible() then
      api.tree.open()
    end
  end,
})
```

**Comment by tan-wei** [comment]
@convers39 The solution you provide is much more elegant.

**Comment by TimothyCates** [comment]
For me the above auto-command only functioned if I navigated to the NvimTree_* buffer, so I modified it to check all buffers and toggle the tree when it finds one
`
vim.api.nvim_create_autocmd({ "BufEnter" }, {
	callback = function()
		local api = require("nvim-tree.api")
		local view = require("nvim-tree.view")

		for _, buf in ipairs(vim.api.nvim_list_bufs()) do
			local name = vim.api.nvim_buf_get_name(buf)
			if name:match("NvimTree*") then
				if not view.is_visible() then
					api.tree.toggle({ focus = false, find_file = true })
				end
				break
			end
		end
	end,
})

`

**Comment by NeilHanlon** [comment]
Cheers for that @HyperCrusher ! :)
