### ISSUE TITLE
[FEATURE] LSPs do not stop when switching session to another project

### ISSUE THREAD

**Issue by rmagatti** [rmagatti/auto-session#208]
**Is your feature request related to a problem? Please describe.**
When switching from a lua project to a typescript project for example, then running `LspInfo` we can see both `tsserver` and `lua_ls` active. This isn't _really_ a session concern theoretically, maybe I can implement this feature with the hooks feature, but since LSPs are built-into Neovim, it _may_ make sense to have some support within auto-session.

<img width="1110" alt="Screenshot 2023-03-01 at 10 23 37 PM" src="https://user-images.githubusercontent.com/2881382/222338836-f46a0ee5-7e4b-483c-8efd-2c1ce814b5db.png">

I worry how much this crosses into "project management" or "specific plugin" territory, but still worth considering.

**Describe the solution you'd like**
That LSPs for the previously loaded session gets shut down just like buffers from a previously loaded sessions do when switching sessions.

**Describe alternatives you've considered**
Using pre and or post hooks to explicitly call to shutdown lsp servers before a next load of a session happens.

**Additional context**
N/A

**Comment by adaviloper** [comment]
After enabling this plugin, I've noticed that LSPs also do not start after a session is loaded. I've tried using the post_restore_cmds to run `LspStart`, but the command doesn't seem to exist yet (I'm using Lazy).
If I switch to a different file, the LSPs start up, but if I switch back to the first file that was opened, the LSP is still inactive.

**Comment by rmagatti** [comment]
@adaviloper that would be something with your configuration specifically. In my config the lsp starts normally after the session is loaded.

**Comment by mixtli** [comment]
I get the same behavior FYI.   Not sure how to track it down really.

**Comment by mixtli** [comment]
Hmm.  Setting this seems to fix it:

			cwd_change_handling = {
				restore_upcoming_session = false, -- <-- THE DOCS LIE!! This is necessary!!
			},

**Comment by cameronr** [comment]
@rmagatti we could do something like the following in `RestoreSessionFile`:

```lua
        local clients = vim.lsp.get_clients()
        if #clients > 0 then vim.lsp.stop_client(clients) end
```

the only downside is that `vim.lsp.get_clients()` seems to take a small amount of time and that is noticeable when launching nvim (prolly not noticeable otherwise). we could plumb through that an autorestore is happening on startup and not do it in that case.

do you think it's worth the trouble?

**Comment by rmagatti** [comment]
> @rmagatti we could do something like the following in `RestoreSessionFile`:
> 
> ```lua
>         local clients = vim.lsp.get_clients()
>         if #clients > 0 then vim.lsp.stop_client(clients) end
> ```
> 
> the only downside is that `vim.lsp.get_clients()` seems to take a small amount of time and that is noticeable when launching nvim (prolly not noticeable otherwise). we could plumb through that an autorestore is happening on startup and not do it in that case.
> 
> do you think it's worth the trouble?

It might be worthwhile having something like this behind a default `false` config to start.
And yes, we'd need to exempt startup auto-restore from kicking off lsp calls.

Something that comes to mind is that not everyone uses vim builtin lsp, which means this config would benefit from being a `boolean|function` type that executes the function the user provides instead of the builtin function (which should be vim.lsp only) to interact with the LSP.

**Comment by cameronr** [comment]
If you want to stop previous language servers when restoring another session add `lsp_stop_on_restore = false,` to your `auto-session` config.
