### ISSUE TITLE
Show error after quitting neovim

### ISSUE THREAD

**Issue by vpeopleonatank** [rmagatti/auto-session#21]
Reproduce: Open neovim, then open file to get session saved, quit neovim then error text on terminal is shown `Client 2 quit with exit code 2 and signal 0`. Error disappear when I remove it from package manager (packer.nvim). This error appear when I fork new neovim config (Lunarvim) and install auto-session, my previous neovim config works with auto-session normally.

https://user-images.githubusercontent.com/30976876/117525029-a166a980-afea-11eb-9f7a-65fbd22b49ca.mp4

**Comment by vpeopleonatank** [comment]
I 'm back to my old config, everything work normally.

**Comment by rmagatti** [comment]
Hm yeah I've seen this once or twice, not quite sure what it is yet but haven't really dug into it much. I can if this comes up again.

Cheers!
