### ISSUE TITLE
[BUG] auto_save_enabled not working well

### ISSUE THREAD

**Issue by Saafo** [rmagatti/auto-session#215]
**Describe the bug**
`auto-session`'s `auto_save_enabled` can't remember the buffers I opened.

**To Reproduce**
1. Open a buffer in nvim
2. Do some changes
3. Quit nvim using `:wq`, or save the buffer, then `:q`
4. Open nvim again, the buffers do not restore (the buffers expected to be restored even do not exist in the saving file)
5. If exec `:SaveSession` before step 3, then restart nvim, the buffers restore as expected.

**Expected behavior**
buffers should be restored in step 4

**Baseline (please complete the following information):**
 - Result of `set sessionoptions?`:
   - `sessionoptions=curdir,help,tabpages,winsize`
 - OS. e.g `uname -a`:
   - `Darwin SaafosM1Pro 22.3.0 Darwin Kernel Version 22.3.0: Mon Jan 30 20:38:37 PST 2023; root:xnu-8792.81.3~2/RELEASE_ARM64_T6000 arm64`
 - Neovim version `nvim --version`
   - NVIM v0.9.0, Build type: Release, LuaJIT 2.1.0-beta3
 - URL to your current config (if public)
   - https://github.com/Saafo/nvimdots

**Additional context**

**Comment by Saafo** [comment]
I exec the following `sessionoptions` setup during nvim start, but the problem still exist.

```
vim.o.sessionoptions="blank,buffers,curdir,folds,help,tabpages,winsize,winpos,terminal,localoptions"
```

**Comment by rmagatti** [comment]
This is probably the result of `sessionoptions=curdir,help,tabpages,winsize`. I don't see the line you mentioned above in your config. With a sessionoptions like the one you pasted as the result of `set sessionoptions?` buffers won't be saved in the session file.

**Comment by Saafo** [comment]
Oh It works after I update my config to 0.9 branch. Maybe there's some config error yesterday, but whatever it works now! Thanks!
