### ISSUE TITLE
[BUG] Error due to unavailability of telescope?

### ISSUE THREAD

**Issue by SanchayanMaity** [rmagatti/auto-session#216]
**Describe the bug**

I do not use Telescope and currently see an error being thrown because of

```
Error detected while processing /home/core/dotfiles/nvim/.config/nvim/after/plugin/auto-session.lua:
E5113: Error while calling lua chunk: ...t/auto-session/lua/auto-session/session-lens/actions.lua:1: module 'telescope.actions.state' not found:
        no field package.preload['telescope.actions.state']
        no file './telescope/actions/state.lua'
        no file '/home/core/GitSources/neovim/.deps/usr/share/luajit-2.1.0-beta3/telescope/actions/state.lua'
        no file '/usr/local/share/lua/5.1/telescope/actions/state.lua'
        no file '/usr/local/share/lua/5.1/telescope/actions/state/init.lua'
        no file '/home/core/GitSources/neovim/.deps/usr/share/lua/5.1/telescope/actions/state.lua'
        no file '/home/core/GitSources/neovim/.deps/usr/share/lua/5.1/telescope/actions/state/init.lua'
        no file './telescope/actions/state.so'
        no file '/usr/local/lib/lua/5.1/telescope/actions/state.so'
        no file '/home/core/GitSources/neovim/.deps/usr/lib/lua/5.1/telescope/actions/state.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
        no file './telescope.so'
        no file '/usr/local/lib/lua/5.1/telescope.so'
        no file '/home/core/GitSources/neovim/.deps/usr/lib/lua/5.1/telescope.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
        [C]: in function 'require'
        ...t/auto-session/lua/auto-session/session-lens/actions.lua:1: in main chunk
        [C]: in function 'require'
        ...tart/auto-session/lua/auto-session/session-lens/init.lua:2: in main chunk
        [C]: in function 'require'
        ...e/pack/paqs/start/auto-session/lua/auto-session/init.lua:3: in main chunk
        [C]: in function 'require'
        ...dotfiles/nvim/.config/nvim/after/plugin/auto-session.lua:13: in main chunk
```

**To Reproduce**

Just open neovim in a directory for which session exists, auto-session will try to restore an existing session for the current cwd and then throws the above error.

**Expected behavior**

No error without telescope.

**Screenshots**

**Baseline (please complete the following information):**
 - Result of `set sessionoptions?`: `buffers,curdir,tabpages,winsize`
 - OS. e.g `uname -a`: `Linux core-endeavour 6.2.12-arch1-1 #1 SMP PREEMPT_DYNAMIC Thu, 20 Apr 2023 16:11:55 +0000 x86_64 GNU/Linux`
 - Neovim version `nvim --version`: `NVIM v0.10.0-dev-188+g9f0762f1f`
 - URL to your current config (if public)

**Additional context**

Is telescope mandatory now?.

**Comment by knpwrs** [comment]
I just ran into this myself. I use fzf.lua and after my latest sync I had to remove auto-session.

**Comment by 3rd** [comment]
temporary fix:
```lua
{
      "rmagatti/auto-session",
      commit = "63984ed9c0fb7eae61eb1c2982bc1147e202d23e",
      -- ...
}
```

**Comment by rmagatti** [comment]
Ah, the idea was that it should work without telescope but I apparently forgot to handle a few cases. I'll drop a PR to fix this up soon!

**Comment by nnako** [comment]
Thanks, @3rd for the workaround hint. Anyway, I had to use commit "**51b5ca4ff3200b875bb0e36416f9a6bccb0e1967**" in order for the auto-load of a standard session to be performed. with later commits, there was still no auto-load at start-up.

**Comment by rmagatti** [comment]
@nnako I don't think you're having the same issue as everyone else in this thread?

For everyone else, mind testing the branch of the PR linked above to see if this fixes your issue? 😊

**Comment by 3rd** [comment]
@rmagatti works great for me! thanks for the fix :tada:

**Comment by nnako** [comment]
Hi, indeed, the fix seems to fix the error connected with the telescope availability. But, unfortunately now, `auto-session` does not load any session at startup. the screen stays empty as if no session file was present within the respective folder. And further, when trying to exit `nvim` from this empty screen, I am prompted to confirm leaving `nvim`, which is not usually the case.

**Comment by rmagatti** [comment]
@3rd are you experiencing anything similar to @nnako?

**Comment by 3rd** [comment]
@rmagatti no issues on my side, my current config for reference: https://github.com/3rd/config/blob/master/home/dotfiles/nvim/lua/modules/workflow/sessions.lua

**Comment by rmagatti** [comment]
@nnako I don't think this is related to what you're experiencing. Maybe there's something special about your config?
