### ISSUE TITLE
After merging session-lens, how to set session-lens settings via auto-session?

### ISSUE THREAD

**Issue by miguno** [rmagatti/auto-session#218]
Originally I had the following settings for session-lens:

```lua
require("session-lens").setup({
  previewer = false,
  prompt_title = "Editor Sessions",
})
```

After the recent merge of session-lens into auto-session, how do I configure these settings in auto-session?

**Comment by rmagatti** [comment]
@miguno if you follow the example in the readme for configuring session-lens it should work fine. So essentially passing the `prompt_title = "Editor Sessions"` under the `session_lens` config table in the auto-session setup function.

https://github.com/rmagatti/auto-session#-session-lens

**Comment by miguno** [comment]
Great, this works. I got confused by this comment right in front of the session-lens settings:

```lua
-- ⚠️ This will only work if Telescope.nvim is installed
```
So I thought it was only for Telescope-related settings.
