### ISSUE TITLE
[FEATURE] Make more friendly for lazy load by disabling telescope in startup

### ISSUE THREAD

**Issue by nanozuki** [rmagatti/auto-session#219]
**Is your feature request related to a problem? Please describe.**
Auto-session integration the 'session-lens' in the latest release; this will cause telescope load before auto-session. The telescope can be a lazy load plugin, but auto-session should load in Vim startup. If auto-session require telescope, the telescope will also load in vim's startup.

In my laptop, made in 2019. This is `:Lazy profile` with auto-session:

![IMAGE 2023-05-04 14:26:22](https://user-images.githubusercontent.com/4208028/236126690-b1176e01-c103-459e-9264-f7cffa8e490d.jpg)
![IMAGE 2023-05-04 14:26:25](https://user-images.githubusercontent.com/4208028/236126698-c4fb9aea-8307-4d8f-a7ec-8ffc81f66dfd.jpg)

And this is `:Lazy profile` without auto-session:

![IMAGE 2023-05-04 14:27:16](https://user-images.githubusercontent.com/4208028/236126803-4552c659-42f9-4b72-98f9-27d64a5dd0b0.jpg)

**Describe the solution you'd like**

Add an option to disable to require the telescope. Let me load the plugin when the telescope loads.

**Comment by Saafo** [comment]
Met the same problem, now my nvim startup very slow and ugly. Really need resolving this issue!

**Comment by rmagatti** [comment]
@Saafo @nanozuki mind trying the branch above? Your config for Session Lens should look something like this:
```lua
require("auto-session").setup {
  log_level = vim.log.levels.ERROR,
  auto_session_suppress_dirs = { "~/", "~/Projects", "~/Downloads", "/" },

  session_lens = {
    load_on_setup = false,
  },
}
```

The `load_on_setup` being set to false should do what you want, which is for session-lens setup to not be called when Auto Session sets up.

You then need to call `require("auto-session").setup_session_lens()` at some point before using session-lens

**Comment by Saafo** [comment]
@rmagatti Thanks for the job! Will try it tomorrow!

**Comment by nanozuki** [comment]
@rmagatti Thanks!

I found that, if someone use `lazy.nvim` to manage plugins. when execute the `require"telescope"` the telescope plugin will be loaded by `lazy.nvim` automatically. So, if we want to prevent to load 'telescope', we should remove all `require"telescope"` in top level and move these in function. Lua will cache the require, so it's ok to require one thing in many times.

I tried the branch and make a patch:

[0001-feat-move-require-telescope-in-function.patch](https://github.com/rmagatti/auto-session/files/11473865/0001-feat-move-require-telescope-in-function.patch)

After this patch, I found that the telescope not load in startup.

**Comment by rmagatti** [comment]
Ah yes, seems like I had forgotten a few spots, thanks for the patch! I have applied it and it's in the branch now!

**Comment by Saafo** [comment]
> Ah yes, seems like I had forgotten a few spots, thanks for the patch! I have applied it and it's in the branch now!

Seems it works! Now it's so fast!
<img width="424" alt="image" src="https://github.com/rmagatti/auto-session/assets/46736350/4b69ef7b-0156-4ec4-a27e-3337cf20ed51">
