### ISSUE TITLE
RestoreSession does not save and delete buffers of the previous session?

### ISSUE THREAD

**Issue by JorisDeRidder** [rmagatti/auto-session#22]
I'm experimenting with the combo auto-session / session-lens (thanks for developing these plugins!). There is something that I'm not sure if it's a bug or a feature ;-). When I use session-lens to go to session A, open some files, then use session-lens to restore session B, then all the open files of session A are still there: they are not saved and their buffers are not deleted. If I then exit and restart nvim, and restore session B then I'm seeing all the open buffers again of both sessions A and B.

Is this intended? I.e. is it intended that one has to manually close the buffers of the previous session first, before restoring another session?

**Comment by rmagatti** [comment]
Hey!

So both plugins currently don't have anything that handles this.
I've been meaning to add something in but haven't gotten around it yet.

**Comment by JorisDeRidder** [comment]
OK, thanks for your swift reply! Together with the already available Telescope integration, I think an automatic closing of the previous session before opening a new one would make this session manager the prime choice for nvim users.

**Comment by rmagatti** [comment]
Hey @JorisDeRidder I just added a feature to session-lens on this PR https://github.com/rmagatti/session-lens/pull/2 that should provide the more intuitive behaviour of buffers from previous sessions not showing up after switching. Let me know if it it doesn't work for you.

If any issues arise from the feature, let's track it in https://github.com/rmagatti/session-lens/issues/1 since it's not really an auto-session feature.

Cheers!

**Comment by wren** [comment]
@rmagatti Thanks for the great plugin!

Could this update also get added to auto-session? Every time a session is restored, I end up with an extra unnamed buffer at the very least.

**Comment by rmagatti** [comment]
hey @wren can you elaborate a bit on your workflow?

I ask because I don't get the same behaviour you're describing. Restoring a session by opening `nvim`, then calling `:buffers` to show the open buffers only shows me what was part of that session with no unnamed buffer.
