### ISSUE TITLE
[BUG] Cannot open XX for writing

### ISSUE THREAD

**Issue by Mupu** [rmagatti/auto-session#220]
**Describe the bug**
I've followed the installation instructions. When trying to save the session im getting the error message shown on the picture. "Cannot open "..." for writing. It looks as if the path contains illegal characters. 
![image](https://user-images.githubusercontent.com/2691299/236327057-82bf5106-6f55-4160-9539-893799627b3e.png)

**To Reproduce**
Im using nvim 0.9 on windows. Open any file and try to do :SessionSave

**Expected behavior**
It should save the session.

**Screenshots**

**Baseline (please complete the following information):**
 - Result of `:SessionSave?`:
 - OS. `Windows 10`:
 - Neovim version `0.9.0`

**Comment by alex-tdrn** [comment]
Just to add to this: I've been having the same issue on windows (linux works fine), since the 2.0 release (using neovim nightly on both windows and linux)
