### ISSUE TITLE
[BUG] Save Session Stopped working

### ISSUE THREAD

**Issue by AlexXi19** [rmagatti/auto-session#226]
**Describe the bug**
Save session (and consequently restoring sessions) stopped working after the two commits on May 11. Looking at the commits, seems like it has something to do with how directory names are handled. I was able to get a working autosession by manually defining the version in packer to this commit: `commit = '21033c6815f249a7839c3a85fc8a6b44d74925c9',` so it should be a change that happened after this commit. 

The error message: 

```
Error executing Lua callback: vim/_editor.lua:0: nvim_exec2(): Vim(mksession):E190: Cannot open "/Users/alexxi/.local/share/nvim/sessions//Users/alexxi/Desktop/CS/<redacted>.vim" for writing
stack traceback:
        [C]: in function 'nvim_exec2'
        vim/_editor.lua: in function 'cmd'
        ...pack/packer/start/auto-session/lua/auto-session/init.lua:583: in function <...pack/packer/start/auto-session/lua/auto-session/init.lua:574>
```

**To Reproduce**
Note: I am on macos
1. Start neovim with autosession by running `nvim`
2. Run `:SessionSave` 
3. See error message

**Expected behavior**
Nothing happens and the session is saved and is able to be restored on startup. 

**Screenshots**
Error message included above. 

**Additional context**
As always, appreciate the great work you have done and thanks for contributing to open source!

**Comment by ten3roberts** [comment]
I am also having this issue when exiting/saving session.

Seems to be caused by a double slash in the file path

The commit c9f5c6a6b52335e7f94aa0ba35b17794e976461d causes it

![Screenshot 2023-05-12 at 09 40 33](https://github.com/rmagatti/auto-session/assets/25723553/27ee1f59-7d6b-4cf2-92ad-7b02e45c5bd2)

Also on MacOS, I think Linux handles double slashes by simply deduplicating them.

**Comment by ten3roberts** [comment]
```sh
cd ~/.local/share/nvim/lazy/auto-session && git reset --hard 21033c6
```

Gets me to a working point

**Comment by augustocdias** [comment]
Auto-restore is also not working. Probably related to this. Restoring manually works though.

**Comment by tobywan** [comment]
> ```shell
> cd ~/.local/share/nvim/lazy/auto-session && git reset --hard 21033c6
> ```
> 
> Gets me to a working point

I needed to do similar, but for my packer set up is was

```
cd .local/share/nvim/site/pack/packer/start/auto-session
git fetch --unshallow
git reset --hard 21033c6
```

**Comment by rmagatti** [comment]
This is super weird because these commits worked for me before merging it. I'm on MacOS too. Anywho, the latest merge should fix this, sorry about the trouble folks

**Comment by ten3roberts** [comment]
> This is super weird because these commits worked for me before merging it. I'm on MacOS too. Anywho, the latest merge should fix this, sorry about the trouble folks

Odd, perhaps it has to do with directory depth after `~/`.

No worries, open source is all about give and take
