### ISSUE TITLE
[FEATURE] Cleanup the session files which is no longer needed

### ISSUE THREAD

**Issue by Saafo** [rmagatti/auto-session#232]
**Is your feature request related to a problem? Please describe.**
I personally use the `git worktree` as my workflow, so I create a folder, develop, commit, and delete the folder. However, since the session file is not store in the current folder, it will not be removed after the folder is been deleted.

**Describe the solution you'd like**
Provide a command to remove the session files which the corresponding folder do not exist. We can even configure to auto execute this command each time we startup nvim.

**Describe alternatives you've considered**
Store the session file at `vim.fn.getcwd() .. '/.nvim/' .. '/sessions'`, and give the ability to customize the session file name, otherwize the file path will be ugly as `~/aa/bb/cc/.nvim/sessions/aa\/bb\/cc` and each time we'll see this at startup .

**Comment by ShangjinTang** [comment]
This is also the feature I need.

**Comment by akhilman** [comment]
My temporary solution:
```lua
local function purge_sessions()
  local auto_session = require 'auto-session'
  local to_purge = {}
  for _, session in ipairs(auto_session.get_session_files()) do
    assert(session.display_name, "Session has no 'display_name' field") -- in case of API change
    if session.display_name:find('^/.*') and vim.fn.isdirectory(session.display_name) == 0 then
      table.insert(to_purge, session.display_name)
    end
  end
  for _, name in ipairs(to_purge) do
    vim.notify("Purging session " .. name, vim.log.info)
    auto_session.DeleteSessionByName(name)
  end
  if #to_purge == 0 then
    vim.notify("Nothing to purge", vim.log.info)
  end
end

vim.api.nvim_create_user_command('PurgeSessions', purge_sessions,  { desc = "Purge orphaned sessions" })
```

**Comment by rmagatti** [comment]
@akhilman implementation looks almost good. I'm not sure about using the command function `DeleteSessionByName` though. I'd probably go through the internals of that function instead but I haven't look at that code in a while to be sure.

Either way this is a great addition, I'd be happy to review a PR on this if you're still interested.
