### ISSUE TITLE
[FEATURE] `auto_session_create_enabled` should also accept a function

### ISSUE THREAD

**Issue by WieeRd** [rmagatti/auto-session#234]
**Is your feature request related to a problem? Please describe.**
Currently, specifying each directory in `auto_session_suppress_dirs` or `auto_session_allowed_dirs` is the only way to toggle auto session per directory.

**Describe the solution you'd like**
In addition to boolean values, `auto_session_create_enabled` should also accept a function that returns a boolean.  
This way, users will be able to put more logics about when to enable auto session.

**Example use case**
```lua
require("auto-session").setup({
  auto_session_create_enabled = function()
    local cmd = "git rev-parse --is-inside-work-tree"
    return vim.fn.system(cmd) == "true\n"
  end,
})
```
If said feature is implemented, this configuration will auto create sessions only when we're inside a Git repository.  
Personally, most of my sessions correspond to a project, and most of my projects have been `$ git init`ed.  
So it will automatically create sessions exactly when I want them to be created.

**Comment by cameronr** [comment]
@WieeRd is this still something you'd like?

Rather than making `auto_session_create_enabled` be able to take a function, what about having `auto_session_suppress_dirs` / `auto_session_allowed_dirs` support taking a function? if either of those are a function, then the code could just call that function rather than doing the internal directory check it does today.

**Comment by WieeRd** [comment]
@cameronr That would work just as well.
However, I think it'd be redundant to have both `suppress_dirs` and `allowed_dirs` as a function.
`allowed_dirs` as a function is functionally identical to `create_enabled` as a function,
and one can just add `not` in the return statement to implement a blacklisting function.
So I personally think just making it possible to have `create_enabled` as a function would be enough.

[`persisted.nvim`](https://github.com/olimorris/persisted.nvim) seems to support all 4 methods.
- boolean: `autosave` == `auto_session_create_enabled`
- whitelist: `allowed_dirs` == `auto_session_allowed_dirs`
- blacklist: `ignored_dirs` == `auto_session_suppress_dirs`
- function: `should_autosave` (not available in `auto-session`)

**Comment by rmagatti** [comment]
I believe we'll be better off with making `auto_session_create_enabled` take a function to start. If that proves to not be enough for how people want to customize things we can then go the route @cameronr suggested.
