### ISSUE TITLE
[BUG] `auto_session_use_git_branch` no longer works

### ISSUE THREAD

**Issue by timtyrrell** [rmagatti/auto-session#236]
**Describe the bug**
Git branches are completely ignored. I don't see any code that actually does anything with the `branch_name`, except for code that is commented out: https://github.com/rmagatti/auto-session/blob/8a7dbcd718086877c7d75d6f36615b34674cad4b/lua/auto-session/init.lua#L316-L327

Looks like this commit broke it: https://github.com/rmagatti/auto-session/commit/c3f35994908291c634923e6331fa57c028e8802b#diff-08c7fd6d133ac05bc96b4db59055f5e9627dd26eee2217b0c36881f863a35a86L285

**To Reproduce**
set `auto_session_use_git_branch =  true`

**Expected behavior**
A git branch name will be appended to the end of a session file name

**Baseline (please complete the following information):**
 - `sessionoptions=curdir,tabpages,winsize,terminal`
 - `Darwin MH7939J63T 22.5.0 Darwin Kernel Version 22.5.0: Mon Apr 24 20:52:24 PDT 2023; root:xnu-8796.121.2~5/RELEASE_ARM64_T6000 arm64`
```
NVIM v0.10.0-dev-2872+g84378c4dd-Homebrew
Build type: Release
LuaJIT 2.1.0-beta3
```
 - URL to your current config (if public)
 https://github.com/timtyrrell/dotfiles-chezmoi/blob/1a233a217fbaf7b6f646db610f0e997b83f82dac/private_dot_config/nvim/init.vim#L822-L837

**Additional context**
It is challenging to debug because of the merge strategy used with this repo

**Comment by rmagatti** [comment]
Oh no! This probably slipped into the big merge of session-lens. I'll prioritize fixing this whenever I can. Otherwise, happy to review a PR if you or someone happens to get to it before me!

**Comment by ctil** [comment]
I put up a PR to fix this: #238. I'm pretty sure that is all that is needed to restore fix the feature to work the way it did before regression. I've been able to save and load sessions just fine with the branch name included.

**Comment by rmagatti** [comment]
@timtyrrell this should be fixed after the latest merge of @ctil's PR

**Comment by timtyrrell** [comment]
Looking good now, thanks!
