### ISSUE TITLE
Session restored when commiting

### ISSUE THREAD

**Issue by R0LA1mRifcF8yAkk** [rmagatti/auto-session#24]
First off, thanks for this, I have been able to eliminate the overhead of thinking which session I should open with Startify. Silky smooth experience so far. Until now, when I've had to commit outside of vim...

If I just run `git commit` in a repo, a vim instance should open with the `COMMIT_EDITMSG` buffer. Instead the plugin restores the session for that directory.

Is there something in the readme that I failed to understand? Or is this just a side-effect that I have to live with?

**Comment by rmagatti** [comment]
@R0LA1mRifcF8yAkk 
I think I know what might be happening, can I see your setup call?
You might be explicitly setting `auto_restore_enabled` to `true`, that is currently overriding the "pager" handling behaviour, which in retrospect is not desired.

It's an easy fix but I'd like to confirm that's the case first.

**Comment by R0LA1mRifcF8yAkk** [comment]
You were right, removing the line fixed the problem but introduced another one which was in turn fixed by removing `auto_save_enabled = true`. I guess I copied the settings from the readme and expected them to be defaults. But now I've removed everything except `auto_session_root_dir`.

The second problem was restoring the `COMMIT_EDITMSG` buffer when I had aborted the commit and wanted to edit the code some more by just opening vim.

Now it works as I'd intuitively expect it to. Opening vim inside a folder restores a session; committing always opens up `COMMIT_EDITMSG`; aborting commit and returning to vim still restores the session.

Thanks!

**Comment by rmagatti** [comment]
For your second edit, you might want to delete the session file for the session that's opening the commit buffer, it's probably just saved in the session from previous saves. 

Or you can close the commit buffer then save the session so it overrides the existence of that buffer.

I'll flip the pager mode handling so it doesn't get overridden by setting those configs.

Thanks for digging!

**Comment by R0LA1mRifcF8yAkk** [comment]
Yeah nah, my first edit was correct. I've been deceived by some incidentally perfect state.

Removing the session file has little effect since the problem arises again with the next commit. Manually saving the session doesn't fit in with my workflow either.

I'll be eagerly waiting for the fix, thanks again!

**Comment by rmagatti** [comment]
@R0LA1mRifcF8yAkk mind trying out the branch on that PR to see if that fixes your issue? I'd like to confirm before I merge

**Comment by R0LA1mRifcF8yAkk** [comment]
@rmagatti Sadly it doesn't save or restore at all on that branch. Would you need some logs or something maybe?

**Comment by rmagatti** [comment]
@R0LA1mRifcF8yAkk that was my bad, I had inverted logic on it. Should work now, did some more testing on my side this time.

**Comment by R0LA1mRifcF8yAkk** [comment]
@rmagatti Awesomesauce, works perfectly now. Thank you!
