### ISSUE TITLE
[BUG] Dashes in session path turns into backslashes

### ISSUE THREAD

**Issue by Lucirukei** [rmagatti/auto-session#242]
**Describe the bug**
Having dashes (-) in the project directory name, or any other directory in the project path, breaks loading sessions with the search/picker.
The dashes gets turned into backslashes.
See screenshots for example. I have a repo called test-repo-test, but it shows up as test\repo\test, meaning I can't load it with the picker.

**To Reproduce**
1. Save a session of a project directory with dashes in the name.
2. Use the Autosession search command
3. Try to load the session with dashes, now backslashes, in the name

**Expected behavior**
See the project path as it should be, with dashes in the name rather than backslashes.
Select the project path and have it load.

**Screenshots**
![auto-session_dash-projects1](https://github.com/rmagatti/auto-session/assets/16620760/a09d799e-a213-459c-b200-f47f669ae952)
![cant-find-dir](https://github.com/rmagatti/auto-session/assets/16620760/16907275-6f3b-4bb4-a1a3-054b9dc9ccf2)

**Baseline (please complete the following information):**
 - Result of `set sessionoptions?`:
 sessionoptions=blank,buffers,curdir,folds,help,tabpages,winsize,winpos,terminal,localoptions
 - OS. e.g `uname -a`:
 Windows 10 Pro (22H2) x64
 - Neovim version `nvim --version`
 NVIM v0.9.1
 - URL to your current config (if public)
Not public. 
But I've tested with only Lazy and auto-session installed, and no other settings. Same problem.

**Comment by BugLight** [comment]
I could not reproduce on my OS X Ventura (NVIM version is 0.9.1 too). Seems to be a windows specific bug.
I can later try on my windows laptop and maybe I'll be able to fix it.

**Comment by rmagatti** [comment]
Yeah. The reality is I don't really officially support Windows with auto-session. All Windows support has been pretty much added by the community, which is amazing to see! Hopefully someone can dive into this one soon!

**Comment by cameronr** [comment]
#315 improves this case so while it's still converting dashes to backslashes, it will load the session when selected. For example, I have a directory called "dash-test" and the session file is rendered as "dash\test":

![Screenshot 2024-07-08 at 14 12 24](https://github.com/rmagatti/auto-session/assets/38429/fc6671ed-9fca-41f7-85a2-87fbe8667d13)

Selecting it does load it successfully:
![Screenshot 2024-07-08 at 14 20 14](https://github.com/rmagatti/auto-session/assets/38429/cbd2e5e0-8008-4db4-abcc-75d0782905d1)

**Comment by cameronr** [comment]
@rmagatti what about url encoding the filename of the session? Then we could use the same encoding scheme on all platforms and have it be fully reversible while only being slightly more cumbersome to look at via `ls` (which shouldn't be an issue for an end user anyway)?

**Comment by cameronr** [comment]
Actually, now that I think about it, I wonder if it's possible to make it work by just escaping the path separator character. I'll look into this a bit more.

**Comment by rmagatti** [comment]
Urlencode would be good, I do remember considering that at the time but don't quite remember why I didn't go with that. Perhaps there wasn't a good option to do that in Lua with Neovim at the time or something like that

**Comment by cameronr** [comment]
@rmagatti I think this can be closed now
