### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by darthdeus** [rmagatti/auto-session#243]
**Describe the bug**

install auto-session & nerdtree, open nerd tree, save & exit, reopen, bug happens

**To Reproduce**
1. do the above

**Expected behavior**
Session is restored

**Screenshots**

![image](https://github.com/rmagatti/auto-session/assets/123374/612d4f20-60b4-4fd2-9b4e-63e888958fd2)

**Baseline (please complete the following information):**
 - Result of `set sessionoptions?`:   sessionoptions=blank,buffers,curdir,folds,help,tabpages,winsize,terminal
 - OS. e.g `uname -a`: Linux
 - Neovim version `nvim --version`: 0.9.1
 - URL to your current config (if public) <https://github.com/darthdeus/dotfiles/tree/fd031a7930d7f0097fb8d76710c89b8afd6e74ca>

**Additional context**

If I remove nerdtree and replace it with nvim-tree.lua it works fine, though still restores an empty panel for nvimtree

**Comment by rmagatti** [comment]
Sorry, this comment still applies
https://github.com/rmagatti/auto-session/issues/105#issuecomment-1011689655
