### ISSUE TITLE
[BUG] Cannot lazy load Telescope due to auto-session

### ISSUE THREAD

**Issue by famiu** [rmagatti/auto-session#244]
**Describe the bug**
auto-session `require()`s Telescope even when Telescope is not being used by it, which makes it impossible to lazy-load Telescope when auto-session is loaded .

**To Reproduce**
Use a configuration that tries to defer the loading of Telescope.

**Expected behavior**
Telescope does not get loaded until it is used.

**Baseline (please complete the following information):**
 - Result of `set sessionoptions?`:  `sessionoptions=blank,folds,help,tabpages,winsize,winpos,terminal,localoptions`
 - OS. e.g `uname -a`: `Linux famiu 6.3.11-200.fc38.x86_64 #1 SMP PREEMPT_DYNAMIC Sun Jul  2 13:17:31 UTC 2023 x86_64 GNU/Linux`
 - Neovim version `nvim --version`:
 ```
 NVIM v0.10.0-dev-639+g06c4edf46
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Run "nvim -V1 -v" for more info
```
 - URL to your current config (if public): https://github.com/famiu/dot-nvim/blob/master/lua/plugins/editor.lua#L54-L64

**Comment by rmagatti** [comment]
Hey 👋  that was fixed a couple of commits back. You can search the readme for `load_on_setup`. It's a session-lens config, when that is false, auto-session shouldn't require telescope until you call the session_lens setup explicitly.
