### ISSUE TITLE
DeleteSession doesn't work when auto_session_use_git_branch = true

### ISSUE THREAD

**Issue by caenrique** [rmagatti/auto-session#245]
I think the issue is that [Lib.escaped_session_name_from_cwd()](https://github.com/rmagatti/auto-session/blob/7afbb149f87be279778689596c781882014f7eef/lua/auto-session/lib.lua#L129C84-L129C84) assumes the session name will be just the cwd

**Comment by hewenjin** [comment]
Same issue here.

**Comment by rmagatti** [comment]
@caenrique that sounds very plausible. I won't have time to drop in a fix this week. Happy to review a PR though! Otherwise I'll try to get to this sometime later next week
