### ISSUE TITLE
[Feature] Track current session without relying on `vim.v.this_session` in `current_session_name`

### ISSUE THREAD

**Issue by rosingrind** [rmagatti/auto-session#250]
**Describe the bug**
I'm using `auto-session` with `lualine` integration:

```lua
lualine_c = {
    { 
        function()
            return require('auto-session.lib').current_session_name()
        end
    }
}
```

It seems that after deleting a session with `SessionDelete`, current session name is not updated (re-opening `nvim` required)

**To Reproduce**
1. Create a session with `:SessionSave` and see it immediately reflected on `lualine`
2. Delete current session
3. Session name is stuck in `lualine`

**Expected behavior**
Session name should be updated

**Screenshots**

**Baseline (please complete the following information):**
 - Result of `set sessionoptions?`: sessionoptions=blank,buffers,curdir,folds,help,tabpages,winsize,winpos,terminal,localoptions
 - OS. e.g `uname -a`: Darwin Benos-MacBook-Air.local 22.6.0 Darwin Kernel Version 22.6.0: Wed Jul  5 22:22:52 PDT 2023; root:xnu-8796.141.3~6/RELEASE_ARM64_T8103 arm64
 - Neovim version `nvim --version`

NVIM v0.9.1
Build type: Release
LuaJIT 2.1.0-beta3

**Comment by rmagatti** [comment]
Hey, you are correct. This likely happens because `vim.v.this_session` is not changed when `SessionDelete` is called.

Meaning this implementation would still return the same value regardless of the session file being deleted or not:

```lua
function Lib.current_session_name()
  local fname = Lib.get_file_name(vim.v.this_session)
  local extension = Lib.get_file_extension(fname)
  local fname_without_extension = fname:gsub(extension:gsub("%.", "%%%.") .. "$", "")
  local fname_split = vim.split(fname_without_extension, "%%")
  local session_name = fname_split[#fname_split] or ""
  return session_name
end
```

**Comment by rosingrind** [comment]
So, is this an intended behavior? I've thought that this is a bug 🤔
If that's how we roll, should I somehow update `vim.v.this_session` on a post-delete callback to reach my desired behavior? May this break anything or is it safe to do?

**Comment by rmagatti** [comment]
> So, is this an intended behavior? 

Not necessarily but ultimately the current session is still the one that was previously loaded according to vim, even after a `SessionDelete` command. For another session to show up in `v.this_session` one would need to load another session. The value of `v.this_session` also doesn't seem to be modifiable so I don't think there's much auto-session can do in this case with the current implementation.

Another way to go would be to not use `this_session` at all in that function and rely on something else to track which session is currently loaded, this would work but it would also require a new implementation of the `current_session_name` function. Happy to review a PR for this, otherwise I'll eventually get to it myself :)

**Comment by rosingrind** [comment]
Much thanks for the detailed info on this topic, I think the issue may either be closed or edited as a feature request as you wish!

> rely on something else to track which session is currently loaded

Implementation of this feature request probably don't really worth it and may introduce unnecessary complications, but I'm really not you to make conclusions :) In my opinion, for a proper solution, I should forward this to main vim/nvim repos. Thank you again!

**Comment by cameronr** [comment]
It looks like `vim.v.this_session` is now modifiable as this returns `test` for me:

```viml
:lua vim.v.this_session = 'test'; print(vim.v.this_session)
```

So i think it makes sense to clear it when if the current session is deleted.
