### ISSUE TITLE
[BUG] `:set list/nolist` immediately quits nvim when `auto-session` is loaded

### ISSUE THREAD

**Issue by rosingrind** [rmagatti/auto-session#251]
**Describe the bug**
I'm loading `auto-session` as a dependency using `lazy.nvim` with disabled `lazy = false` option:

```lua
dependencies = {
    {
        "rmagatti/auto-session",
        lazy = false,
        opts = {
            log_level = "error",
            auto_session_suppress_dirs = {
                vim.env.HOME,
                vim.env.HOME.."/Desktop",
                vim.env.HOME.."/Downloads",
                "/"
            },
            auto_session_use_git_branch = true,
            auto_session_create_enabled = false,
            auto_save_enabled = true,
            auto_restore_enabled = true,
        },
        init = function()
            vim.opt.sessionoptions = "blank,buffers,curdir,folds,help,tabpages,winsize,winpos,terminal"
        end,
        config = function(_, opts)
            require("auto-session").setup(opts)

            vim.keymap.set("n", "<Leader>ss", ":SessionRestore<CR>", { silent = true })
            vim.keymap.set("n", "<Leader>sw", ":SessionSave<CR>", { silent = true })
            vim.keymap.set("n", "<Leader>sd", ":SessionDelete<CR>", { silent = true })
        end
    }
}
```

It seems that changing `list/nolist` option in nvim is not possible as nvim crashes with no message (just quits). If you permanently set `list/nolist` in a config, the changes won't be loaded even after restart (I guess, old value is stored in a session). No stderr printed out to the terminal, the return code of `echo $?` is `139`.

If I remove `rmagatti/auto-session` as a dependency, changing `list/nolist` always succeeds. The return code of `echo $?` after successfully changing this setting and quitting with `:q` is `134`.

**To Reproduce**
1. Add `rmagatti/auto-session` as a dependency and load it
2. `:set list` or `:set nolist`

**Expected behavior**
A setting successfully changes and nothing really bad happens.

**Baseline (please complete the following information):**
 - Result of `set sessionoptions?`:sessionoptions=blank,buffers,curdir,folds,help,tabpages,winsize,winpos,terminal,localoptions
 - OS. e.g `uname -a`: Darwin Benos-MacBook-Air.local 22.6.0 Darwin Kernel Version 22.6.0: Wed Jul  5 22:22:52 PDT 2023; root:xnu-8796.141.3~6/RELEASE_ARM64_T8103 arm64
 - Neovim version `nvim --version`

NVIM v0.9.1
Build type: Release
LuaJIT 2.1.0-beta3

**Additional context**
Note that `sessionoptions` does not store `options`, only `localoptions`. I don't know why, but setting `list/nolist` in an `init.lua` config does not change the situation, the old value is still grabbed on session restore.

**Comment by rmagatti** [comment]
Can't reproduce. I build Neovim from source though. This sounds like an upstream problem to me. You can try loading a session file manually with `source path/to/session.vim` then `:set list/nolist` to see if you can reproduce this.

**Comment by rosingrind** [comment]
I've tested more and I've found that it's a combination of 3 plugins which unwinds a problem with `dstein64/nvim-scrollview`. I sincerely apologize for it, thank you for your time and answer!
