### ISSUE TITLE
[BUG] Crash on running require("session-lens").search_session()

### ISSUE THREAD

**Issue by HaCk3Dq** [rmagatti/auto-session#266]
**Describe the bug**
Crash on running session list

```lua
E5108: Error executing lua .../pack/packer/start/auto-session/lua/auto-session/lib.lua:81: attempt to call field 'debug' (a nil value)
stack traceback:
        .../pack/packer/start/auto-session/lua/auto-session/lib.lua:81: in function 'validate_root_dir'
        ...pack/packer/start/auto-session/lua/auto-session/init.lua:399: in function 'get_root_dir'
        ...escope/_extensions/session-lens/session-lens-library.lua:77: in function 'gen_from_file'
        ...ion-lens/lua/telescope/_extensions/session-lens/main.lua:71: in function 'search_session'
        [string ":lua"]:1: in main chunk

```

**To Reproduce**
```lua
:lua require('session-lens').search_session()
```

**Expected behavior**
Window with sessions should pop up

**Baseline (please complete the following information):**
 - Result of `set sessionoptions?`: 
 `sessionoptions=blank,buffers,curdir,folds,help,tabpages,winsize,terminal`
 - OS. e.g `uname -a`: 
 `Linux HaCk3D 6.7.3-arch1-1 #1 SMP PREEMPT_DYNAMIC Thu, 01 Feb 2024 10:30:35 +0000 x86_64 GNU/Linux`
 - Neovim version `nvim --version`:
 ```
NVIM v0.9.5
Build type: Release
LuaJIT 2.1.1702233742
 ```
 - URL to your current config (if public):  [nvim config](https://github.com/HaCk3Dq/dotfiles/tree/master/nvim)

**Comment by HaCk3Dq** [comment]
@rmagatti any ideas?

**Comment by HaCk3Dq** [comment]
@rmagatti any progress so far?
This bug kinda ruins my workflow, as none of the sessions are saved neither can be manually saved.
If you tell me how to debug it I'll do it myself

**Comment by rmagatti** [comment]
@HaCk3Dq Have you tried calling `require("auto-session.session-lens").search_session()` instead?

**Comment by HaCk3Dq** [comment]
> @HaCk3Dq Have you tried calling `require("auto-session.session-lens").search_session()` instead?

```lua
:lua require("auto-session.session-lens").search_session()
E5108: Error executing lua ...tart/auto-session/lua/auto-session/session-lens/init.lua:51: attempt to index field 'functions' (a nil value)
stack traceback:
        ...tart/auto-session/lua/auto-session/session-lens/init.lua:51: in function 'search_session'
        [string ":lua"]:1: in main chunk
```

**Comment by HaCk3Dq** [comment]
fixed by calling just `use 'rmagatti/auto-session' ` without `session-lens`
