### ISSUE TITLE
[BUG] Picker's theme config is broken

### ISSUE THREAD

**Issue by zyriab** [rmagatti/auto-session#267]
**Describe the bug**
When I open the picker, it does not respect Telescope's highlight group.
If I do `:highlight TelescopeNormal bgui=red` it becomes red, as expected, but if I set it back to `bgui=NONE` it reverts back to the wrong `bgui` (while my other telescope windows go back to transparent).

Here's how it looks if I pass no options whatsoever to `search_session` or `session_lens.theme_conf`

<img width="613" alt="image" src="https://github.com/rmagatti/auto-session/assets/2111910/f478b27e-e429-4b09-a998-ffa4e5148460">

Some options passed to `session_lens.theme_conf` seem to work (e.g.: `border = false`) but if I pass `preview = true`, nothing happens.

Now, if I call the following, here's the result:

```lua
session_lens.search_session({
    preview = false,
})
```

<img width="844" alt="image" src="https://github.com/rmagatti/auto-session/assets/2111910/95a5b0dd-10e8-4a1a-bbdc-33cbdef1c61b">

If I pass `border = false`, only the border option is taken into account.

**Workaround**
To disable the preview, I've found a workaround:
```lua
session_lens.search_session({
    preview = { hide_on_startup = true },
})
```

**Note that it only works if I pass it to `search_session`, if I pass it to `session_lens.theme_conf` in the `setup` function, nothing happens**

Result:
<img width="668" alt="image" src="https://github.com/rmagatti/auto-session/assets/2111910/615d2bb0-c248-4c02-97fa-a8b50ca94e79">

As a reference, here's my Telescope file finder:

<img width="1658" alt="image" src="https://github.com/rmagatti/auto-session/assets/2111910/bc470c55-400c-494d-9e26-978e853cd216">

`TelescopeNormal` HL group:
<img width="342" alt="image" src="https://github.com/rmagatti/auto-session/assets/2111910/a3738b8a-0d40-4387-aec0-68afa9702a68">

**To Reproduce**
1. Set `TelescopeNormal` to `NONE`
2. Reload Neovim
3. Open the picker

**Expected behavior**
1. The picker should respect my theme (i.e.: be transparent)
2. Tweaking the options should not cause random behavior
3. If options are set in `session_lens.theme_conf` and not in `search_session`, they should be taken into account. (`border` did work, not `path_display` or `preview`).

**Config**
I use LazyNvim as a package manager, this plugin is loaded **AFTER** Telescope.

```lua
return {
    "rmagatti/auto-session",
    lazy = true,
    dependencies = { "nvim-telescope/telescope.nvim" },
    config = function()
        local auto_session = require("auto-session")
        local session_lens = require("auto-session.session-lens")
        local telescope = require("telescope")
        local lualine = require("lualine")

        ---@diagnostic disable-next-line: missing-fields
        auto_session.setup({
            -- refresh lualine so the new session name is displayed in the status bar
            post_cwd_changed_hook = lualine.refresh,
        })

        telescope.load_extension("session-lens")

        vim.keymap.set("n", "<leader>ss", function()
            session_lens.search_session({
                path_display = { "shorten" },
                preview = { hide_on_startup = true },
            })
        end)
    end,
    init = function()
        ---@url https://github.com/rmagatti/auto-session/issues/223#issuecomment-1666658887
        local autocmd = vim.api.nvim_create_autocmd

        local lazy_did_show_install_view = false

        local function auto_session_restore()
            -- important! without vim.schedule other necessary plugins might not load (eg treesitter) after restoring the session
            vim.schedule(function()
                require("auto-session").AutoRestoreSession()
            end)
        end

        autocmd("User", {
            pattern = "VeryLazy",
            callback = function()
                local lazy_view = require("lazy.view")

                if lazy_view.visible() then
                    -- if lazy view is visible do nothing with auto-session
                    lazy_did_show_install_view = true
                else
                    -- otherwise load (by require'ing) and restore session
                    auto_session_restore()
                end
            end,
        })

        autocmd("WinClosed", {
            pattern = "*",
            callback = function(ev)
                local lazy_view = require("lazy.view")

                -- if lazy view is currently visible and was shown at startup
                if lazy_view.visible() and lazy_did_show_install_view then
                    -- if the window to be closed is actually the lazy view window
                    if ev.match == tostring(lazy_view.view.win) then
                        lazy_did_show_install_view = false
                        auto_session_restore()
                    end
                end
            end,
        })
    end,
}
```

My theme config:

```lua
return {
    "projekt0n/github-nvim-theme",
    lazy = false,
    priority = 1000,
    dependencies = {
        "xiyaowong/transparent.nvim",
        opts = {
            groups = { -- table: default groups
                "Normal",
                "NormalNC",
                "Comment",
                "Constant",
                "Special",
                "Identifier",
                "Statement",
                "PreProc",
                "Type",
                "Underlined",
                "Todo",
                "String",
                "Function",
                "Conditional",
                "Repeat",
                "Operator",
                "Structure",
                "LineNr",
                "NonText",
                "SignColumn",
                "StatusLine",
                "StatusLineNC",
                "EndOfBuffer",
            },
            extra_groups = {
                "NvimTreeNormal",
                "NormalFloat",
                "NvimTreeEndOfBuffer",
                "StatusLine",
                "StatusLineNC",
                "CmpItemMenu",
                "NoiceScrollbar",
            }, -- table: additional groups that should be cleared
            exclude_groups = {
                "CursorLine",
                "CursorLineNr",
                "CursorColumn",
                "InclineNormalFloat",
                "InclineNormalFloatNC",
            }, -- table: groups you don't want to clear,
        },
    },
    config = function()
        local transparent = require("transparent")
        local theme = require("github-theme")
        local palette1 = require("github-theme.palette.github_dark_colorblind")
        local palette2 = require("github-theme.palette.github_dark")
        local colors1 = palette1.generate_spec(palette1.palette)
        local colors2 = palette2.generate_spec(palette2.palette)

        theme.setup({
            palette = {},
            groups = {
                all = {
                    CursorLine = { bg = colors1.sel1 },
                    ColorColumn = { bg = colors2.bg1 },
                    IblScope = { fg = colors1.syntax.func },
                    IblIndent = { fg = colors1.fg3 },
                },
            },
            options = {
                transparent = true,
                hide_end_of_buffer = false,
            },
        })

        transparent.clear_prefix("WhichKey")
        transparent.clear_prefix("Lazy")
        -- The tabs do not display well if transparent
        -- transparent.clear_prefix("Mason")

        vim.cmd("colorscheme github_dark_colorblind")
    end,
}
```

**Baseline (please complete the following information):**
 - Result of `set sessionoptions?`: `sessionoptions=blank,buffers,curdir,folds,help,tabpages,winsize,terminal`
 - OS. e.g `uname -a`: MacOS Sonoma 14.2.1 (i7) `Darwin hevyboi.local 23.2.0 Darwin Kernel Version 23.2.0: Wed Nov 15 21:54:10 PST 2023; root:xnu-10002.61.3~2/RELEASE_X86_64 x86_64`
 - Neovim version `nvim --version`: 0.9.5
 - URL to your current config (if public): [My Neovim config](https://github.com/zyriab/dotfiles/tree/dotfiles/nvim)

I'm currently rewriting my entire config, it's really stable and although I'm no theme/frontend-guy I'm certain that it's a bug with the implementation of the picker (only took a quick look at the code behind `search_session` but it looked a bit too complex imho, it might also be the fact that I'm super tired right now, though!).

**Additional context**
To find the relevant files in my config:

```
.
└── lua
    ├── configs <-- Big configs cut into smaller chunks
    │   ├── incline
    │   ├── lsp
    │   └── telescope
    ├── plugins <-- all my plugins
    │   ├── bible
    │   ├── dap
    │   ├── db
    │   ├── editor
    │   ├── git
    │   ├── lsp
    │   ├── ui <-- Theme is here
    │   └── utils <-- Telescope and auto-session are here
    └── utils
```
Plugins are loaded through `lua/lazy-plugins.lua`
Then they are loaded in a file that has the name of their directory, so Telescope and auto-session are loaded in `lua/plugins/utils.lua`.

**Comment by LukasPietzschmann** [comment]
> but if I pass preview = true, nothing happens.

The setting is called `previewer` not `preview`: see [here](https://github.com/rmagatti/auto-session/blob/29a8c77a0579636d5520aebd38bdbc2e6079f2f5/README.md?plain=1#L303)

Setting `previewer = true` works for me. I'll look at the highlight groups next :)

**Comment by zyriab** [comment]
Wooh my bad! Thanks, the preview removal is a success!

**Comment by LukasPietzschmann** [comment]
> If options are set in session_lens.theme_conf and not in search_session, they should be taken into account. (border did work, not path_display or preview).

Not sure if I'm understanding you correctly with regards to `path_display`. This option should not be passed in `theme_conf`, but directly in `session_lens`:
```lua
opts = {
	session_lens = {
		theme_conf = { }, -- not here
		path_display = { 'shorten' }, -- here
	},
},

```
When I call `search_session` like this:
```lua
require('auto-session.session-lens').search_session({
	path_display = { 'shorten' },
})
```
everything also works as expected.

**Comment by LukasPietzschmann** [comment]
Btw, thanks a lot for the detailed write-up! The screenshots and explanations really help :)

**Comment by LukasPietzschmann** [comment]
So, regarding the highlighting issue: I cannot figure out, why my changes should impact this at all.

I tested setting the highlight of the Normal group to green, then running `:highlight TelescopeNormal guibg=red` which turned the picker, well, red. Running `:highlight TelescopeNormal guibg=NONE` resets everything to green (as expected).

I really don't know why you're experiencing the issue with transparency.

**Comment by zyriab** [comment]
> > If options are set in session_lens.theme_conf and not in search_session, they should be taken into account. (border did work, not path_display or preview).
> 
> Not sure if I'm understanding you correctly with regards to `path_display`. This option should not be passed in `theme_conf`, but directly in `session_lens`:
> 
> ```lua
> opts = {
> 	session_lens = {
> 		theme_conf = { }, -- not here
> 		path_display = { 'shorten' }, -- here
> 	},
> },
> ```
> 
> When I call `search_session` like this:
> 
> ```lua
> require('auto-session.session-lens').search_session({
> 	path_display = { 'shorten' },
> })
> ```
> 
> everything also works as expected.

Sorry Lukas, I should not be working on my config late at night after sleeping 5h the night before.
I'll look into the issue, it must be a problem with my theme or the way everything is loaded inside LazyNvim, maybe adding an event like `VeryLazy` would fix this.

Thanks for your time and sorry for the rookie mistakes 🙃 
Also I took a look at your config and found some gems, nice! (Also pretty cool that you implemented LZip in C!).

I'll close this issue since it's not related to the plugin. Have a great night!

**Comment by LukasPietzschmann** [comment]
There's no need to say sorry! Late night config rewrites are simply irresistible :D

Thanks a lot for the positive feedback on my config and LZip!

I hope your getting more than 5 hours of sleep tonight 🌃
