### ISSUE TITLE
Incorrect shortmess if there is an error whilst loading the session

### ISSUE THREAD

**Issue by akinsho** [rmagatti/auto-session#27]
Hi 👋🏾 ,

#### Problem
I've noticed particularly whilst using this plugin that when loading a session if there is a bug in my config or some other error that disrupts startup then the session file is only partially read i.e. given it works as excommands being executed sequentially I'm guessing that if one errors the whole thing aborts.

This means that I'm often left in a situation where my session is then corrupted. This mainly manifests as an incorrect shortmess. Normally I set my shortmess to `tAoOTfFscW` but in most session files it is temporarily set to `set shortmess=aoO` then restored *after* loading all your files is completed. 

The reason why it is a particular issues is that after clicking through the error message prompts `auto-session` then starts to automatically save my session even though it didn't get restored correctly.

#### Solution
I think the simplest solution would be to turn off autosaving if restoring a session didn't finish cleanly. So that the next `BufEnter` or whatever the event is doesn't corrupt that session file with incorrect details since it never got read correctly.

It'd be nice if somehow it could recover but I don't think that's up to this plugin though since just retrying sourcing the plugin isn't likely to work if the error isn't resolved by the user.

I've posted an example from my dotfiles session
<details>

```vim
let SessionLoad = 1
let s:so_save = &g:so | let s:siso_save = &g:siso | setg so=0 siso=0 | setl so=-1 siso=-1
let v:this_session=expand("<sfile>:p")
let VM_mouse_mappings =  0 
let Hexokinase_termDisabled =  0 
let Hexokinase_optInPatterns = "full_hex,rgb,rgba,hsl,hsla,colour_names"
let VM_default_mappings =  1 
let VM_persistent_registers =  0 
let VM_live_editing =  1 
let VM_use_python =  0 
let VM_highlight_matches = "underline"
let VM_disable_syntax_in_imode =  0 
let VM_debug =  0 
let Hexokinase_executable_path = "/home/akin/.local/share/nvim/site/pack/packer/opt/vim-hexokinase/hexokinase/hexokinase"
let Hexokinase_v2 =  1 
let VM_use_first_cursor_in_line =  0 
let Hexokinase_virtualText = "■"
let VM_case_setting = ""
let VM_check_mappings =  1 
let VM_theme = "iceblue"
let Hexokinase_signIcon = "■"
let VM_reselect_first =  0 
let Hexokinase_optOutPatterns = ""
silent only
cd ~/.dotfiles
if expand('%') == '' && !&modified && line('$') <= 1 && getline(1) == ''
  let s:wipebuf = bufnr('%')
endif
set shortmess=aoO " ABORTS HERE LEAVING Wrong Shortmess
badd +878 .config/nvim/lua/as/plugins/init.lua
badd +45 .config/nvim/lua/as/dev.lua
badd +52 .config/nvim/lua/as/plugins/compe.lua
badd +47 ~/minimal.lua
badd +9 .config/nvim/lua/as/init.lua
badd +250 .config/nvim/lua/as/autocommands.lua
badd +112 .config/nvim/plugin/autocommands.vim
badd +404 ~/.dotfiles/.config/nvim/lua/as/statusline/utils.lua
badd +37 ~/.dotfiles/.config/nvim/lua/as/globals/utils.lua
argglobal
%argdel
edit ~/.dotfiles/.config/nvim/lua/as/statusline/utils.lua
argglobal
balt .config/nvim/plugin/autocommands.vim
let s:l = 404 - ((20 * winheight(0) + 20) / 41)
if s:l < 1 | let s:l = 1 | endif
keepjumps exe s:l
normal! zt
keepjumps 404
normal! 05|
if exists('s:wipebuf') && len(win_findbuf(s:wipebuf)) == 0&& getbufvar(s:wipebuf, '&buftype') isnot# 'terminal'
  silent exe 'bwipe ' . s:wipebuf
endif
unlet! s:wipebuf
set winheight=20 winwidth=20 shortmess=tAoOTfFscW
let s:sx = expand("<sfile>:p:r")."x.vim"
if filereadable(s:sx)
  exe "source " . fnameescape(s:sx)
endif
let &g:so = s:so_save | let &g:siso = s:siso_save
nohlsearch
doautoall SessionLoadPost
unlet SessionLoad
" vim: set ft=vim :
```

</details>

**Comment by rmagatti** [comment]
Hey @akinsho, there's a PR up that should do your proposed solution, would you kindly test it out before I merge?
The PR just disables auto save when the `source` command on a session errors out. That is, assuming the return from the `vim.cmd` command will in fact be an error.

And yeah recovery is tough here, since I'm only wrapping the `mksession` and `source` commands with the plugin.

**Comment by akinsho** [comment]
@rmagatti I just did a small test and `vim.cmd` will error if the underlying command errors so that should work. Thanks for the fix, I'll have a go at testing it, I just tried to break my config and despite how often it seems to happen it's harder to do intentionally to break sourcing the session 😆

**Comment by akinsho** [comment]
@rmagatti I actually just noticed a scenario where this didn't work. I'm going to investigate a bit more how that was possible since it was whilst the session was being sourced, I'm not sure why it wasn't caught be the `pcall`. I'll try and get some concrete information about what's happening.

**Comment by rmagatti** [comment]
@rmagatti 
Oh, okay, let me know what you find!
