### ISSUE TITLE
[BUG] Required fields in setup

### ISSUE THREAD

**Issue by NeilGirdhar** [rmagatti/auto-session#277]
For some reason, this is the only plugin that is giving me required field errors in NeoVim:

```
   -- Sessions.
    {
        'rmagatti/auto-session',
        config = function()
            -- luacheck: push ignore missing-fields
            require("auto-session").setup {
                auto_session_suppress_dirs = { "~/", "~/Downloads", "/"},
            }
            -- luacheck: pop
        end
    },
```
gives
```
nvim/lua/plugins/init.lua|160-162 col 43-14 warning| Missing required fields in type `defaultConf`: `log_level`, `auto_session_enable_last_session`, `auto_session_last_session_dir`, `auto_session_root_dir`, `auto_session_enabled`
```
on the `setup` function.

**Comment by NeilGirdhar** [comment]
I think there's some questions marks missing in the field specifications: https://github.com/rmagatti/auto-session/blob/29a8c77a0579636d5520aebd38bdbc2e6079f2f5/lua/auto-session/init.lua#L38

**Comment by rmagatti** [comment]
I see. I would welcome a PR to fix this!

**Comment by NeilGirdhar** [comment]
@rmagatti Awesome, thanks for doing this, but I'm still getting errors for `defaultConf` and `log_level`.

**Comment by rmagatti** [comment]
Pushed an update on #289. Hopefully that helps

**Comment by NeilGirdhar** [comment]
Woohoo!  Thanks for fixing this
