### ISSUE TITLE
[BUG] FileType autocommand prompts do not appear on session restore

### ISSUE THREAD

**Issue by benjiwolff** [rmagatti/auto-session#278]
**Describe the bug**
When restoring a session triggers a FileType autocommand that contains a prompt, the autocommand is not fully executed as the prompt is not shown. This is because `:silent source <session>` is used [here](https://github.com/rmagatti/auto-session/blob/29a8c77a0579636d5520aebd38bdbc2e6079f2f5/lua/auto-session/init.lua#L658) to restore the session instead of `:source <session>`.

**To Reproduce**
1. Create an autocommand with a prompt such as
```
vim.api.nvim_create_autocmd("FileType", {
    pattern = { "text" },
    callback = function()
        vim.ui.select({ "1", "2" }, {
            prompt = "Select target",
        }, function(selected)
            -- important code that should run on session restore
        end)
    end,
})
```
3. Create an empty .txt file
5. Restart nvim in the same directory without arguments
8. The prompt is not shown. Consequently, the subsequent code is not executed.

**Expected behavior**
Ouput generated by FileType autocommands should be visible when a session is restored. This is also the behavior when restoring a session using `nvim -S` or `:source`.

**Comment by rmagatti** [comment]
Right, the reason `silent` was used is because when sourcing a session, depending on your settings, the print from the source would make it so that `enter` needs to be pressed for the buffers to actually load. This bug seems to be an unfortunate side-effect

**Comment by benjiwolff** [comment]
How about a setting that allows a non-silent restore or using non-silent restore for the corresponding log level (error)?

**Comment by benjiwolff** [comment]
That was quick, thanks. <3
