### ISSUE TITLE
[BUG] Session lens picker is transparent by default while other telescope pickers are solid

### ISSUE THREAD

**Issue by benjiwolff** [rmagatti/auto-session#279]
**Describe the bug**
By default, the session picker seems to be transparent, making it hard to read when there is text behind it.

**To Reproduce**
1. Install telescope and auto-session with default settings. I am using lazy.nvim
```
require("lazy").setup({
    {
        'nvim-telescope/telescope.nvim',
        dependencies = { 'nvim-lua/plenary.nvim' }
    },
    {
        'rmagatti/auto-session',
        opts = {},
    }
})
```
2. Restart nvim
3. Type `:lua=require('telescope.builtin').find_files()`. This will show a picker with a solid background
![image](https://github.com/rmagatti/auto-session/assets/103897890/36ede0e3-863f-48d0-a535-c15db9d0fd26)
4. Type `:lua=require("auto-session.session-lens").search_session()`. This will show a transparent picker
![image](https://github.com/rmagatti/auto-session/assets/103897890/e171f106-fa1e-4b3c-9acc-dd857f5f65d9)

**Expected behavior**
The session picker has the same style as other telescope pickers unless configured otherwise.

**Comment by benjiwolff** [comment]
This might be related to #267.

**Comment by rmagatti** [comment]
Can't reproduce. This might be a theme thing, I'm using `kanagawa` and I'm also not setting any theme on the session picker in my config. The code for opening the session picker is here if you'd like to take a further look:
https://github.com/rmagatti/auto-session/blob/main/lua/auto-session/session-lens/init.lua#L44
