### ISSUE TITLE
[BUG] cannot restore session using `Autosession search`

### ISSUE THREAD

**Issue by swahpy** [rmagatti/auto-session#287]
**Describe the bug**
When opening nvim and trying to restore session using `Autosession search`, nothing happened, the session was not restored.

**To Reproduce**
1. Open nvim
2. Open a file
3. In command mode, enter `Autosession search` and select session number
4. Press enter, nothing happens.

**Expected behavior**
The expected session should be restored.

**Screenshots**

**Baseline (please complete the following information):**
 - Result of `set sessionoptions?`:
 sessionoptions=blank,buffers,curdir,folds,help,tabpages,winsize,winpos,terminal,localoptions
 - OS. e.g `uname -a`:
 Darwin K1F6JWK7KT 23.4.0 Darwin Kernel Version 23.4.0: Fri Mar 15 00:12:49 PDT 2024; root:xnu-10063.101.17~1/RELEASE_ARM64_T6020 arm64
 - Neovim version `nvim --version`
 NVIM v0.9.5
Build type: Release
LuaJIT 2.1.1692716794
 - URL to your current config (if public)
 https://github.com/swahpy/dotfiles/blob/main/.config/nvim/lua/plugins/auto-session.lua

**Additional context**
I can delete session using `Autosession delete`.

**Comment by rmagatti** [comment]
The `Autosession search` command is using `vim.ui.select` version of session switching (for those who don't have Telescope).
```lua
local function open_picker(files, prompt, callback)
  vim.ui.select(files, {
    prompt = prompt,
    kind = "auto-session",
    format_item = function(item)
      return item.display_name
    end,
  }, function(choice)
    if choice then
      callback(choice)
    end
  end)
end
```

The issue is that this is merely changing the `cwd`, which means the `CwdChangeHandling` feature needs to be set for session switching to happen.
```lua
local function handle_autosession_command(data)
  local files = AutoSession.get_session_files()
  if data.args:match "search" then
    open_picker(files, "Select a session:", function(choice)
      -- Change dir to selected session path, the DirChangePre and DirChange events will take care of the rest
      vim.fn.chdir(choice.display_name)
    end)
  elseif data.args:match "delete" then
    open_picker(files, "Delete a session:", function(choice)
      AutoSession.DeleteSessionByName(choice.display_name)
    end)
  end
end
```

If you're using Telescope.nvim you can just call `require("auto-session.session-lens").search_session()` which currently does more handling.

The picker callback should be able to call the same behaviour that the telescope based handlers do, this is a bug indeed 👍

**Comment by swahpy** [comment]
Hi @rmagatti, thank you for your reply. Yes I can implement the same functionality using `require("auto-session.session-lens").search_session()`. That's great!
