### ISSUE TITLE
SessionDelete command should also deactivate autosaving

### ISSUE THREAD

**Issue by akinsho** [rmagatti/auto-session#29]
Hi @rmagatti,

Sorry I'm really raising a few of these recently, thanks for being so responsive. 

One thing I've noticed with the newly added `SessionDelete` command which is a godsend since I'd been manually removing them from the session directory is that when I use `SessionDelete` it doesn't stop autosaving from happening so right after I execute the command and say quit vim or move buffer the session is resurrected. I think and don't know if this will break anything but if someone has autosave on and they delete the session that same session should not be saved again and auto save should probably be  disabled till the next time they open nvim.

WDYT?

**Comment by rmagatti** [comment]
Hey @akinsho,

Keep them coming, it just helps make the plugin better :)

And yes I think that would make sense, I had added this command to support the integration with https://github.com/rmagatti/session-lens and this particular workflow you described wasn't something I had come across.

I'll look into this very soon!

**Comment by rmagatti** [comment]
@akinsho this should do it for the workflow you described I think.

Some other improvements could be made to control maybe reenabling auto-save if a manual `SaveSession` command is triggered, but for now, this will likely do.

Cheers!
