### ISSUE TITLE
[BUG]`require("auto-session").get_session_files()` does not return sessions with names ending in 'x'.

### ISSUE THREAD

**Issue by ck961018** [rmagatti/auto-session#295]
**Describe the bug**
I attempted to save `/examples/llvm-project/libcxx` as a session, and indeed, it generated a `%home%user%examples%llvm-project%libcxx.vim` file under `/.local/share/nvim/sessions/`. 
However, when I tried to use `require("auto-session").get_root_dir()` to retrieve the sessions, I found that it was not listed.

**To Reproduce**
1. Navigate into a directory ending with 'x'
2. Save session
3. Invoke `require("auto-session").get_root_dir()`

**Expected behavior**
`require("auto-session").get_root_dir()` returns the correct result.

**Baseline (please complete the following information):**
 - `vim.o.sessionoptions="blank,buffers,curdir,folds,help,tabpages,winsize,winpos,terminal,localoptions"`
 - OS: WSL2 under Windows 11 23H2 22631.3593, ArchWSL
 - Neovim version: `v0.9.5`
 - URL to your current config: [](https://github.com/ck961018/nvim)

**Additional context**
I reviewed the source code, and it seems the issue is caused by string.find(item, "x.vim$"). 
```
function AutoSession.get_session_files()
  local files = {}
  local sessions_dir = AutoSession.get_root_dir()

  if not vim.fn.isdirectory(sessions_dir) then
    return files
  end

  local entries = vim.fn.readdir(sessions_dir, function(item)
    return vim.fn.isdirectory(item) == 0 and not string.find(item, "x.vim$")
  end)

  return vim.tbl_map(function(entry)
    return { display_name = AutoSession.format_file_name(entry), path = entry }
  end, entries)
end

```
While I'm not entirely certain about the role of the x.vim file, it seems there might be a more effective approach to implement this functionality.

**Comment by rmagatti** [comment]
Here's some context for the `x.vim` functionality.
https://github.com/rmagatti/auto-session/issues/74

**Comment by ck961018** [comment]
> Here's some context for the `x.vim` functionality. #74

This appears to require designing an algorithm to check if each file ending with .x.vim is an extra data file for a particular session file. 
However, this approach does not resolve the situation where both session `A` and session `Ax` exist simultaneously. 

Do you have any better ideas?

**Comment by cameronr** [comment]
What about:

- For each file in the sessions dir that matches *x.vim
  - check and see if there's a *.vim
    - if there isn't, assume it's a session file
    - if there is, check the x.vim file to see if the first line contains 'SessionLoad'?

or maybe more simply just check any *x.vim file to see if the first line contains 'SessionLoad'?

there's risk that that breaks if the implementation of mks changes but that risk exists in both cases (albeit it would have less impact in the first solution)

**Comment by rmagatti** [comment]
@cameronr that sounds like it could work well! That risk is acceptable as we're relying on Neovim's internal functionality 👍
