### ISSUE TITLE
[BUG] Cursor position outside buffer when opening folder with an empty session.

### ISSUE THREAD

**Issue by V4G4X** [rmagatti/auto-session#296]
**Describe the bug**
Having some trouble making [auto-sessions](https://github.com/rmagatti/auto-session) and [startup.nvim](https://github.com/startup-nvim/startup.nvim) play along.

I have a [simple config](https://github.com/v4G4X/nvim_config) where both are set up independently, there's no logic that makes them play along well.

As a result, I'm having problems when nvim auto-recovers an empty session(or a session with ONLY the startup page).  

It throws:
```
    Error executing vim.schedule lua callback: ....local/share/nvim/lazy/startup.nvim/lua/startup/init.lua:524: Cursor position outside buffer
    stack traceback:
            [C]: in function 'nvim_win_set_cursor'
            ....local/share/nvim/lazy/startup.nvim/lua/startup/init.lua:524: in function ''
            vim/_editor.lua: in function ''
            vim/_editor.lua: in function <vim/_editor.lua:0>
```
Anyone else faces this? Any fixes to make it smart enough it not try to recover sessions when:
1. The previous session was empty.
2. The previous session only had the startup screen.

**To Reproduce**
1. Install a simple startify config: `{ "startup-nvim/startup.nvim",      config = function() require "startup".setup({ theme = "startify" }) end },`
2. Open a folder. Open no files, so that the only buffer open is the startup page.
3. Exit. (Using `:q` or `ZZ`)
4. Open the same folder again.
5. See error

**Expected behavior**
It would have been better to instead open the startup page, or if not, at least something empty without an error. 

**Screenshots**
![image](https://github.com/rmagatti/auto-session/assets/34249137/e05dd512-3db4-4ed0-9c5b-80d2c5eeb135)

**Baseline (please complete the following information):**
 - Result of `set sessionoptions?`:
```
sessionoptions=blank,buffers,curdir,folds,help,tabpages,winsize,terminal
```
 - OS. e.g `uname -a`:
```
Darwin Varun-MBP.local 23.4.0 Darwin Kernel Version 23.4.0: Fri Mar 15 00:12:41 PDT 2024; root:xnu-10063.101.17~1/RELEASE_ARM64_T8103 arm64
```
 - Neovim version `nvim --version`
```
NVIM v0.10.0
Build type: Release
LuaJIT 2.1.1713484068
Run "nvim -V1 -v" for more info
```
 - URL to your current config (if public)
https://github.com/v4G4X/nvim_config

**Comment by cameronr** [comment]
Have you tried the `bypass_session_save_file_types` option? I think for Startup.nvim, the FT is just 'startup', so maybe this:

`bypass_session_save_file_types = { 'startup' }`

**Comment by V4G4X** [comment]
Thank you SO MUCH!
