### ISSUE TITLE
[BUG] Not an editor command: SessionSave in SpaceVim

### ISSUE THREAD

**Issue by rooday-doordash** [rmagatti/auto-session#302]
**Describe the bug**
Adding auto-session in SpaceVim init.toml doesn't seem to load the plugin.

**To Reproduce**
1. Add auto-session to SpaceVim init.toml.
2. Restart SpaceVim
3. Try using `:SessionSave` command

**Expected behavior**
For the command to work/the plugin to have loaded.

**Baseline (please complete the following information):**
 - Result of `set sessionoptions?`: `sessionoptions=blank,buffers,curdir,folds,help,tabpages,winsize,terminal`
 - OS. e.g `uname -a`: `Darwin KMX5QH9Q0F 23.5.0 Darwin Kernel Version 23.5.0: Wed May  1 20:17:33 PDT 2024; root:xnu-10063.121.3~5/RELEASE_ARM64_T6031 arm64`
 - Neovim version `nvim --version`: `NVIM v0.10.0`

Here's my SpaceVim init.toml:
```
[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    colorscheme = "tokyonight-night"
    colorscheme_bg = "dark"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = true
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = "arrow"
    statusline_iseparator = "arrow"
    buffer_index_type = 4
    enable_tabline_filetype_icon = true
    enable_statusline_mode = false
    project_rooter_outermost = false
    bootstrap_before = 'myspacevim#before'
    bootstrap_after = 'myspacevim#after'

# Enable autocomplete layer
[[layers]]
name = 'autocomplete'
auto_completion_return_key_behavior = "complete"
auto_completion_tab_key_behavior = "smart"

[[layers]]
name = 'shell'
default_position = 'top'
default_height = 30

[[layers]]
  name = "colorscheme"

[[layers]]
  name = "lang#kotlin"

[[custom_plugins]]
  repo = "folke/tokyonight.nvim"
  merged = 0

[[layers]]
    name = 'git'
[[layers]]
    name = 'VersionControl'

[[layers]]
    name = "denite"
[[layers]]
    name = "telescope"

[[layers]]
  name = "gtags"
  gtagslabel = "pygments"

[[custom_plugins]]
    repo = "rmagatti/auto-session"
    merged = false

[[layers]]
  name = "lsp"
```

**Comment by tan-wei** [comment]
I would frankly say that it is not the bug with the plugin itself. It is related to the distribution `SpaceVim`.

**Comment by rooday-doordash** [comment]
@tan-wei I'm sure you're right, I'm just not sure where else to get info on this (pretty new to spacevim/vim plugins in general). I've noticed that spacevim is using this startify plugin which I think has it's own session handling logic, perhaps that is causing a conflict? Are there any known issues between startify and autosession?

**Comment by rmagatti** [comment]
Yeah this isn't really auto-session related. It just looks like the plugin never loaded if `:SessionSave` is not available. I'm gonna close this issue until an actual problem with auto-session itself comes up. I don't personally use SpaceVim so this isn't something I've come across or would have the time to dig into unfortunately. 

Perhaps posting on the SpaceVim repo would shed some light?

**Comment by tan-wei** [comment]
@rooday-doordash If the plugin is loaded correctly, these commands should be enabled. For example, if you lazy load the plugin without set `events` or something else, it will cause the issue you descibed. Maybe you should ask Spacevim directly, to know how to load the plugin you add correctly.
