### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by Rydwxz** [rmagatti/auto-session#303]
**Is your feature request related to a problem? Please describe.**
I would like to automatically manage sessions when launching nvim with arguments such as `.`, or another path to a file or directory.

**Describe the solution you'd like**
The created session's name would need to depend on both cwd when launched and the arguments given.  

**Describe alternatives you've considered**
The way it works now is fine but when there's no existing session it opens to an empty buffer instead of the directory editor I get with my habitual `nvim .`. Also, it would make the automagic experience more set-and-forget so you never accidentally forget to save a session as well as opening up great ease of use in regards to multiple sessions per directory by allowing associating sessions with files.

**Additional context**
Thanks a bunch for the great plugin, this is such a sensible way to do sessions it deserves expansion!

**Comment by richardgill** [comment]
I am also a habitual `nvim .`er. 

It would be good to have an option to enable this. I suppose it should only activate for arguments which are a directory.

**Comment by cameronr** [comment]
I could see a special case for 'nvim .', where it would just use the same session as launching without the dot. in that case, would you expect to have the directory buffer open after launch or just whatever was in the session before?

For launching with other files / paths, would you want to save a different session for each file path launched or would you expect it to use the session for the directory, so restore the session and then open the requested file?

Possible concern with the first approach (new session for each file path) is proliferation of sessions and long session names so trying to understand use case a little more.

**Comment by cameronr** [comment]
More precisely, these are the options that come to mind:

args_allow_dot: boolean, special case to treat ‘nvim .’ the same as if there were no args so session is loaded/saved the same as if just 'nvim' was run

args_handling: string, with one of the following values:
none: no session processing when there are args (how it is today)
replace_session: no session load, replace the session on exit (assuming auto save is enabled)
replace_session_only_if_multiple: no session load, replace the session on exit (assuming auto save is enabled) but only if there’s more than one buffer open (requested in #316)
new_session: no session load, create a new session named with the arguments on exit (assuming autosave is enabled)

I don't know if all of those are possible or worth it but do those cover your use cases? if so, which one(s) would you use? if not, what would you add?
