### ISSUE TITLE
[BUG] Is cwd_change_handling supposed to be enabled by default?

### ISSUE THREAD

**Issue by cameronr** [rmagatti/auto-session#313]
The docs seem to say yes, cwd_change_handling is enabled by default:

![Screenshot 2024-06-27 at 14 15 08](https://github.com/rmagatti/auto-session/assets/38429/c7c1789f-cd12-4d34-8e15-292a8208f313)

But with this config:

```lua
    require('auto-session').setup({
      auto_restore_enabled = true,
      auto_save_enabled = true,

      log_level = 'debug',

      auto_session_suppress_dirs = { '~/', '~/Downloads', '~/Documents', '~/Desktop' },
    })
```

`init.lua` sets `cwd_change_handling` to `false` by default here: 

https://github.com/rmagatti/auto-session/blob/879f5b30207bd53101e1034ca91330f23746f601/lua/auto-session/init.lua#L89

But then `autocmds.lua` doesn't set up the AutoCmds if `cwd_change_handling` is false:

https://github.com/rmagatti/auto-session/blob/879f5b30207bd53101e1034ca91330f23746f601/lua/auto-session/autocmds.lua#L8-L10

And that's confirmed with the minimal config above:

![Screenshot 2024-06-27 at 14 13 29](https://github.com/rmagatti/auto-session/assets/38429/9e46a1e0-c89d-4412-8a02-917554673a94)

I can change it but I wanted to make sure I knew what the intended / desired behavior was. Thanks!

**Comment by rmagatti** [comment]
I believe it was supposed to be enabled by default, but people were running into some issues so I vaguely remember flipping that default to false. More than likely forgot to change the docs when I did that.

In summary, it should probably remain as default false and the docs should be changed
