### ISSUE TITLE
[BUG] buftypes_to_ignore not working?

### ISSUE THREAD

**Issue by cameronr** [rmagatti/auto-session#314]
Do you know if buftypes_to_ignore is functional?

I'm able to see the code in session-lens/actions.lua not close a buffer of a type i set to ignore (e.g. terminal) but that window is still replaced when the `vim.cmd` to source the session is given in `AutoSession.RestoreSession`. I ask because I'm in the process of cleaning up the code between session lens and Autosession search (and fixing that git bug) and want to reimplement that feature if it's working but I can't get it to work even in a clean branch.

thanks!

**Comment by rmagatti** [comment]
It might have been broken for a while now tbh, not sure when. The session-lens merge was a bit of a mess in an of itself 😅
