### ISSUE TITLE
[BUG] Lazy install snippet syntax error

### ISSUE THREAD

**Issue by aaharr** [rmagatti/auto-session#317]
**Describe the bug**
Seems like the lazy install snippet from the readme has an extra paren `},` on line 10 causing syntax error. Removing allows install without error.

**To Reproduce**
1. Copy lazy install into empty lua file
2. Reload
3. Lua error

**Expected behavior**
Install w/o editing snippet

**Comment by cameronr** [comment]
Good catch, thanks!
