### ISSUE TITLE
[BUG] Session being restored for Pager/  .git/COMMIT_EDITMSG file

### ISSUE THREAD

**Issue by yogeshlonkar** [rmagatti/auto-session#327]
**Describe the bug**

When commit is initiated and nvim is default editor the session is restored.

**To Reproduce**

1. Have nvim as default edit for git
2. Go to any git repository
3. Open any file with nvim and exit (creates or uses existing session)
4. Start a commit
5. The session is restored (not expected)
6. Instead of .git/COMMIT_EDITMSG file being open in buffer it switches to last edited file from session

**Expected behavior**

Session to be not restored

**Screenshots**

NA

**Baseline (please complete the following information):**
 - Result of `set sessionoptions?`:
   ```
   sessionoptions=blank,buffers,curdir,help,tabpages,winsize,terminal,resize
   ```
 - OS. e.g `uname -a`:
   ```
   Darwin 23.5.0 Darwin Kernel Version 23.5.0: Wed May  1 20:14:38 PDT 2024; root:xnu-10063.121.3~5/RELEASE_ARM64_T6020 arm64
   ```
 - Neovim version `nvim --version`
   ```
   NVIM v0.10.0
   Build type: Release
   LuaJIT 2.1.1720049189
   Run "nvim -V1 -v" for more info
   ```
 - URL to your current config (if public): Options from lazy.nvim
   ```lua
   opts = {
    log_level = 'error',
    auto_session_create_enabled = true,
    auto_session_root_dir = home .. '/.config/nvim/.sessions/',
    cwd_change_handling = {restore_upcoming_session = true},
    auto_session_suppress_dirs = {
      '~/',
      '~/git-repos',
      '~/Downloads',
      '/',
    },
   }
   ```

**Additional context**

This seems to be introduced after 24c44a8c901db111b6f3c314a126a39e95c7d50f as this version works without this error

**Comment by cameronr** [comment]
Thanks for the report. That is definitely a bit surprising and it doesn't trivially reproduce for me.

Can you do the following:

1. Can you set `log_level = 'debug'`and then add the log messages to this report?
2. When in the git commit message, can you ctrl-z to drop to the shell, run ps, and report what the git command line is showing? e.g. for me it's:
`/usr/local/bin/nvim /Users/cam/tmp/a/.git/COMMIT_EDITMSG`
3. Does adding `args_allow_single_directory = false` fix the problem? Even if it does, I'd like to understand why it would be causing this issue.

**Comment by yogeshlonkar** [comment]
1. ```
   Fri Jul 12 19:04:42 2024 | INFO auto-session INFO: Session restored from /<MY-HOME-DIR>/.config/nvim/.sessions/<SOME-DIR-MIRROR>/<DIR-NAME>.vim
   ```
2. ```
   29514 ttys005    0:00.01 /opt/homebrew/bin/nvim /<ABSOLUTE-PATH-TO-GIT-DIR>/.git/COMMIT_EDITMSG
   ```
3. Doesn't fix the problem

I think [this line](https://github.com/rmagatti/auto-session/commit/04e1db5ceb12a8648464f594368e3a562d50d564#diff-c0a9845fef194fa6666b8a620c35bcad175457e26374baae3c91cf0dd57eaec1R760) should have been
```diff
--- launch_argv = vim.fn.argv()
+++ launch_argv = next(vim.fn.argv())
```

**Comment by cameronr** [comment]
The `if not launch_argv` check is only there because `launch_argv` gets set to nil when a session is restored, so the code is supposed to continue on if there's an argument. I would expect this block to be entered and for it not to load the session but obviously it seems like that's not happening:

https://github.com/rmagatti/auto-session/blob/4b0728715e674ad9c18f1519127dcaed59f9981b/lua/auto-session/init.lua#L259-L261

Can you set `log_level = 'debug'` in the config and include all of the log lines so I can see the whole flow of what's happening? You should be able to see the full log by doing `:messages` or `:Notifications` if you have `nvim-notify`

**Comment by yogeshlonkar** [comment]
```
auto-session DEBUG: Loading session lens on setup {
  conf = {
    args_allow_files_auto_save = false,
    args_allow_single_directory = true,
    auto_restore_lazy_delay_enabled = true,
    auto_session_create_enabled = true,
    auto_session_enable_last_session = false,
    auto_session_enabled = true,
    auto_session_root_dir = "/***/.config/nvim/.sessions/",
    auto_session_suppress_dirs = { *** },
    auto_session_use_git_branch = false,
    close_unsupported_windows = true,
    cwd_change_handling = {
      restore_upcoming_session = true
    },
    log_level = "debug",
    session_lens = {
      buftypes_to_ignore = {},
      load_on_setup = true,
      session_control = {
        control_dir = "/***/.local/share/nvim/auto_session/",
        control_filename = "session_control.json"
      }
    },
    silent_restore = true
  }
}
auto-session INFO: Setting up autocmds
auto-session DEBUG: No arguments, restoring/saving enabled
auto-session DEBUG: RestoreSession {
  session_dir = "/***/test-gitlab-ci"
}
auto-session DEBUG: Using session DIR
auto-session DEBUG: get_session_file_name {
  session = "/***/test-gitlab-ci",
  upcoming_session_dir = "/***/test-gitlab-ci"
}
auto-session DEBUG: not session_name {
  session_name = "***\\%test-gitlab-ci",
  sessions_dir = "/***/test-gitlab-ci"
}
auto-session DEBUG: session name post-format {
  session_name = "***\\%test-gitlab-ci"
}
auto-session DEBUG: get_session_file_name {
  final_path = "***/.config/nvim/.sessions/***\\%test-gitlab-ci.vim",
  upcoming_session_dir = "/***/test-gitlab-ci"
}
auto-session DEBUG: { "No session name, getting session file name",
  last_loaded_session_name = "***\\%test-gitlab-ci",
  session_dir = "/***/test-gitlab-ci",
  session_file_path = "/***/.config/nvim/.sessions/***\\%test-gitlab-ci.vim"
}
auto-session DEBUG: {
  last_loaded_session_name = "***\\%test-gitlab-ci",
  last_loaded_session_namelegacy_file_path = "***/.config/nvim/.sessions/-***-test-gitlab-ci.vim",
  last_loaded_session_namesession_file_path = "/***/.config/nvim/.sessions/***\\%test-gitlab-ci.vim"
}
auto-session DEBUG: {
  path = "/***/.config/nvim/.sessions/***test-gitlab-ci.vim",
  readable = false
}
auto-session DEBUG: {
  path = "/***/.config/nvim/.sessions/-***-test-gitlab-ci.vim",
  readable = false
}
auto-session DEBUG: File not readable, not restoring session
```

**Comment by yogeshlonkar** [comment]
```
Configuration initialized
Restored unfinished commit msg
auto-session DEBUG: Loading session lens on setup {
  conf = {
    args_allow_files_auto_save = false,
    args_allow_single_directory = true,
    auto_restore_lazy_delay_enabled = true,
    auto_session_create_enabled = true,
    auto_session_enable_last_session = false,
    auto_session_enabled = true,
    auto_session_root_dir = "/***/.config/nvim/.sessions/",
    auto_session_suppress_dirs = { "~/", "~/Downloads", "/" },
    auto_session_use_git_branch = false,
    close_unsupported_windows = true,
    cwd_change_handling = {
      restore_upcoming_session = true
    },
    log_level = "debug",
    session_lens = {
      buftypes_to_ignore = {},
      load_on_setup = true,
      session_control = {
        control_dir = "/***/.local/share/nvim/auto_session/",
        control_filename = "session_control.json"
      }
    },
    silent_restore = true
  }
}
auto-session INFO: Setting up autocmds
auto-session DEBUG: No arguments, restoring/saving enabled
auto-session DEBUG: RestoreSession {
  session_dir = "/***/test-gitlab-ci"
}
auto-session DEBUG: Using session DIR
auto-session DEBUG: get_session_file_name {
  session = "/***/test-gitlab-ci",
  upcoming_session_dir = "/***/test-gitlab-ci"
}
auto-session DEBUG: not session_name {
  session_name = "***\\%test-gitlab-ci",
  sessions_dir = "/***/test-gitlab-ci"
}
auto-session DEBUG: session name post-format {
  session_name = "***\\%test-gitlab-ci"
}
auto-session DEBUG: get_session_file_name {
  final_path = "/***\\%test-gitlab-ci.vim",
  upcoming_session_dir = "/***/test-gitlab-ci"
}
auto-session DEBUG: { "No session name, getting session file name",
  last_loaded_session_name = "***\\%test-gitlab-ci",
  session_dir = "/***/test-gitlab-ci",
  session_file_path = "/***\\%test-gitlab-ci.vim"
}
auto-session DEBUG: {
  last_loaded_session_name = "***\\%test-gitlab-ci",
  last_loaded_session_namelegacy_file_path = "/***-test-gitlab-ci.vim",
  last_loaded_session_namesession_file_path = "/***\\%test-gitlab-ci.vim"
}
auto-session DEBUG: {
  path = "/***%test-gitlab-ci.vim",
  readable = true
}
auto-session INFO: Session restored from /***/%test-gitlab-ci.vim
auto-session DEBUG: {
  content = '{"current":"\\/***.local%share%nvim%lazy%auto-session.vim"}'
}
auto-session DEBUG: {
  content = '{"current":"\\/***%.local%share%nvim%lazy%auto-session.vim"}',
  sessions = {
    current = "/***/.config/nvim/.sessions/***%test-gitlab-ci.vim"
  }
}
auto-session DEBUG: session control file contents {
  content = '{"current":"***%test-gitlab-ci.vim"}',
  sessions = {}
}
auto-session DEBUG: {
  RESTORED_WITH = "***%test-gitlab-ci.vim"
}
```

**Comment by yogeshlonkar** [comment]
Additional details trying to get argv values I see this
```lua
:lua print(vim.inspect(vim.fn.argv()))
{}
```
But
```lua
:lua print(vim.inspect(vim.v.argv))
{ "/opt/homebrew/bin/nvim", "--embed", "/***/test-gitlab-ci/.git/COMMIT_EDITMSG" }
```

So the issue might be at
1. My setup has issues, not sure why it causes different results for vim.fn.argv and vim.v.argv
2. vim.fn.argv always behaved this way and auto-session worked correctly in past and now it doesn't

**Comment by cameronr** [comment]
Thanks for the quick response! Interesting, `launch_argv` must be `nil` but I can't figure out why that would be the case.

If you're up to it, can you add this line to `auto-session/lua/auto-session/init.lua` on line number 786 (right after `  launch_argv = vim.fn.argv()`? You should most likely find that path in `~/.local/share/nvim/lazy`.

```lua
  launch_argv = vim.fn.argv() -- line 785
  Lib.logger.debug("auto_restore_session_at_vim_enter, launch_argv: " .. vim.inspect(launch_argv)) -- add this
```

And then can you send post the logs again?

I wonder if there's another plugin that's consuming the arguments or issuing `argdel` somewhere. Do you have other plugins running (e.g. do you know which one is generating `Restored unfinished commit msg`)? Can you see if the issue reproduces with a minimal configuration?

**Comment by cameronr** [comment]
I saw your other comment briefly and that makes me lean more towards another plugin consuming the arguments so by the time autosession calls `vim.fn.argv()` the arguments are gone. It is interesting that vim.v.argv still has the full command line so it's possible we could look at that but that would introduce another can of worms around correctly processing the arguments. Another option would be a config option to disable all argument processing for this kind of conflict.

**Comment by yogeshlonkar** [comment]
Apologies for taking your time, the issue was in my init function.

<details>
  <summary>I had this init function based on comment on #223 issue</summary>

```lua
local function init()
  local lazy_did_show_install_view = false
  local function auto_session_restore()
    -- important! without vim.schedule other necessary plugins might not load (eg treesitter) after restoring the session
    vim.schedule(function() require('auto-session').AutoRestoreSession() end)
  end
  autocmd('User', 'VeryLazy', function()
    local lazy_view = require('lazy.view')

    if lazy_view.visible() then
      -- if lazy view is visible do nothing with auto-session
      lazy_did_show_install_view = true
    else
      -- otherwise load (by require'ing) and restore session
      auto_session_restore()
    end
  end, 'handle lazy and session restore')
  autocmd('WinClosed', '*', function(ev)
    local lazy_view = require('lazy.view')

    -- if lazy view is currently visible and was shown at startup
    if lazy_view.visible() and lazy_did_show_install_view then
      -- if the window to be closed is actually the lazy view window
      if ev.match == tostring(lazy_view.view.win) then
        lazy_did_show_install_view = false
        auto_session_restore()
      end
    end
  end, 'handle lazy and session save')
end
```
</details>

To fix this I had to remove init function and add 2 more options

```lua
 {
  'rmagatti/auto-session',
  opts = {
    log_level = 'error',
    auto_save_enabled = true,
    auto_restore_enabled = true,
    auto_session_create_enabled = true,
    auto_session_root_dir = home .. '/.config/nvim/.sessions/',
    cwd_change_handling = {restore_upcoming_session = true},
    auto_session_suppress_dirs = {
      '~/',
      '~/git-repos',
      '~/Downloads',
      '/',
    },
  },
}
```

I had not followed the changes for log time so missed these fixes but somehow argv becomes problematic if handled by init function specially after 24c44a8c901db111b6f3c314a126a39e95c7d50f commit

**Comment by cameronr** [comment]
No worries, glad we got to the bottom of it and I appreciate the quick responses.

`auto_save_enabled` / `auto_save_restored` should effectively default to `true` (technically, they default to `nil`but the code checks for `nil` and returns true for both of them... i'm not quite sure why it doesn't just default them to true) so I don't believe setting them to true should be necessary.

**Comment by rmagatti** [comment]
>  i'm not quite sure why it doesn't just default them to true

It should 😅
