### ISSUE TITLE
Enhancement: DeleteSession improvements

### ISSUE THREAD

**Issue by rmagatti** [rmagatti/auto-session#33]
Currently :DeleteSession only takes a single argument (or none). Changing this (and AutoSession.DeleteSession*) to take varargs would be pretty simple. 

If  someone selects the current session for deletion the session will simply be created again at exit (this scenario is dealt with in AutoSession.DeleteSession if no arguments are passed to it). If a path is passed in it should probably check if that path is the current session and deal appropriately.

_Originally posted by @WhoIsSethDaniel in https://github.com/rmagatti/auto-session/issues/32#issuecomment-851160997_

**Comment by WhoIsSethDaniel** [comment]
PR #32 supports varargs now.

**Comment by WhoIsSethDaniel** [comment]
PR #32 supports :DeleteSession <arg> where <arg> is the current session.  It will act like :DeleteSession with no arguments, i.e. it will disable auto session management.

**Comment by rmagatti** [comment]
Closed on PR #32
