### ISSUE TITLE
[BUG] starting from commit 5454660 sessions for cwd ending on "x" will not be listed in session picker

### ISSUE THREAD

**Issue by wilriker** [rmagatti/auto-session#335]
**Describe the bug**
If a session is created for a directory tha's name ends in an `x`, e.g. `~/projects/x` this will not be listed in session-lens.

**To Reproduce**
1. create a directory ending in `x`
2. create a session for that `cwd`
3. open auto-lens
4. session will not be listed

**Expected behavior**
Session should be listed independent of directory name (or more specific if it ends in `x` or any other character).

**Additional context**
I have bisected the problem to the above mentioned commit. As part of this commit the directory where the session files are stored and the name of the session have been concatenated and the logic to exclude files named `x.vim` has been extended to any session file including its full path ending in `x.vim`. 

Also interesting is that this only happens for session-lens but command completion for `:SessionRestore` will list those sessions.

**Comment by cameronr** [comment]
Good catch. I'll get a PR out shortly.

**Comment by wilriker** [comment]
That was an easy catch as I work 99% of my time in a repo that ends in an `x` and that was "gone" after the update. ;-) Took me quite a while though to figure out _why_ it was happening. :-D

**Comment by cameronr** [comment]
Sorry you had to spend time tracking that down. If you want to test the fix, you can swap to my fork `cameronr/auto-session` (after changing the config, you'll have to update the plugin in lazy to actually pull it down)

**Comment by wilriker** [comment]
No worries, was a good excuse to fiddle with neovim. :-D

Anyways, I can confirm that your fork shows the entries ending in `x` in session-lens again. :+1:

**Comment by yetyetanotherusername** [comment]
Thanks for figuring this out, spent a few mins yesterday scratching my head until i found this issue.
