### ISSUE TITLE
[BUG] "close_unsupported_windows = true close the buffer

### ISSUE THREAD

**Issue by nanozuki** [rmagatti/auto-session#341]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**
Before close:
<img width="867" alt="image" src="https://github.com/user-attachments/assets/30bffd9f-1938-4287-881d-ef44c6b6a858">

After restore, terminal is missing:

<img width="865" alt="image" src="https://github.com/user-attachments/assets/0936bf68-a027-44e7-a2ba-8071e01f9b09">

**Baseline (please complete the following information):**
 - Result of `set sessionoptions?`:
 - OS. e.g `uname -a`:
 - Neovim version `nvim --version`
 - URL to your current config (if public)

**Additional context**

**Comment by cameronr** [comment]
Dup of #342

**Comment by cameronr** [comment]
No worries :)
