### ISSUE TITLE
[BUG] "close_unsupported_windows = true" close terminal window

### ISSUE THREAD

**Issue by nanozuki** [rmagatti/auto-session#342]
**Describe the bug**

The option `close_unsupported_windows = true` will close the terminal window, event there are "terminal" in `sessionoptions`.

**To Reproduce**
1. Open nvim
2. use `tabnew` create new tabpage
3. use `terminal` open a terminal
4. use `SessionSave` create session
5. exit and reopen nvim
6. the terminal window is missing.

**Expected behavior**
Restore the terminal window.

**Screenshots**
Before close:
<img width="867" alt="image" src="https://github.com/user-attachments/assets/30bffd9f-1938-4287-881d-ef44c6b6a858">

After restore, terminal is missing:

<img width="865" alt="image" src="https://github.com/user-attachments/assets/0936bf68-a027-44e7-a2ba-8071e01f9b09">

**Baseline:**

Minimal config to reproduce:

```lua
vim.env.LAZY_STDPATH = ".repro"
load(vim.fn.system("curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"))()
require("lazy.minit").repro({
  spec = {
    {
      "rmagatti/auto-session",
      opts = {},
    },
  },
})

vim.o.sessionoptions = "buffers,curdir,folds,help,tabpages,winsize,resize,winpos,terminal,globals"
vim.o.showtabline = 2
vim.o.background = "dark"
```

Save this file to `repro.lua`, use `nvim -u repro.lua` to open nvim with this config.

**Additional context**

Because there is a "terminal" option in `sessionoptions`, I think the terminal window shouldn't be close when this option is active.

I use this function to clean buffers before, maybe helps you:

```lua
local function clean_buffers()
  local bufs = vim.api.nvim_list_bufs()
  for _, buf in ipairs(bufs) do
    local name = vim.api.nvim_buf_get_name(buf)
    local type = vim.api.nvim_get_option_value('buftype', { buf = buf })
    if name ~= '' and type ~= '' and type ~= 'terminal' then
      vim.api.nvim_buf_delete(buf, {})
    end
  end
end
```

**Comment by cameronr** [comment]
Great catch! I'll get a fix out. thanks!
