### ISSUE TITLE
[BUG] Session restore empty buffer when in tmux

### ISSUE THREAD

**Issue by chenxin-yan** [rmagatti/auto-session#344]
**Describe the bug**

`:SessionSearch` does not work as expected in tmux, restoring a blank buffer, after enter a session. However, `:SessionRestore` works as expected in tmux.

**To Reproduce**
1. Save a session with opened buffers
2. create a tmux session
3. Use `:SessionSearch` to restore a session inside tmux
4. The session is not correctly restored with a empty buffer

**Expected behavior**
It is expected that `:SessionRestore` would restore buffers inside tmux session.

**Baseline (please complete the following information):**
 - sessionoptions=blank,buffers,curdir,folds,help,tabpages,winsize,winpos,terminal,localoptions,globals
 - macos 23.4.0
 - nvim v0.10.1
 - my [config](https://github.com/chenxin-yan/nvim/blob/main/lua/cyan/plugins/auto-session.lua)

**Comment by cameronr** [comment]
Thanks for the report! I suspect there's something else going on besides tmux. To help debug, can you add `log_level = 'debug',` to your auto-session config and then post the results of both `:SessionSearch` and `:SessionRestore`? That will really help me understand what's happening.

**Comment by chenxin-yan** [comment]
Thank you for replying!

Startup config: 
<img width="884" alt="image" src="https://github.com/user-attachments/assets/29f948ac-7549-458b-87d5-a72e5c7c8e5f">

When restoring a session using `:SessionSearch` (Buffers are not restored correctly, with a empty buffer)
![Xnip2024-08-07_19-22-20](https://github.com/user-attachments/assets/840cfe62-ab17-421e-b3b6-db95ab0ab16f)

When restoring a session using `:SessionRestore` (Session is correctly restored):
<img width="1630" alt="image" src="https://github.com/user-attachments/assets/54da0ab4-a721-4c21-a99d-d2e93e9f6e8f">

When Saving a session:
<img width="1423" alt="image" src="https://github.com/user-attachments/assets/11dedf7e-36a0-4e8e-87a4-09fd1d707670">

**Comment by cameronr** [comment]
Thanks for the quick response! It's still a bit of a mystery to me as `:SessionRestore` and `:SessionSearch` use the same function to restore the session. The only thing that's different about `:SessionSearch` is that it'll save a session for the existing directory (assuming `auto_save_enabled` is true). It does look like there's an error when `:SessionSearch` is trying to close existing windows and maybe that process is creating a blank buffer that's hiding other contents. A few more questions for you:

1. What buffers does `:ls` show in both cases? Maybe the buffers you're expecting are hidden under the blank one?

1. Before you restore the session, what windows do you have open / what does the screen look like? Maybe there's something that isn't working right right when we try to close those.
 
1. Can you share the contents of the session file (to make sure the expected buffers are in the file)? It should be at `/Users/yanchenxin/.local/share/nvim/sessions/%2FUsers%2Fyanchenxin%2Fdev%2Ffootnote%2Envim.vim`

**Comment by chenxin-yan** [comment]
I think I might have a clue on what's going on. Since I use a dashboard [(alpha.nvim)](https://github.com/goolord/alpha-nvim) on startup to restore session, when I call `:SessionSearch` through the dashboard, the dashboard pane might be saved in session, replacing the panes I saved.

 So basically, if I call `:SessionSearch` on dashboard and select the session that current working directory is in, the dashboard pane would be saved and loaded in place of the previous panes. 

I am not sure if auto-session has some options for acoomendate for a dashboard, or else I would just avoid using `:SessionSearch` on startup in a dashboard to prevent this issue from happening. Thank you so much for your response!

**Comment by cameronr** [comment]
Ah yes, since you have `auto_restore_enabled = false` but `auto_save_enabled = true`, when you start `nvim` in a directory, it's autosaving a session for that directory right before it loads it again. It probably shouldn't autosave in that case, I'll take a look at that.

All of that said, it's easy to disable autosave when the only open buffer is of a matching filetype. I also use alpha so have this in my config:

```lua
      bypass_session_save_file_types = { 'alpha' },
```

Let me know if that fixes it for you!

**Comment by chenxin-yan** [comment]
It does the trick! Thank you so much.
