### ISSUE TITLE
[BUG] [FEATURE] Session-lens Telescope mappings not working. Being able to customize them.

### ISSUE THREAD

**Issue by Frankwii** [rmagatti/auto-session#347]
None of the default mappings for the picker work for me. I suspect (probably wrongly) it's because I have set as a default option in Telescope that the initial mode for any picker should be normal, and the mappings are insert-only. On the init.lua of session-lens:

```   
    attach_mappings = function(_, map)
      telescope_actions.select_default:replace(Actions.source_session)
      map("i", "<c-d>", Actions.delete_session)
      map("i", "<c-s>", Actions.alternate_session)
      map("i", "<c-a>", Actions.alternate_session)
      return true
    end,
```

These don't work for me either when on insert mode. If set to normal mode, however, they do work:

```
    attach_mappings = function(_, map)
      telescope_actions.select_default:replace(Actions.source_session)
      map("n", "<c-d>", Actions.delete_session)
      map("n", "<c-s>", Actions.alternate_session)
      map("n", "<c-a>", Actions.alternate_session)
      return true
    end,
```

It would be nice to be able to customize mappings in order to get rid of this altogether.

**Comment by cameronr** [comment]
Thanks for the report! Being able to customize the mappings has been on the feature list for a while. I'll take a look at this.

**Comment by cameronr** [comment]
@Frankwii the config now supports mappings:

'''lua

config = function()
    require('auto-session').setup({
      -- ⚠️ This will only work if Telescope.nvim is installed
      -- The following are already the default values, no need to provide them if these are already the settings you want.
      session_lens = {
        -- If load_on_setup is false, make sure you use `:SessionSearch` to open the picker as it will initialize everything first
        load_on_setup = true,
        theme_conf = { border = true },
        previewer = false,
        mappings = {
          -- Mode can be a string or a table, e.g. {"i", "n"} for both insert and normal mode
          delete_session = { "i", "<C-D>" },
          alternate_session = { "i", "<C-S>" },
        },
      },
    })
  end
'''

**Comment by Frankwii** [comment]
Amazing! Thanks a lot!!
