### ISSUE TITLE
[BUG] 0408539 removed session_lens.previewer = false

### ISSUE THREAD

**Issue by wilriker** [rmagatti/auto-session#349]
**Describe the bug**
In the above mentioned commit the config was refactored and defaults for `session_lens` have been moved to the config defaults for `auto-session`. As part of this the default value `previewer = false` was removed. This leads to Telescope showing the previewer unless the user overwrites this explicitly with `previewer = false` when calling `setup`.

I _think_ that a missing value will fall back to Telescope's default of showing the previewer.

**To Reproduce**
1. Make sure the configuration to `auto-session` does not have a value for `session_lens.previewer` set
2. Open session-lens

**Expected behavior**
No previewer is show since `previewer = false` is listed as default on `README`.

**Comment by cameronr** [comment]
Ah shoot. I'll get that fixed.

**Comment by cameronr** [comment]
Just saw them, thanks!
