### ISSUE TITLE
Telescope extension error

### ISSUE THREAD

**Issue by eddyekofo94** [rmagatti/auto-session#35]
I keep getting this error, I don't really know what is the cause, I see it has something to do with Telescope. I really don't know how to fix it
```
Error detected while processing /Users/.../.local/share/nvim/site/pack/packer/opt/session-lens/plugin/session-lens.vim:
line    6:
E5108: Error executing lua [string "luaeval()"]:1: loop or previous error loading module 'telescope._extensions.session-lens.main'
```

**Comment by rmagatti** [comment]
Hi @eddyekofo94, this is actually an issue in [Session Lens](https://github.com/rmagatti/session-lens). You might not have called the loading of the extension there.

**Comment by eddyekofo94** [comment]
I found my problem was with packer, I had the plugin as optional like:
` 
   use {'rmagatti/session-lens', opt = true } 
`
when it should be loaded at start up like:
`    use {'rmagatti/session-lens'} `
