### ISSUE TITLE
[BUG] current_session_name incorrectly displayed if git branch has forward slash

### ISSUE THREAD

**Issue by db757** [rmagatti/auto-session#352]
**Describe the bug**
When the current git branch has a forward slash in it, i.e `bugfixes/some_feature`, `current_session_name` is truncated after the last forward slash.

**To Reproduce**
1. Switch to branch with a forward slash in it's name, for example `bugfixes/some_feature`.
2. Save the current session so that the new session name will get updated.
3. Add `require('auto-session.lib').current_session_name` to lualine, or simply run `:lua require('auto-session.lib').current_session_name()`

**Expected behavior**
Expected output is `<dirname> (branch: bugfixes/some_feature)`.
Actual output is: `some_feature)`.

**Screenshots**
On master branch (no issue):
![image](https://github.com/user-attachments/assets/2a2868ff-4941-4d57-8b16-c83959bdcf6d)
On `bugfixes/somefeature` branch:
![image](https://github.com/user-attachments/assets/a795808a-7321-47e3-851b-d615b8e3a18e)

**Baseline (please complete the following information):**
 - Result of `set sessionoptions?`: `sessionoptions=buffers,curdir,folds,help,tabpages,winsize,winpos,terminal`
 - OS. e.g `uname -a` :5.15.153.1-microsoft-standard-WSL2 (Ubuntu 24.04 LTS on WSL2 on windows 11).
 - Neovim version `nvim --version`: NVIM v0.10.1
Build type: Release
LuaJIT 2.1.1713773202
 - URL to your current config (if public)

**Additional context**
It would be nice to also

**Comment by cameronr** [comment]
Good find. I'll have a fix in a bit.
