### ISSUE TITLE
[FEATURE] Add option to configure the picker window size

### ISSUE THREAD

**Issue by rafaelnp** [rmagatti/auto-session#356]
**Is your feature request related to a problem? Please describe.**
there is at the moment, AFAIK, no option to resize the picker window

**Describe the solution you'd like**
Add the configuration option to define the picker window size (e.g. percentage of neovim window)

**Describe alternatives you've considered**
none

**Additional context**
none

**Comment by cameronr** [comment]
It's not well documented, but you can use the `theme_conf` config option to change the size of the picker. The easiest way to see the options is to look at the code:

https://github.com/nvim-telescope/telescope.nvim/blob/5972437de807c3bc101565175da66a1aa4f8707a/lua/telescope/themes.lua#L41

Adding this to your `auto-session` config sets the picker to 85% of the width and 50% of the height:

```lua
      ...
      session_lens = {
        theme_conf = {
          layout_config = {
            width = 0.8,
            height = 0.5,
          },
        },
      },
```

It also looks like there's a bug when setting it to 100% where you have to specify that slightly differently:
https://github.com/nvim-telescope/telescope.nvim/issues/2508#issuecomment-1650278179

Does that do what you want? If so, I'll add something to the readme.

**Comment by rafaelnp** [comment]
@cameronr Thanks for your suggestion and sorry for the late reply. Yes, it does work for me. 👍

**Comment by cameronr** [comment]
I'm doing a larger config overhaul so will include the docs in that.
