### ISSUE TITLE
Unable to save a session in windows

### ISSUE THREAD

**Issue by denilson020898** [rmagatti/auto-session#36]
![image](https://user-images.githubusercontent.com/24517135/121569570-2100f180-ca4b-11eb-9a54-d170c8554220.png)

It seems like escaping windows path does not work correctly.
https://github.com/rmagatti/auto-session/blob/80ddcf26eca11cf4d48a52ffec094fe5a4711f32/lua/auto-session.lua#L163

https://github.com/rmagatti/auto-session/blob/80ddcf26eca11cf4d48a52ffec094fe5a4711f32/lua/auto-session-library.lua#L129

I can see that, in linux the escape replacement is going to be 

> %home%denil%dev%rwp.vim

I wonder how you want it to be on windows. %ENV% is used to expand the env var.

https://github.com/rmagatti/auto-session/blob/80ddcf26eca11cf4d48a52ffec094fe5a4711f32/lua/auto-session-library.lua#L94-L98

We can use `vim.cmd("type NUL > "..file_path)`

I can work on this.

Thank you.

**Comment by rmagatti** [comment]
Hi @denilson020898, would be great if you can look into it. I look forward to a PR! Thanks!

**Comment by rmagatti** [comment]
Fixed in #38
