### ISSUE TITLE
[BUG]With `auto_create` disabled, session can't be auto-saved.

### ISSUE THREAD

**Issue by BurningLutz** [rmagatti/auto-session#376]
**Describe the bug**
With `auto_create` disabled, if I create a session manually with ":SessionSave", it is not auto-saved before exiting vim.

**To Reproduce**
1. with default config, set `auto_create` to false.
2. Open an arbitrary project, and create a session with ":SessionSave".
3. Open some files and exit vim with ":qa".
4. Re-open vim and load the coresponding session.
5. The session doesn't consist with the state before exiting vim.

**Expected behavior**
The session should be auto-saved.

**Checkhealth**
```
auto-session: require("auto-session.health").check()

vim options ~
- OK vim.o.sessionoptions

Lazy.nvim settings ~
- OK Lazy.nvim support is enabled
- OK auto-session is not lazy loaded

Config ~
- OK 
  {
    auto_create = false
  }

General Info ~
- Session directory: /home/lutz/.local/share/nvim/sessions/
- Current session: 
- Current session file: 
```

**Baseline (please complete the following information):**
- Result of `set sessionoptions?`:
sessionoptions=blank,buffers,curdir,folds,help,tabpages,winsize,terminal,localoptions                                                                                       
- OS. e.g `uname -a`:
Linux Lutz-Gram 5.15.153.1-microsoft-standard-WSL2 #1 SMP Fri Mar 29 23:14:13 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
- Neovim version `nvim --version`
NVIM v0.10.1
Build type: Release
LuaJIT 2.1.1713773202
Run "nvim -V1 -v" for more info
- URL to your current config (if public)
Just default config with `auto_create` set to false.

**Additional context**
I did some diagnostics, it may be related to the `AutoSaveSession` function not getting the current session name.

**Comment by cameronr** [comment]
Thanks for the report. There must be something else going as a config with just `auto_create = true` works as expected for me. To test, can you do the following:

1. add `log_level = 'debug'` to your config
2. to simulate autosaving, press `:` to enter command mode then paste in `=require('auto-session').AutoSaveSession()` and hit enter. That will run the Lua function that gets called when nvim is exiting.
3. Post the debug logs into this issue. They should be available either under `:messages` or `:Notifications` depending on if you have `nvim-notify` installed or not

**Comment by BurningLutz** [comment]
@cameronr Sure! Here is the debug messages:
```
auto-session DEBUG: launch_argv is nil, saving/restoring enabled
auto-session DEBUG: find_matching_directory {
  dirToFind = "/home/lutz/Documents/dotfiles",
  dirsToCheck = {}
}
auto-session DEBUG: suppress_session didn't find a match, returning false
auto-session DEBUG: bypass_save_by_filetype: false
auto-session DEBUG: auto_save_conditions_met: returning true
auto-session DEBUG: get_session_file_name no session_name, using cwd: /home/lutz/Documents/dotfiles
auto-session DEBUG: Create not enabled and no existing session, not creating session
false
```

**Comment by cameronr** [comment]
That's actually normal: when no session name is provided, it derives one automatically from the cwd. From those logs, it looks like it can't find the session created by `:SessionSave` so it decides not to save one. That is the correct behavior when `auto_create = false` so the question now is if `:SessionSave` is working as expected.

Can you do the following (all with debug logging on):

1. start nvim
2. open some files
3. run `:SessionSave`
4. run `:=require('auto-session').AutoSaveSession()`
5. post the log results

thanks!

**Comment by BurningLutz** [comment]
@cameronr The new debug messages:
```
auto-session DEBUG: SaveSessionToDir start { "/home/lutz/.local/share/nvim/sessions/", "" }
auto-session DEBUG: SaveSessionToDir validated session_dir:  /home/lutz/.local/share/nvim/sessions/
auto-session DEBUG: get_session_file_name no session_name, using cwd: /home/lutz/tmp/proj
auto-session DEBUG: SaveSessionToDir escaped session name: %2Fhome%2Flutz%2Ftmp%2Fproj.vim
auto-session DEBUG: SaveSessionToDir writing session to: /home/lutz/.local/share/nvim/sessions/%2Fhome%2Flutz%2Ftmp%2Fproj.vim
auto-session DEBUG: Saved session: /home/lutz/tmp/proj.vim
Saved session: /home/lutz/tmp/proj
auto-session DEBUG: enabled_for_command_line_argv, launch_argv: {}                                                                                                            auto-session DEBUG: No arguments, saving/restoring enabled
auto-session DEBUG: find_matching_directory {
  dirToFind = "/home/lutz/tmp/proj",
  dirsToCheck = {}
}
auto-session DEBUG: suppress_session didn't find a match, returning false
auto-session DEBUG: bypass_save_by_filetype: false
auto-session DEBUG: auto_save_conditions_met: returning true
auto-session DEBUG: get_session_file_name no session_name, using cwd: /home/lutz/tmp/proj
auto-session DEBUG: SaveSessionToDir start { "/home/lutz/.local/share/nvim/sessions/",
  [3] = false
}
auto-session DEBUG: SaveSessionToDir validated session_dir:  /home/lutz/.local/share/nvim/sessions/
auto-session DEBUG: get_session_file_name no session_name, using cwd: /home/lutz/tmp/proj
auto-session DEBUG: SaveSessionToDir escaped session name: %2Fhome%2Flutz%2Ftmp%2Fproj.vim
auto-session DEBUG: SaveSessionToDir writing session to: /home/lutz/.local/share/nvim/sessions/%2Fhome%2Flutz%2Ftmp%2Fproj.vim
auto-session DEBUG: Saved session: /home/lutz/tmp/proj.vim
true
```
It seems that it works as expected, and I tried the steps with `:SessionSave proj`, this time the debug messages show:
```
auto-session DEBUG: SaveSessionToDir start { "/home/lutz/.local/share/nvim/sessions/", "proj" }
auto-session DEBUG: SaveSessionToDir validated session_dir:  /home/lutz/.local/share/nvim/sessions/
auto-session DEBUG: SaveSessionToDir escaped session name: proj.vim
auto-session DEBUG: SaveSessionToDir writing session to: /home/lutz/.local/share/nvim/sessions/proj.vim
auto-session DEBUG: Saved session: proj.vim
Saved session: proj
auto-session DEBUG: enabled_for_command_line_argv, launch_argv: {}                                                                                                            auto-session DEBUG: No arguments, saving/restoring enabled
auto-session DEBUG: find_matching_directory {
  dirToFind = "/home/lutz/tmp/proj",
  dirsToCheck = {}
}
auto-session DEBUG: suppress_session didn't find a match, returning false
auto-session DEBUG: bypass_save_by_filetype: false
auto-session DEBUG: auto_save_conditions_met: returning true
auto-session DEBUG: get_session_file_name no session_name, using cwd: /home/lutz/tmp/proj
auto-session DEBUG: Create not enabled and no existing session, not creating session
false
```
Seems that the auto-save is not working with a session created with manual session name. Is it expected behavior?

**Comment by cameronr** [comment]
Ah, yes, that is currently the way it works. Auto-saving / restoring only works with automatically named sessions (where the name is derived from the cwd) as that's how we know there's a session for the cwd. You can save and restore a manually named session but it won't be used for auto-saving or auto-restoring.

**Comment by BurningLutz** [comment]
I see. Thanks for your quick responses! I'm closing this now.

**Comment by kqvanity** [comment]
@cameronr 
> But it won't be used for auto-saving or auto-restoring
will named session be supported? relying on CWD keeps overriding the sessions if accidentally opened up another one in the same dir. It's worth noting in the docs as well.

**Comment by cameronr** [comment]
Currently, auto-saving and loading sessions only works for sessions where the name is derived from the CWD (with `use_git_branch` the session name will include the current git branch). You can create named sessions with `:SessionSave <sessionname>`/`:SessionRestore <sessionname>` but they won't be auto-saved or restored.

It doesn't work this way today, but I could imagine supporting auto-saving to a named session on exit (i.e. if you create/load a named session then we could write that session on exit rather than to the one derived from the cwd). 

@rmagatti thoughs on the above as a possible feature?

@kqvanity I'm curious about your use case where you're having multiple, different sessions tied to the same cwd. Can you share some details on your workflow?

**Comment by kqvanity** [comment]
> Can you share some details on your workflow

It's just that I've enabled single file support, so It overridden the whole CWD session. I'd ideally want to save sessions explicitly with a custom name/CWD, and have support for individual files there're outside of any project's session. That's the behavior I'm used coming from Vim

I'd favor support for named sessions for multiple reasons
- short custom name
- not tied to the CWD

**Comment by cameronr** [comment]
@kqvanity rather than using this issue, can you file a new feature enhancement issue with as much detail as you can about how you'd like it to work?

thanks!
