### ISSUE TITLE
[BUG] "n buffers wiped out" message pops up on every startup

### ISSUE THREAD

**Issue by MaroonedMind** [rmagatti/auto-session#379]
**Describe the bug**
For every existing session regardless of the amount of buffers opened in the project, on each startup of neovim the autosession plugin produces the following message: "2 buffers wiped out". I could not find the root cause or what exactly are these 2 buffers that get wiped out every time. It's clear that this happens for every session restoration, because when opening neovim by passing a path argument to it (which skips session restoration) or after deleting a corresponding session for the given workdir, there's no such message on startup. Immediately quitting and reopening neovim leads to the same message again.

**To Reproduce**
Unclear if there's anything specific about my setup that leads to this behavior. The only step I'm taking:
1. Open neovim without passing any path arguments. 

**Expected behavior**
There shouldn't be an identical "2 buffers wiped out" message for every single neovim run. 

**Screenshots**
<img width="294" alt="image" src="https://github.com/user-attachments/assets/d1c46d31-0da1-432d-a408-5ce669a2559d">

**Checkhealth**
```
auto-session: require("auto-session.health").check()

vim options ~
- OK vim.o.sessionoptions

Lazy.nvim settings ~
- Lazy.nvim not loaded

Config ~
- OK 
  {
    auto_create = true,
    log_level = "info",
    suppressed_dirs = { "~/Downloads", "/" }
  }

General Info ~
- Session directory: /Users/{username}/.local/share/nvim/sessions/
- Current session: /Users/{username}/Code/kong-library
- Current session file: /Users/{username}/.local/share/nvim/sessions/%2FUsers%2F{username}%2FCode%2Fkong-library.vim
```

**Baseline (please complete the following information):**
- Result of `set sessionoptions?`:
`sessionoptions=blank,buffers,curdir,folds,help,tabpages,winsize,winpos,terminal,localoptions`
- OS. e.g `uname -a`:
`Darwin 23.6.0 arm64`
- Neovim version `nvim --version`
```
NVIM v0.10.1
Build type: Release
LuaJIT 2.1.1725453128
```

**Additional context**
This has only started to occur after the upgrade to the recent version of autosession plugin about 3 weeks ago

**Comment by cameronr** [comment]
Thanks for the report. I see the issue. It's a simple fix; I'll put together a PR shortly.

**Comment by paulozava** [comment]
Nice to know, I am having the same problem.

**Comment by cameronr** [comment]
This should be fixed now.

@MaroonedMind / @paulozava can you confirm it's working for you?

**Comment by MaroonedMind** [comment]
Can confirm the issue is resolved now with the latest update. 
Thank you @cameronr
