### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by tbkj98** [rmagatti/auto-session#381]
**Is your feature request related to a problem? Please describe.**
I am working with multiple directories/projects in a single NeoVim session.
I am using NeoVim tabs to manage different projects in single session.
I manually set the tab name using [Tabby,nvim](https://github.com/nanozuki/tabby.nvim)

![Screenshot from 2024-09-22 13-41-45](https://github.com/user-attachments/assets/adab5a22-7dc6-4061-b339-0ccb99aeeecb)
From the screenshot attached above, I've renamed the tab to "config".

After saving the session and restoring it, The auto-session plugin restores everything(according to my requirement). but it does not restores the tab name

**Describe the solution you'd like**
I would like the tab names to be restored as well upon session restore.

**Additional context**
If anyone uses other solutions for the mentioned workflow.
Please share, that would be great help.

I have time to contribute to the project.

**Comment by cameronr** [comment]
According to the [`tabby.nvim` docs, you just need to make sure you have `globals` in your `sessionoptions`](https://github.com/nanozuki/tabby.nvim?tab=readme-ov-file#save-and-restore-in-session):

> Save and restore in session
> 
> You can save and restore tab layout and tab names in session, by adding word tabpages(for layout) and globals(for tab names) to vim.opt.sessionoptions. This is a valid sessionoptions:
> 
> vim.opt.sessionoptions = 'curdir,folds,globals,help,tabpages,terminal,winsize'

Can you double check your `sessionoptions`?

**Comment by tbkj98** [comment]
Thank you for the answer.
I was missing "globals" from sessionopts, but even after including globals, it did not work.

**Comment by cameronr** [comment]
Hmm, it worked for me in my testing. Did you make sure to save a new session after adding `globals` to your `sessionoptions` (sessions created before adding `globals` won't have the tabnames)?

Can you post the following:

1. What `set sessionoptions?` returns
2. The contents of a session file from a session with a custom tab name created after you added `globals`?

**Comment by cameronr** [comment]
Hmm, that's very strange. `auto-session` uses native neovim sessions under the hood so it really is odd that it works when you use`mks`/source. Can you post the the following:

1. The full contents of a session you create manually with `mks` that does save tab names
2. The full contents of a session that `auto-session` creates that does not save tab names

I'm trying to figure out if the issue is in saving the tab names to the session file or in restoring the names. Also, if you have your nvim configuration is publicly available that might also help me track down the issue.

**Comment by tbkj98** [comment]
[manual.txt](https://github.com/user-attachments/files/17128160/manual.txt)
[auto-session.txt](https://github.com/user-attachments/files/17128161/auto-session.txt)

I've shared both of them and named the files accordingly.

**Comment by cameronr** [comment]
Interesting, the auto-session.txt session has an empty set of tab names (`let TabbyTabNames = "[]"`) while the manual one is filled out correctly. It looks like those sessions are from two different projects, I wonder if that's related in some way (e.g. maybe it depends on what buffers you have open in each tab). Can you do the following:

0. Set up the tabs (with names) how you want
1. run `:mks manual.vim` to save a manual session caled `manual.vim`
2. run `:SessionSave test` to have auto-session save a session called `test.vim` in `~/.local/share/nvim/sessions/`
3. Exit vim to have auto-session automatically save the session in `~/.local/share/nvim/sessions/` with cwd as the name (with / escaped as %2F)
4. Post the value for `TabbyTabNames` for all three sessions in this issue?

Another possibility is a timing issue between when Tabby sets `TabbyTabNames` and when `auto-session` saves the session.

5. Can you post both your `auto-session` config and your `Tabby` config to this issue?

**Comment by tbkj98** [comment]
Thanks for the help

**Comment by cameronr** [comment]
Glad it's working. For posterity, do you know what ended up being the issue?
