### ISSUE TITLE
[BUG] Session is not AutoCreated on `nvim .`

### ISSUE THREAD

**Issue by jack-obrien** [rmagatti/auto-session#393]
**Describe the bug**

When I open a directory with `nvim .`, auto-session does not save the session. See the additional context - i think it is an issue with allow_files_auto_save

**To Reproduce**

Set the auto_create option to True. cd to a new directory with no saved session named after it. call `nvim .` No session is created on startup (fair I guess, as there's no session to restore). But still no session is saved on close. 

**Expected behavior**
When I run :q after the "To Reproduce" steps, it should create a new session on save.

**Screenshots**

**Checkhealth**
Paste the contents of `checkhealth auto-session` here
```
auto-session: require("auto-session.health").check()

vim options ~
- OK vim.o.sessionoptions

Lazy.nvim settings ~
- OK Lazy.nvim support is enabled
- OK auto-session is not lazy loaded

Config ~
- OK 
  {
    log_level = "debug",
    suppressed_dirs = { "~/", "~/Projects", "~/Downloads", "/" }
  }

General Info ~
- Session directory: /home/grabba/.local/share/nvim/sessions/
- Current session: 
- Current session file: 

```

**Baseline (please complete the following information):**
- Result of `set sessionoptions?`: sessionoptions=blank,buffers,curdir,folds,help,tabpages,winsize,winpos,terminal,localoptions
- OS. e.g `uname -a`: `Linux HP-Workstation 6.8.0-48-generic #48~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Mon Oct  7 11:24:13 UTC 2 x86_64 x86_64 x86_64 GNU/Linux`
- Neovim version `nvim --version`
``` 
NVIM v0.10.2
Build type: RelWithDebInfo
LuaJIT 2.1.1713484068
```
- URL to your current config (if public): https://github.com/jack-obrien/kickstart.nvim
Note that I have disabled a bunch of the config options of auto-session for this bug report, see my checkhealth output.

**Additional context**
I typically run nvim through neovide, but for this report I have just used the command line to call nvim.

With debug enabled, it looks like auto-session thinks my command line argument is a file, not a directory. (This is just when running `nvim .`)
`auto-session DEBUG: args_allow_files_auto_save is false, not enabling restoring/saving`

Thanks for reading! Let me know if you need anything else :)

**Comment by jack-obrien** [comment]
Thank you so much for your detailed help! Lazy loading nvim-tree definitely helped with the path overwriting issue. I found that to disable lazy loading I had to actively specify lazy = true in my nvim-tree options.

**Comment by cameronr** [comment]
Glad it's working! 

If you specify `keys`, `cmd`, `event`, or `ft` in a plugin spec, you shouldn't need to explicitly set `lazy = true` (but you can't have `lazy = false` as that will force it to be not lazy):

https://lazy.folke.io/spec/lazy_loading
https://lazy.folke.io/spec#spec-lazy-loading
