### ISSUE TITLE
[FEATURE] Show notification on auto session restore

### ISSUE THREAD

**Issue by jblsp** [rmagatti/auto-session#394]
**Is your feature request related to a problem? Please describe.**
When restoring a session with this plugin, usually a notification appears indicating that the session has been restored, but when a session is automatically restored on launch no notification appears.

**Describe the solution you'd like**
Create a config option to enable notifications for automatically restored sessions.

**Comment by cameronr** [comment]
Seems reasonable, I'll add shortly.

**Comment by cameronr** [comment]
Ok, I just submitted my PR. If you want to test it, you can temporary change the top of your auto-session config to:

```lua
  -- 'rmagatti/auto-session',
  'cameronr/auto-session',
```

After changing the config, you'll have to open Lazy (or whatever plugin manager you use) and update the plugin to actually pull it down (and restart nvim just to be sure).

Then set `show_auto_restore_notif = true,` and it should now display notifications when auto-restoring.
