### ISSUE TITLE
Sessions history

### ISSUE THREAD

**Issue by Shatur95** [rmagatti/auto-session#4]
Hi! Thank you a lot for the awesome plugin.

It would like to suggest to add the ability to switch between sessions. For example, VSCode have [the following](https://github.com/l13/vscode-projects) plugin. This is very convenient feature. The list of sessions could be selected using [Telescope](https://github.com/nvim-telescope/telescope.nvim).

**Comment by Shatur95** [comment]
Oh, all session accesible throught sessions dir. I can just add a custom picker for Telescope myself.

**Comment by rmagatti** [comment]
This was originally on my mind to add as well after a suggestion in reddit about it.
But I didn't really know how to do it in a way that wouldn't be specific to any particular other plugin like telescope or fzf.

Maybe just knowing there's a sessions dir for now and doing the wiring manually is fine, if more people ask for this maybe it's something that can be added in the future somehow.

@Shatur95 do you mind linking your config for configuring this with Telescope if possible?

**Comment by Shatur95** [comment]
> But I didn't really know how to do it in a way that wouldn't be specific to any particular other plugin like telescope or fzf.

Unfortunately, this kind of integration is always plugin-specific.

> @Shatur95 do you mind linking your config for configuring this with Telescope if possible?

I haven't done it yet, but if I do, I will share it :)

**Comment by rmagatti** [comment]
@Shatur95 I'm in the process of making an "extension" plugin for auto-session called `auto-session-telescope`.
I already have the functionality done on my local config, just cleaning up the code and getting a good README.md going.

Will post it over the next day or two in r/neovim and here as well for reference.

**Comment by Shatur95** [comment]
Sounds awesome, thank you!
I will look forward to it.

**Comment by rmagatti** [comment]
@Shatur95 I did change the name but here it is.
https://github.com/rmagatti/session-lens

I'll do a reddit post about it soon but if you want to try it out and let me know how it goes that would be great!

**Comment by Shatur95** [comment]
> @Shatur95 I did change the name but here it is.

Thank you! But I have an error with `auto-session`:

```
.../nvim/pack/plugins/opt/auto-session/lua/auto-session.lua:119: Vim(lua):E5108: Error executing lua ...im/pack/plugins/opt/nvim-tree.lua/lua/nvim-tree/view.lua:93: Vim:E813: Cannot close autocmd window
```

It looks like it conflicts with nvim-tree somehow?

I also have some suggestions :)

Could you use `vim.fn.mkdir` here? Current command slower, will not work on Windows and causes "Press enter" promt.
https://github.com/rmagatti/auto-session/blob/49e2a0ef443eb0578c2b884a7b85f9f4e4c08fde/lua/library.lua#L90

Maybe it will be better to store such things in `data` folder as default vim sessions? You can also use `vim.fn.stdpath('data') to avoid hardcoding the path.
https://github.com/rmagatti/auto-session/blob/49e2a0ef443eb0578c2b884a7b85f9f4e4c08fde/lua/library.lua#L10

**Comment by Shatur95** [comment]
I decided to wrote [a separate plugin](https://github.com/Shatur95/neovim-session-manager) for my own purposes. It have a different behavior, more like in VSCode.

**Comment by rmagatti** [comment]
> I decided to wrote [a separate plugin](https://github.com/Shatur95/neovim-session-manager) for my own purposes. It have a different behavior, more like in VSCode.

Cool!

Those are great suggestions btw, I'll work into getting them in.

Thanks!

**Comment by rmagatti** [comment]
I like what you did on yours with the last session based on timestamp and closing the buffers before loading a session.

I might have to steal that for auto session too if you don't mind.

Also your code is cleaner than mine, this was my first time coding Lua, and a neovim plugin for that matter, I clearly have to get better at both 😄

**Comment by Shatur95** [comment]
> I like what you did on yours with the last session based on timestamp and closing the buffers before loading a session.

Thanks :) This is how VSCode works. It's more like a history of current working directories with buffers.

> I might have to steal that for auto session too if you don't mind.

Sure! But your plugin is under the MIT license, and mine is under the GPL. If I understand correctly, these licenses are not compatible. I would suggest changing the license to GPL if you want to borrow the code directly.

**Comment by rmagatti** [comment]
> > I like what you did on yours with the last session based on timestamp and closing the buffers before loading a session.
> 
> Thanks :) This is how VSCode works. It's more like a history of current working directories with buffers.
> 
> > I might have to steal that for auto session too if you don't mind.
> 
> Sure! But your plugin is under the MIT license, and mine is under the GPL. If I understand correctly, these licenses are not compatible. I would suggest changing the license to GPL if you want to borrow the code directly.

To be clear, I'm not copying any code from your plugin. 😊
