### ISSUE TITLE
Buffer problem.

### ISSUE THREAD

**Issue by ahmed-rezk-dev** [rmagatti/auto-session#41]
When I close the session and restore the session. It says 3 buffers deleted which is the number I had it opened before closing.

Does it support saving the buffers?

**Comment by rmagatti** [comment]
Hey 👋 thanks for the submission.
Can you elaborate? Where does _it_ say that?

And what are the steps to reproduce what you're experiencing?

**Comment by rmagatti** [comment]
Hey I'm gonna close this for now then. Feel free to reopen.
