### ISSUE TITLE
Feature Request: Command to throw away last session and start with a empty session

### ISSUE THREAD

**Issue by IndianBoy42** [rmagatti/auto-session#42]
Either a command that I can run before closing to throw away the session (so that the next load doesn't reopen this session)
Or  a command that I can run on startup (potentially using `nvim +NoAutoloadSession`) that ignores/deletes the auto saved session

Sometimes I just don't want the previous session, or even worse I quit because I messed up the window layout and want to reset (i suppose this case has another way to solve it but regardless).

The only way right now to load without autosession is `nvim .` but that 1. opens netrw/rnvimr to explore the dir rather than open my dashboard. and 2. then doesn't save the session to reopen next time.

**Comment by rmagatti** [comment]
Added a `DisableAutoSave` command.

One could technically do `nvim "+let g:auto_session_enable = 0"` but it doesn't seem to be working right now. I'll dig into why when I get some free time.

**Comment by IndianBoy42** [comment]
I don't think DisableAutoSave is working

I am trying to do `DeleteSession` followed by `DisableAutoSave`. But when I close it still creates a new session file

**Comment by rmagatti** [comment]
`DeleteSession` already disables auto saving on close automatically. Do you maybe have a video showing the issue? Also would be helpful to look at what your config looks like.

**Comment by IndianBoy42** [comment]
My config is here: https://github.com/IndianBoy42/LunarVim although its a lot

I can record a video but basically its as I said, DeleteSession does delete the session file (checking with ls), but when I `:qa` it recreates it

**Comment by IndianBoy42** [comment]
Oh, Im sorry, it was another plugin saving the session for me...
