### ISSUE TITLE
Disabling auto session on startup is not working

### ISSUE THREAD

**Issue by rmagatti** [rmagatti/auto-session#44]
One could technically do `nvim "+let g:auto_session_enable = 0"` but it doesn't seem to be working right now.

_Originally posted by @rmagatti in https://github.com/rmagatti/auto-session/issues/42#issuecomment-876473978_

**Comment by IndianBoy42** [comment]
I think `nvim +X` is defined as running the command after the config and/or the first file. `nvim --cmd X` would run the command before any config file. 

But that also doesn't work so thats strange...

**Comment by rmagatti** [comment]
This actually works.
`nvim "+let g:auto_session_enabled = v:false"`
