### ISSUE TITLE
DeleteSession doesn't work if performed in the same instance as RestoreSession

### ISSUE THREAD

**Issue by kdheepak** [rmagatti/auto-session#48]
Thanks for making this plugin!

I have the following configuration:

```
    use {
      'rmagatti/auto-session',
      config = function()
        local opts = {
          log_level = 'info',
          auto_session_enabled = false,
          auto_save_enabled = false,
          auto_restore_enabled = false,
        }
        require('auto-session').setup(opts)
      end,
    }
```

If I do the following:
 
1) open vim, 
2) open a bunch of buffers, 
3) SaveSession, 
4) Exit vim, 
5) RestoreSession, 
6) DeleteSession,
7) Close all open buffers
7) RestoreSession

I was expecting the session to not open again. However it does. The session file also exists on disk before the last RestoreSession call. If I call RestoreSession, close vim, open vim and then call DeleteSession it works as expected. I'm assuming this is a bug? If not, let me know if I'm not using it correctly.

**Comment by rmagatti** [comment]
Hey @kdheepak, I can't seem to reproduce this.
When trying your step 8 it doesn't restore anything because there is no session file anymore.

Logs with `debug` level:
<img width="549" alt="Screen Shot 2021-07-30 at 12 10 59 AM" src="https://user-images.githubusercontent.com/2881382/127608798-7846d6d3-25f2-4fc3-a9c3-7c0bdae36217.png">

**Comment by rmagatti** [comment]
Come to think of it you might be having an issue with the `DeleteSession` command? Can you set the log level to debug, try again and show me what you get?

As for if this is the "right" usage, it really depends on you, I dislike having to manually save or restore sessions, hence why the default behaviour of the plugin is to do this for me, but if disabling the automatic behaviour is what works for you, then by all means keep at it 😊

**Comment by kdheepak** [comment]
Okay, I don't know exactly what I was going but now I think I understand what my problem actually is.

When I have these settings:

```
          auto_session_enabled = false,
          auto_save_enabled = false,
          auto_restore_enabled = false,
```

And I quit vim, my session is always being saved. So `RestoreSession` restores the last state before `:q` instead of when `SaveSession` was called last.

**Comment by kdheepak** [comment]
So, if I just open vim and `:q` it doesn't `SaveSession`. However, if I `SaveSession` manually once, then when I `:q` it appears that it always runs `SaveSession`.

**Comment by kdheepak** [comment]
And for what it is worth, these lines are the last lines of my `vim.log` file when I run `vim -V9vim.log` and use it with `SaveSession`:

<img width="650" alt="Screen Shot 2021-08-01 at 4 07 00 PM" src="https://user-images.githubusercontent.com/1813121/127786662-548b61c5-b88b-407d-8474-3a7bc9a67e42.png">

**Comment by kdheepak** [comment]
I added a `print(auto_save())` instead the `SaveSession()` function, and that is returning `false`. Which is what is seen in the screenshot above.

However, the following lines are in my `vim.log` file which I think is the culprit:

```
Executing VimLeavePre Autocommands for "*"
autocommand if ! empty(v:this_session) && ! exists('g:SessionLoad') |   execute 'mksession! ' . fnameescape(v:this_session) | endif
```

I don't think this is the fault of this plugin. I will close the issue.

**Comment by kdheepak** [comment]
I figured it out. `dashboard.nvim` has a session feature too: https://github.com/glepnir/dashboard-nvim/blob/ba98ab86487b8eda3b0934b5423759944b5f7ebd/plugin/dashboard.vim#L55-L73

Changing my plugin configuration to the following solves this issue for me:

```
    use {
      'glepnir/dashboard-nvim',
      config = function()
        vim.g.dashboard_enable_session = false
      end,
    }
```
