### ISSUE TITLE
Use case: managing N sessions for a project

### ISSUE THREAD

**Issue by mellery451** [rmagatti/auto-session#49]
This is more of a usage question. Feel free to close this if you don't have the time or interest in answering it.

I've switched to this plugin largely because it has telescope support. I have several large (git) projects and typically want to have a couple of sessions that I can easily switch between but that apply ONLY to the given project. Some sessions managers will handle this by putting session files into the .git directory (if one is found), otherwise default to the master/default location. Is there a way to configure this plugin that way? 

Either way, how would you recommend managing a small number of sessions that apply to a given project - goals are (1) easy switching between them..but only to sessions that apply to the project, and (2) auto reload the last session that I had open for a given project.

Any advice appreciated.

**Comment by rmagatti** [comment]
Hey, so this plugin works by assuming a few things, one of them being that there's one session per "cwd directory".
So even in your one project you can technically have more than one session, but really only if those sessions are on different directories.

Overall, the idea of multiple sessions for one "project" is not really an intentionally supported flow.
Btw, the plugin does have "open last session" feature.

**Comment by mellery451** [comment]
understood - thanks for the explanation.
