### ISSUE TITLE
The ability to load last session if there is no session for the current directory

### ISSUE THREAD

**Issue by Shatur95** [rmagatti/auto-session#5]
At the moment, if the session for the current folder was not found, then a new session is started. But this is not always convenient, because Neovim can be launched from the GUI, for example. It would be awesome to load last session if there is no saved session for the current directory.

**Comment by rmagatti** [comment]
I think this can be an option to be set for sure.
I personally prefer the current behaviour but I can see why you'd want the behaviour you mentioned too.

I'll cook something up for this. Thanks for bringing it up!
