### ISSUE TITLE
Named Sessions

### ISSUE THREAD

**Issue by sujaybokil** [rmagatti/auto-session#51]
Hii, love your plugin, it works fantastically. Is there any chance of adding named sessions to the plugin, probably while running the `:SaveSession` command? For example,

```
:SaveSession  ~/some_directory/session_name.vim
```
Right now, if the command is executed it will still append the name of the file based on cwd at the end of the given session name.

Another request I would like to make is to add the change to `sessionoptions` to the documentation for the plugin to work correctly
```
# Add to init.lua
vim.o.sessionoptions="blank,buffers,curdir,folds,help,options,tabpages,winsize,resize,winpos,terminal"
# Add to init.vim
set sessionoptions+=options,resize,winpos,terminal
``` 
Without using the following settings the files from the session would be restored correctly in my case but the splits and their sizes would not be. 

Thank you

**Comment by rmagatti** [comment]
Thanks for the submission! I'm glad you like it!
Added the suggested improvements. Lmk if things don't work!
