### ISSUE TITLE
Plugin stopped working after eac476d0 on macOS

### ISSUE THREAD

**Issue by rafi** [rmagatti/auto-session#53]
Hi there. After the eac476d0 commit, I'm unable to save session. I'm using macOS, and since this commit:

```
==== Pager mode false
sessions dir or file nil
==== Using session DIR
==== Session Name \%Users\%rafi\%src\%bla\%foo
==== is_readable false
==== is_readable false
File not readable, not restoring session
sessions dir or file nil
==== Using session DIR
==== Session Name \%Users\%rafi\%src\%bla\%foo
==== is_readable false
==== is_readable false
File not readable, not restoring session
SaveSession param is not a directory, saving as a file.
Session saved at
```

Session is saved in current path as `Session.vim`, not what expected.

**Comment by wilriker** [comment]
I can see the same behavior on Linux. In addition I can see the following error message thrown by `nvim`:
```
E5108: Error executing lua ...site/pack/packer/start/auto-session/lua/auto-session.lua:178: attempt to concatenate local 'session' (a nil value)
```

What happens (AFAICT) is that the new `local session` is initialized from an empty value `sessions_dir`. And while `sessions_dir` is checked on the following line if it is empty and then being overwritten with the return value of `AutoSession.get_root_dir()` this won't affect the emptiness of `session` and `nvim` complains about concatenating a `nil` value.

**Comment by rmagatti** [comment]
Yeah fixed by #54.
That was my bad.

This reminds me I should come up with tests for the plugin so I don't break core functionality in the future.

**Comment by rmagatti** [comment]
@rafi @wilriker lmk if the fix doesn't work 🙏

**Comment by wilriker** [comment]
I can confirm it works again for me.
