### ISSUE TITLE
Runtime path is messed up when plugin loaded

### ISSUE THREAD

**Issue by jonasstr** [rmagatti/auto-session#57]
I'll try to explain a weird problem I had today and explain why I believe this has to do with this plugin (I have been using this plugin for some time and had no issues before this). I opened Neovim and suddenly had no TreeSitter syntax highlighting anymore, like this:
![Screenshot from 2021-08-23 21-03-53](https://user-images.githubusercontent.com/40792180/130503291-4e85c0a8-d550-40ac-af7c-4a7803ab8df2.png)

Then I tried running `:checkhealth` and got this error: `E5009: Invalid 'runtimepath'`

So I checked `set runtimepath?` which prints this output (shortened for readability):

`runtimepath=~/.config/nvim, [...], /tmp/.mount_nvim8wjgL7/usr/share/nvim/runtime,/tmp/.mount_nvim8wjgL
7/usr/share/nvim/runtime/pack/dist/opt/matchit,/tmp/.mount_nvim8wjgL7/usr/lib/nvim, [...]`

Notice the path is **.mount_nvim8wjgL7**. 

I read [here](https://www.reddit.com/r/neovim/comments/7bvu61/question_about_vimruntime/dpla7f4?utm_source=share&utm_medium=web2x&context=3) that the runtime path must contain the result of `$VIMRUNTIME`.

This was not the case for me since `echo $VIMRUNTIME` prints `/tmp/.mount_nvimbXWU5b/usr/share/nvim/runtime` (this time it's a different path **.mount_nvimbXWU5b**)

I then disabled the auto-session plugin and all the problems were gone. So I assume that the session is somehow loaded incorrectly.

Does this even have to do something with this plugin or is this a Neovim specific issue? I hope this made any sense ^^ 

Thanks for your time!

**Comment by rmagatti** [comment]
Thanks for the submission!

I've had some weird "corrupted sessions" issues myself before. From the sound of what you explained I think it's likely more to do with that than with the plugin itself.

Auto Session uses Neovim's `mksession` and `source` commands under the hood and doesn't really do any runtime path manipulation.

What I've done in odd cases like these is run a `:DeleteSession` with no params to delete the currently loaded session, then close Neovim and reopen the project. Issues are usually gone after that for me.

Let me know if this doesn't really work for you or if you still think it's somehow related to something this plugin does!

**Comment by rmagatti** [comment]
Hm, oddly enough I also started getting no syntax highlighting when first loading the file, since yesterday that is. Are you using treesitter by any chance?

**Comment by jonasstr** [comment]
Hmm that is weird. Yes I am using Treesitter.

**Comment by rmagatti** [comment]
Reopening this for tracking purposes. I don't really see issues with my path but I do get the "no highlight" issue.

**Comment by rmagatti** [comment]
Okay, this took me a while but I figured it out.

After disabling and enabling plugins "binary search" style for quite a bit I landed on this:
I was ending up without syntax highlighting because of `telescope-fzf-native`. I was lazy loading it on `BufReadPre` which apparently is not a great idea and really just not the right way of lazy loading something like that.

Since then I've fixed some of my lazy loading and no issues with highlighting for me anymore. I don't think this necessarily helps your case here but maybe it'll hint you to what might be going on?

**Comment by jonasstr** [comment]
Thanks for looking into this further! I also have `telescope-fzf-native` installed but removing it did not help unfortunately. At least I found out by looking at your config that I did not have Treesitter highlighting enabled since I started using Neovim... Well I guess thanks for that, it's much more colorful now :smiley:

**Comment by rmagatti** [comment]
More colourful is always good! Glad I could help on something :)

I still don't quite understand your runtime issue since nothing in auto-session would really affect that.
One thing that stands out is the fact that you have a `mount` thing in your path 🤔 mind elaborating on what your setup looks like?

**Comment by jonasstr** [comment]
Yes you can check out my config [here](https://github.com/jonasstr/dotfiles/tree/master/.config/nvim), but I did not specifically change anything regarding the path. Maybe this is related to `mount`: [https://docs.appimage.org/user-guide/run-appimages.html#mount-an-appimage](https://docs.appimage.org/user-guide/run-appimages.html#mount-an-appimage). I use the 0.5 appimage from the neovim GitHub page.

**Comment by lucasvianav** [comment]
I'm also having all the issues described by @jonasstr and more 🙃 

Everything was working fine until the day before yesterday, when I stopped getting TreeSitter syntax highlighting whenever restoring a session. At first it was fine, I would just run `:windo e`, but then suddenly everything broke and I could not even move anymore without getting spammed the following warning at every keypress.

I do not have `telescope-fzf-native` installed, but my full config is [here](github.com/lucasvianav/nvim).

```
Error executing vim.schedule lua callback: [string "<nvim>"]:64: vim.lua:93: module 'vim.treesitter' not found:
        no field package.preload['vim.treesitter']
        no file './vim/treesitter.lua'
        no file '/home/runner/work/neovim/neovim/.deps/usr/share/luajit-2.1.0-beta3/vim/treesitter.lua'
        no file '/usr/local/share/lua/5.1/vim/treesitter.lua'
        no file '/usr/local/share/lua/5.1/vim/treesitter/init.lua'
        no file '/home/runner/work/neovim/neovim/.deps/usr/share/lua/5.1/vim/treesitter.lua'
        no file '/home/runner/work/neovim/neovim/.deps/usr/share/lua/5.1/vim/treesitter/init.lua'
        no file '/home/v0004/.cache/nvim/packer_hererocks/2.1.0-beta3/share/lua/5.1/vim/treesitter.lua'
        no file '/home/v0004/.cache/nvim/packer_hererocks/2.1.0-beta3/share/lua/5.1/vim/treesitter/init.lua'
        no file '/home/v0004/.cache/nvim/packer_hererocks/2.1.0-beta3/lib/luarocks/rocks-5.1/vim/treesitter.lua'
        no file '/home/v0004/.cache/nvim/packer_hererocks/2.1.0-beta3/lib/luarocks/rocks-5.1/vim/treesitter/init.lua
'
        no file './vim/treesitter.so'
        no file '/usr/local/lib/lua/5.1/vim/treesitter.so'
        no file '/home/runner/work/neovim/neovim/.deps/usr/lib/lua/5.1/vim/treesitter.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
        no file '/home/v0004/.cache/nvim/packer_hererocks/2.1.0-beta3/lib/lua/5.1/vim/treesitter.so'
        no file './vim.so'
        no file '/usr/local/lib/lua/5.1/vim.so'
        no file '/home/runner/work/neovim/neovim/.deps/usr/lib/lua/5.1/vim.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
        no file '/home/v0004/.cache/nvim/packer_hererocks/2.1.0-beta3/lib/lua/5.1/vim.so'
```

**Comment by lucasvianav** [comment]
Yesterday I found out that my `runtimepath` and `Error executing vim.schedule lua callback` were due to having `options` in my `sessionoptions`. I am not sure of why that is (and will open an issue at the neovim repo), but once I removed that, those errors went away. @jonasstr do you have that setting as well?

The not having syntax highlighting when restoring a session is still happening (and is even worse when the session has multiple windows), but now I don't think this is a auto-session issue, but rather a neovim/treesitter one, for this also happens when sourcing a regular session file unrelated to the plugin.

**Comment by jonasstr** [comment]
Thanks for this tip! I do indeed have `sessionoptions` set since this had been recommended in the readme. I will try removing them soon and confirm if this changed anything for me.

**Comment by lucasvianav** [comment]
I guess it's not necessary to remove the whole `sessionoptions`, just the `options` value if you use Packer's lazyload -- I didn't see that section on the README before and that was what was breaking things for me.

**Comment by jonasstr** [comment]
Thank you so much @lucasvianav, removing `options` from `sessionoptions` fixed it for me! @rmagatti Could you maybe add a note to the readme to inform other users about this potential fix? Is this a neovim bug?

**Comment by lucasvianav** [comment]
It's already on the README:
>Note: if you use packer.nvim's lazy loading feature, you might want to not add the options value to sessionoptions. It might lead to weird behaviour with the lazy loading, especially around key-based lazy loading.

**Comment by jonasstr** [comment]
Oh I didn't see this. Even then, this makes it sound like it's a packer.nvim issue - I use vim plug and still had this issue.

**Comment by lucasvianav** [comment]
Maybe it's a general lazy-loading problem.

**Comment by rmagatti** [comment]
I'll be closing this for now then!
