### ISSUE TITLE
[Feature Request] Seperate AutoSave and AutoCreate

### ISSUE THREAD

**Issue by wilriker** [rmagatti/auto-session#59]
I would like to see the possibility to separate auto-saving of sessions from auto-creation of sessions. What I mean is that an existing session (created e.g. manually with `:SaveSession`) will be saved on `VimLeave` as of now but it will not create a new session if there is none already.

Currently one can only specify `auto_session_suppress_dirs` but that is of course unfeasable if one only wants to create and track a few explicit sessions.

Alternatively (but of course less flexible) would be to provide `auto_session_include_dirs` as an inverse to `auto_session_suppress_dirs`.

**Comment by rmagatti** [comment]
Hey, thanks for the subimssion!

There's an ongoing PR for adding an `include_dirs` feature. https://github.com/rmagatti/auto-session/pull/58

Now as for the feature request itself:

> What I mean is that an existing session (created e.g. manually with :SaveSession) will be saved on VimLeave as of now but it will not create a new session if there is none already.

I'm not sure I follow what you mean, running a `:SaveSession` manually effectively creates a session by running a `mksession`, so "create" and "save" at the same time.
The command won't actually enable auto-saving through `VimLeave` as it's a manual action in this case.

Maybe I'm misunderstanding what you'd like to get from the proposed feature, would you mind sharing some more about your config and the behaviour you're expecting overall?

**Comment by wilriker** [comment]
I was afraid that I would not be able to convey what I mean first try. :-D

So here, is what I currently have:
* I have a total of 8 sessions as of right this moment
* I also have my home directory excluded via `auto_session_suppress_dirs`

Now to what I would like to see:
* Whenever I open one of these 8 sessions it should be saved when I either close neovim or load another session (via session-lens - great plugin by the way, using it constantly throughout my working day)
* There should never be any session automatically created in any other directory unless I manually call `:SaveSession`

In other words, I'd like auto-session to continue updating existing sessions but it should never create a session for a directory by itself similar to
> 2. When starting `nvim .` with some argument, auto-session will do nothing.

just that I want this to be the default. So one simple rules (I guess)
Is there already a session for the current `cwd`?
* Yes: update it
* No: do not create one

Reason for this request (maybe that explains it better): I do use a [rooter plugin](https://github.com/ahmedkhalf/project.nvim) to change `cwd` to the root of a file opened. When I now navigate into source-code of a library in e.g. a Golang project this plugin will change `cwd` to the root of this library as represented on my disk. That will cause auto-session to say "oh wait, there is no session here, so I am going to create one" and I now have an unwanted extra session in a compiler-managed dependency directory.

**Comment by rmagatti** [comment]
Right I do see your point there. It'd be nice to have a way to break these down as long as the current behaviour is still the default one.

Yeah if you can get to it before I can, that'd be lovely, thanks for the help 😊

**Comment by ivanddm** [comment]
Thanks @rmagatti for this very nive plugin. This is exactly the behavior that I wanted to setup but it took me some time to realize that the option `auto_session_create_enabled` existed as it is not documented yet.

**Comment by rmagatti** [comment]
@ivanddm, oh I hadn't realized this was undocumented, thanks for pointing it out! I'd greatly appreciate it if you could send me a PR for an updated readme! 😊

**Comment by ivanddm** [comment]
Sure, will do so ASAP @rmagatti.

Thanks again!
