### ISSUE TITLE
incorrect session restored

### ISSUE THREAD

**Issue by Chaitanyabsprip** [rmagatti/auto-session#61]
session was restored from one of the "allowed_dirs" and I was in a seperate directory.

**Comment by rmagatti** [comment]
Do you have a reproducible example I can look at?

**Comment by Chaitanyabsprip** [comment]
I simply installed the plugin and added three paths to auto_session_allowed_dirs, I launch nvim from the directory one of dirs mentioned in the list and then open some random buffers to allow to auto-session to create a session file. I exit from nvim and then open the second directory mentioned in the list and the original session is opened, one from the previous directory.

**Comment by Chaitanyabsprip** [comment]
```lua
local u = require("utils")
require('auto-session').setup {
  log_level = 'info',
  auto_session_enable_last_session = true,
  auto_session_root_dir = vim.fn.stdpath('data') .. "/sessions/",
  auto_session_enabled = true,
  auto_save_enabled = nil,
  auto_restore_enabled = nil,
  auto_session_suppress_dirs = {"/Users/user"},
  auto_session_allowed_dirs = {
    "/Users/user/Projects/Application Development/crimson",
    "/Users/user/Projects/Application Development/lernit",
    "/Users/user/Projects/Application Development/flutter_clean_auth_architecture"
  }
}

require('session-lens').setup {
  -- path_display = {'shorten'},
  -- theme_conf = {border = false},
  previewer = true
}

require("telescope").load_extension("session-lens")

u.kmap('n', '<leader>s',
       '<CMD>lua require("session-lens").search_session()<CR>',
       {noremap = true, silent = true})
```

This is how I have set it up

**Comment by Chaitanyabsprip** [comment]
I believe you will just have to check whether the session directory and the current directory match before restoring it.

**Comment by rmagatti** [comment]
Hey @Chaitanyabsprip I just noticed, this is likely because you have `auto_session_enable_last_session = true,` as a setting.

Here's the readme piece about it.
https://github.com/rmagatti/auto-session#last-session

**Comment by Chaitanyabsprip** [comment]
Ah, makes sense. I should read the "README" more closely. Thank you for your help.
