### ISSUE TITLE
change global variable

### ISSUE THREAD

**Issue by aspeddro** [rmagatti/auto-session#65]
how i can change a global variable?

Example:

```lua
--- init.lua
vim.g.nvim_tree_auto_open = 0 -- nvim-tree.lua plugin
```
i open side bar then save and quit. The behavior expected is than sidebar should be opened. I try create hooks to modify `vim.g.nvim_tree_auto_open`, but not work.

```lua
local function nvim_tree()
  local nvim_tree_status = require'nvim-tree.view'.win_open() and 1 or 0
  vim.api.nvim_set_var('nvim_tree_auto_open', nvim_tree_status)
end


require('auto-session').setup {
    pre_save_cmds = { nvim_tree }
}
```

**Comment by rmagatti** [comment]
I haven't used `nvim_set_var` but I figure you could just do `vim.g.nvim_tree_auto_open = 1` in the hook function instead?
Printing the result of what the global var looks like in the function might also be useful to figure out what's happening.

Either way this looks to me like an issue with setting the value, not with the hook itself running as far as I can tell.
