### ISSUE TITLE
Some questions I have about options and docs

### ISSUE THREAD

**Issue by augustocdias** [rmagatti/auto-session#67]
Could you document what which of this options involve?

```
vim.o.sessionoptions="blank,buffers,curdir,folds,help,options,tabpages,winsize,resize,winpos,terminal"
```

I'm having an issue which when I reopen neovim it is not getting the changes I made in my settings and keymaps, and I have no idea which of theses is causing this. (at first I thought it were the `options` but even after disabling it, the "issue" persisted)

And what's the difference between `auto_save_enabled` and `auto_session_enabled`? They seem the same to me

**Comment by rmagatti** [comment]
Hi @augustocdias thanks for the submission.

This would be better as a discussion most likely but that's alright.
You can read what each of these options does in the help docs. `:h sessionoptions`.

`options` or `localoptions` are probably what should hold that info for you.

As for the enabled flags:
- `auto_save_enabled`: is just a more granular control option, it really just toggles the auto saving of a session, not the restoring of one for example.
- `auto_session_enabled`: toggles the whole plugin, so auto-session will do nothing if this is disabled, not save, not restore, nothing.

**Comment by augustocdias** [comment]
Tks for the info. I didn't open a thread in the discussions because it is not available for me. Is it enabled for the repo?

**Comment by rmagatti** [comment]
Oh you're right, I guess it wasn't 🙃. It should be enabled now! Thanks 🎉 

I hope the above answers your questions though!
