### ISSUE TITLE
[Feature Request] Option to not autosave session if only buffer is of filetype x,y,z,...

### ISSUE THREAD

**Issue by lucasvianav** [rmagatti/auto-session#69]
Would be nice to not save a session with only a Dashboard buffer (same for Startify, Packer, gitcommit, etc). I could maybe make a PR for this if you'd be ok with that

**Comment by rmagatti** [comment]
Yeah this could be a good feature if it's generic enough ofc. I'd welcome a PR!

**Comment by lucasvianav** [comment]
Great, I'll look into it :)

**Comment by rmagatti** [comment]
@glyh @lucasvianav mind testing out the branch in the draft PR?

**Comment by lucasvianav** [comment]
Hey @rmagatti

Sorry for the delay, life's been a little chaotic. Since it's working and merged, so I'll close this issue
