### ISSUE TITLE
[FEATURE] Support the extra data in session, which is "x.vim".

### ISSUE THREAD

**Issue by nanozuki** [rmagatti/auto-session#74]
**Is your feature request related to a problem? Please describe.**

* Some non-file buffer, I want to store/restore it more accurately with my customized config.
* I'm writing a tabline plugin, and there are some data (such as customer tab name), I want to store in session to get better UX.

**Describe the solution you'd like**

I found that, nvim has a built-in feature for this. In `:help :mksession`:

```
10. If a file exists with the same name as the Session file, but ending in
   "x.vim" (for eXtra), executes that as well.  You can use *x.vim files to
   specify additional settings and actions associated with a given Session,
   such as creating menu items in the GUI version.
```

So, 'Auto-session' might provide a hook/config to let users put codes in "*x.vim".

**Describe alternatives you've considered**
Provide a public function to let the user know the filename of the current session. In case the user can store their own "*x.vim".

**Comment by rmagatti** [comment]
Hey @nanozuki, any luck? This does seem like it would be a cool thing to support. I'll try to get to it if you haven't started anything yet

**Comment by nanozuki** [comment]
Oh, last weekend, I had a surprise visit from a good friend, which made me so busy that I didn't have time to write code 😂. At the earliest, I might start writing Saturday afternoon. (UTC+8). If you like to start earlier, I will happy to enjoy your results, otherwise, I also glad to implement this feature.
