### ISSUE TITLE
[BUG] Loading a session in smaller terminal window breaks neovim

### ISSUE THREAD

**Issue by dlee** [rmagatti/auto-session#78]
**Describe the bug**
When you close a session from a larger terminal window and then reload the session from a smaller terminal window, neovim ends up broken.

**To Reproduce**
1. Open neovim in a large terminal window.
2. Exit neovim to auto-save session.
2. Reduce terminal window size.
3. Open neovim to auto-restore session.
4. neovim is broken

**Expected behavior**
restoring a session from a larger window should not break neovim.

**Screenshots**

https://user-images.githubusercontent.com/7035/138635418-a2de5264-a6d1-4d98-b602-75cc93821584.mov

**Baseline (please complete the following information):**
 - OS. e.g `uname -a`: Darwin Kernel Version 19.6.0
 - Neovim version `nvim --version`
```
NVIM v0.5.1
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: clang -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -O2 -DNDEBUG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/tmp/neovim-20210927-21425-quzo0s/neovim-0.5.1/build/config -I/tmp/neovim-20210927-21425-quzo0s/neovim-0.5.1/src -I/usr/local/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include -I/usr/local/opt/gettext/include -I/tmp/neovim-20210927-21425-quzo0s/neovim-0.5.1/build/src/nvim/auto -I/tmp/neovim-20210927-21425-quzo0s/neovim-0.5.1/build/include

Features: +acl +iconv +tui
```

**Comment by rmagatti** [comment]
Yeah removing the `resize` seems to do something, but doesn't really solve it. Either way, worth opening an issue upstream with Neovim about it.

**Comment by rmagatti** [comment]
@dlee I actually think removing `resize` from my `sessionoptions` did actually fix it. I assume because it then draws the size like it normally would when opening Neovim instead of using values that are potentially outdated compared to the current size of the terminal window.

**Comment by rmagatti** [comment]
Closing since there is a workaround of removing `resize` from `sessionoptions`.
