### ISSUE TITLE
[BUG] Load session, BufReadPost with C++

### ISSUE THREAD

**Issue by chriztheanvill** [rmagatti/auto-session#84]
**Describe the bug**
Trying loading a source or header in C++, does not load intellisense.
```sh
Error detected while processing BufReadPost Autocommands for "*.h":
E117: Unknown function: dist#ft#FTheader
```

**To Reproduce**
1. SaveSession, just a source or header
2. Close neovim
3. Load Session
4. Switch to source or header

**Expected behavior**
Switching to Header or Source without problems.

**Screenshots**
![image](https://user-images.githubusercontent.com/37992958/139558798-4516d155-0f62-4ce8-8c37-9b90b03e4cce.png)

![image](https://user-images.githubusercontent.com/37992958/139558804-56674009-8fcb-4af9-b925-6359cd5d51f7.png)

**Baseline (please complete the following information):**
 - OS. e.g `uname -a`: Linux cris-pc 5.13.0-21-generic #21-Ubuntu SMP Tue Oct 19 08:59:28 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

 - Neovim version `nvim --version`: 0.5.1
 - URL to your current config (if public): https://github.com/chriztheanvill/My_Neovim (its not updated)

**Additional context**

**Comment by rmagatti** [comment]
Hey @chriztheanvill, sorry I don't quite see how this is related to auto-session?
Where it seems to failing for you is on the processing of the `BufReadPost` autocmd, at which point auto-session has already done its job of restoring your session. Your Neovim at that point in time not being able to find the `dist#ft#FTHeader` function isn't really related to what auto-session is doing.

One thing to look out for is around lazy loading, there's a chance whatever plugin you might be lazy loading to get your completion might not be happening correctly.

**Comment by chriztheanvill** [comment]
> Hey @chriztheanvill, sorry I don't quite see how this is related to auto-session? Where it seems to failing for you is on the processing of the `BufReadPost` autocmd, at which point auto-session has already done its job of restoring your session. Your Neovim at that point in time not being able to find the `dist#ft#FTHeader` function isn't really related to what auto-session is doing.
> 
> One thing to look out for is around lazy loading, there's a chance whatever plugin you might be lazy loading to get your completion might not be happening correctly.

This error only happens when I use:
```vim
vim.o.sessionoptions="blank,buffers,curdir,folds,help,options,tabpages,winsize,resize,winpos,terminal"
```

**Comment by rmagatti** [comment]
Try removing `options` from your `sessionoptions`.

**Comment by rmagatti** [comment]
Closing as there's no evidence this is related to or can be fixed by this plugin.
