### ISSUE TITLE
[BUG] I can't run it in Debian on my RaspberryPi

### ISSUE THREAD

**Issue by Fatpandac** [rmagatti/auto-session#86]
![image](https://user-images.githubusercontent.com/30423976/139827368-9076fa63-cef0-482b-88d6-e6e6b0cb02b5.png)

Lua 5.4
Neovim 0.4.4

**Comment by rmagatti** [comment]
Neovim 0.4 is not supported. You need at least 0.5.0.

**Comment by Fatpandac** [comment]
> Neovim 0.4 is not supported. You need at least 0.5.0.

Thx
