### ISSUE TITLE
[FEATURE] Integration with VimspectorMkSession functionality

### ISSUE THREAD

**Issue by Issafalcon** [rmagatti/auto-session#87]
**Is your feature request related to a problem? Please describe.**
Currently, to save a Vimspector session (saves all breakpoints) to the auto-session files, I need to use a post_save command hook to modify the session file using the vimspector plugin function VimspectorMkSession

**Describe the solution you'd like**
It would be great if this could be incorporated by default (or with a configuration setting to toggle) into auto-session, so all my vimspector breakpoints are also stored in the session file without all the additional configuration. I'm sure others would also find this useful.

**Describe alternatives you've considered**
As above, using the post_save command hook works OK, but this feature would be great to see

**Additional context**
To clarify, what I use currently in my lua setup for neovim
`
require('auto-session').setup {
    post_save_cmds = {"VimspectorMkSession"},
    post_restore_cmds = {"VimspectorLoadSession .vimspector.session"}
}
`

**Comment by rmagatti** [comment]
Hey, thanks for the submission!

I think the whole point of the hooks is to make things like this achievable.
In the interest of keeping auto-session small and relatively simple, I would like to avoid adding specific plugin integration directly into the plugin.

**Comment by Issafalcon** [comment]
No problem. I understand completely. I'll close the issue.
