### ISSUE TITLE
[BUG] Buffers restored in last-save order | Neovim 0.6.0

### ISSUE THREAD

**Issue by lcrockett** [rmagatti/auto-session#90]
**Describe the bug**
Whenever a session is restored, buffers are restored in the order they were saved. Prior to Neovim 0.6.0 (`HEAD`) buffers were restored in the same order they were opened.

**To Reproduce**
1. Open 2 different buffers in 1 window
2. Save buffer 1
3. Save buffer 2
4. Save sesssion
5. Open Neovim
6. Restore session
7. Observe buffer 2 being the first buffer loaded (after buffer 2)

**Expected behavior**
I would expect buffer 1 to be the first loaded buffer, as prior to saving the session buffer 1 was also the first loaded buffer. This behaviour is consistent with Neovim 0.5.1-stable and Neovim 0.5.0. Only in 0.6.0 (`HEAD`) did this behaviour change.

**Baseline (please complete the following information):**
 - Ubuntu 20.04 LTS
 - v0.6.0-dev+579-g2f37ffb71

**Additional context**
I'm linking to a different issue in a bufferline plugin where this behaviour is laid out from a slightly different perspective: https://github.com/akinsho/bufferline.nvim/issues/253

**Comment by rmagatti** [comment]
Thanks for the submission @lcrockett 

Like @akinsho mentioned this loooks like it's new behaviour from Neovim upstream.
auto-session merely wraps `mksession` and `source session.vim` functionality and doesn't do any sorting of buffers within the plugin itself.

It might be worth opening an issue with neovim/neovim if you believe the current behaviour to not be the ideal behaviour.

**Comment by lcrockett** [comment]
I'll follow up with Neovim, thanks for that.

**Comment by sgon00** [comment]
@lcrockett I can't find the bug you opened in neovim, I found a similar bug instead: https://github.com/neovim/neovim/issues/28879
