### ISSUE TITLE
[BUG] Loading a session seem to NOT trigger FileType autocommands

### ISSUE THREAD

**Issue by caenrique** [rmagatti/auto-session#95]
**Describe the bug**
Loading a session seem to NOT trigger FileType autocommands

I have lsp setup with [nvim-metals](https://github.com/scalameta/nvim-metals) and [lsp_signature](https://github.com/ray-x/lsp_signature.nvim) and the lsp server attaches with the FileType autocommand.
If I run `:RestoreSession` it works as expected, but on VimEnter it doesn't seem to be triggering this autocommand.

**To Reproduce**

minimal.lua:
```lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvim/site]]
local package_root = '/tmp/nvim/site/pack'
local install_path = package_root .. '/packer/start/packer.nvim'
local function load_plugins()
  require('packer').startup {
    {
      'wbthomason/packer.nvim',
      {"scalameta/nvim-metals", requires = "nvim-lua/plenary.nvim" },
      "ray-x/lsp_signature.nvim",
      "rmagatti/auto-session",
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. '/plugin/packer_compiled.lua',
      display = { non_interactive = true },
    },
  }
end
_G.load_config = function()

  -- Metals
  vim.cmd([[augroup lsp]])
  vim.cmd([[autocmd!]])
  vim.cmd([[autocmd FileType scala,sbt lua require("metals").initialize_or_attach(metals_config)]])
  vim.cmd([[augroup end]])

  metals_config = require("metals").bare_config()
  metals_config.on_attach = function(client, bufnr)
    print(">>> ATTACHINGGGG!!!!!!!!!!!!!!!!!!!!!!!")
    require("lsp_signature").on_attach()
  end

  -- auto-session
  require('auto-session').setup()
end

if vim.fn.isdirectory(install_path) == 0 then
  print("Installing dependencies.")
  vim.fn.system { 'git', 'clone', '--depth=1', 'https://github.com/wbthomason/packer.nvim', install_path }
end
load_plugins()
require('packer').sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua load_config()]]
```
1. Open nvim `nvim -u minimal.lua`
2. Edit a scala file
3. Save session
4. Exit Nvim
5. Open Nvim again with the same command as in number 1 (This should trigger VimEnter and run `LuaAutoRestoreSession()`)

**Expected behavior**
- `:echo &filetype` should give `scala`
- `FileType` event should have been triggered
- The string `>>> ATTACHINGGGG!!!!!!!!!!!!!!!!!!!!!!!` should appear in `:messages`
- `lsp_signature` should be working

**Actual behaviour**
`:echo &filetype` returns `scala` but without triggering (that's what it looks like at least) FileType event. 

If I manually do `set filetype=scala` it works again.

**Baseline (please complete the following information):**
 - OS. e.g `uname -a`: Darwin nb-cenrique.local 21.1.0 Darwin Kernel Version 21.1.0: Wed Oct 13 17:33:23 PDT 2021; root:xnu-8019.41.5~1/RELEASE_X86_64 x86_64
 - Neovim version `nvim --version`
 ```
NVIM v0.5.1
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: clang -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -O2 -DNDEBUG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/tmp/neovim-20210927-1441-demfsz/neovim-0.5.1/build/config -I/tmp/neovim-20210927-1441-demfsz/neovim-0.5.1/src -I/usr/local/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX11.sdk/usr/include -I/usr/local/opt/gettext/include -I/tmp/neovim-20210927-1441-demfsz/neovim-0.5.1/build/src/nvim/auto -I/tmp/neovim-20210927-1441-demfsz/neovim-0.5.1/build/include
Compiled by brew@BigSur

Features: +acl +iconv +tui
```

**Comment by rmagatti** [comment]
Hey, thanks for the submission.

So I tried your minimal config, had to change it a bit since with that one you'd only set the autocmd for the filetype after packer complete runs, which would be after the initial read of the buffer.

It works perfectly for me here without having to set the ft manually or re-read the buffer with `:e`.

I'm also on neovim head, but I don't think that should play a part here. 0.5.1 should be enough afaik.
<img width="879" alt="Screen Shot 2021-11-23 at 10 08 24 PM" src="https://user-images.githubusercontent.com/2881382/143178325-d400c985-f2db-447e-8144-a9817d6b08b7.png">

**Comment by caenrique** [comment]
Hi, thanks for the response!
I think I had some problems with the loading order of my config and trying to reproduce it with the minimal config I didn't noticed that, so thanks for pointing that out :)
🤦🏻 I was going crazy hahaha

**Comment by rmagatti** [comment]
Happens haha cheers.
