### ISSUE TITLE
Recommending `options` in sessionoptions can cause problems

### ISSUE THREAD

**Issue by TC72** [rmagatti/auto-session#97]
1st of all, thanks for the plug in, so far most of it is great but I hit a real problem by following the recommendation to include `options` in `sessionoptions`.

This was causing keymaps to be stored in the session which broke my set-up. It looked like `nvim-cmp` was causing my errors but uninstalling it completely still caused problems. After a lot of checking I realised my problems were due to keymaps in the session.

I'd suggest removing `options` from the recommended settings, neovim don't use it in their default:
```
default: "blank,buffers,curdir,folds,help,tabpages,winsize"
Vi default: "blank,buffers,curdir,folds,help,options,tabpages,winsize")
```

**Comment by rmagatti** [comment]
Hey, I think there's a note right after the recommended sessionoptions about options and lazy loading. Was the problem you saw related to lazy loading too?

I guess I could just remove that as recommended instead of having a note about it.

**Comment by TC72** [comment]
@rmagatti thanks for the quick response, no I don't think it's to do with lazyloading.
The thinks stored in the session when using `options` is going to cause problems, probably why neovim don't have it in their defaults.

Someone else commented on the issue I posted on the nvim-cmp page saying they also had an issue due to auto-session.
https://github.com/hrsh7th/nvim-cmp/issues/569

**Comment by rmagatti** [comment]
Oh I see. Sounds good. I'll edit the readme soon!

Thanks a lot!
